import type { Article } from './types';

/**
 * RE GEN Academy Journal
 * Staff training articles — real situations, real scripts, real guidance
 */

export const ARTICLES: Article[] = [
  {
    id: 'a1',
    cat: 'Front desk',
    pinned: true,
    title: 'How to answer the BPC-157 question in thirty seconds',
    dek: 'The most common peptide question we get, and a repeatable three-move answer that never crosses the line.',
    author: 'Danielle',
    date: 'Aug 2026',
    read: '4 min',
    body: [
      { p: "Someone is going to ask you about BPC-157 this week. Probably at the front desk, probably while three other things are happening. You don't need a lecture ready — you need three moves." },
      { h: 'Move one: name it plainly' },
      { p: '"It\'s a peptide — a short chain of amino acids — that\'s been studied for tissue repair and gut lining." That\'s it. You\'ve told them something true and specific in one breath, and you\'ve already outperformed most of what they read online.' },
      { h: 'Move two: say where the research stands' },
      { p: '"Most of what exists is research-use-only, so it\'s studied for those things rather than approved to treat them." This sentence is doing enormous work. It\'s honest, it protects the practice, and it quietly signals that we know the difference — which is the whole reason they should trust us over a website.' },
      { h: 'Move three: hand it off warmly' },
      { quote: '"Whether it makes sense for you specifically is exactly what Ryan looks at. Want me to find you twenty minutes this week?"' },
      { p: "Notice what that last line does. It doesn't say no. It doesn't say \"I can't answer that.\" It says the honest thing — that suitability is a medical question — and it converts. Every time you run this sequence you should end up with a booked consult, not a dead end." },
      { callout: 'The trap to avoid: any version of "it\'s safe" or "it should be fine for you." Those five words turn a great interaction into a compliance problem. There is no situation where they\'re ours to say.' },
      { h: 'If they push' },
      { list: [
        { text: '"My friend takes it and it\'s fine." — "That\'s great for her. Everyone\'s screening looks different, which is why Ryan does his own."' },
        { text: '"Can\'t you just tell me the dose?" — "That part genuinely isn\'t mine, and you\'d want it to come from him anyway."' },
        { text: '"Do you sell it?" — Answer the menu question plainly, then route back to the consult.' },
      ] },
      { p: "Run it three times and it stops feeling like a script. It just becomes how you talk." },
    ],
  },
  {
    id: 'a2',
    cat: 'Safety',
    title: 'The biotin question we should ask before every lab draw',
    dek: "A hair-skin-nails gummy can throw a thyroid panel far enough to send someone to a cardiologist. Here's why, and the one question that prevents it.",
    author: 'Ryan Kent, NP',
    date: 'Aug 2026',
    read: '3 min',
    body: [
      { p: "This one is worth knowing cold, because it's the rare case where a supplement most people consider harmless can produce a genuinely alarming lab result." },
      { h: 'What actually happens' },
      { p: "A lot of lab immunoassays use a biotin-streptavidin binding step in their chemistry. When there's a large amount of biotin circulating in the sample, it competes with that step. Depending on how the particular assay is built, the result comes back falsely high or falsely low." },
      { p: 'The tests most affected are the ones we order most: TSH, free T4, free T3, and — importantly — troponin, the cardiac marker used in emergency departments to evaluate chest pain.' },
      { callout: "There are documented cases of high-dose biotin producing thyroid results that looked like Graves' disease, and troponin results that looked normal in someone actually having a cardiac event. This isn't a theoretical interference." },
      { h: 'Why our clients are high risk for it' },
      { p: "Biotin is the headline ingredient in nearly every hair, skin and nail supplement sold — which is to say, the exact category our clients buy. Doses in those products routinely run far above what anyone needs from food. And because it's marketed as a beauty supplement rather than a medication, clients almost never think to mention it." },
      { h: 'The one question' },
      { quote: '"Before I get you scheduled — are you taking any hair, skin and nail vitamins, or a biotin supplement?"' },
      { p: "Ask it at booking, not at the draw. If the answer is yes, flag it to me. You can absolutely tell a client that biotin is known to interfere with lab results — that's education. What you should not do is tell them to stop taking it, or for how long. Stopping a supplement before a draw is an instruction with a clinical timeline attached, and that's mine." },
      { p: "One question at booking. It's the cheapest safety intervention in the building." },
    ],
  },
  {
    id: 'a3',
    cat: 'Compliance',
    title: 'When a client texts you her lab screenshot',
    dek: "It will happen. The instinct to be helpful is exactly what makes this dangerous — and there's a warm way to hold the line.",
    author: 'Ryan Kent, NP',
    date: 'Jul 2026',
    read: '4 min',
    body: [
      { p: 'A client screenshots her panel and sends it over with "is this bad??" She trusts you. She\'s anxious. You can see the number and the reference range right there on the screen. Everything about the moment is pulling you toward answering.' },
      { p: "Don't. Not because of a rule for its own sake, but because of what interpretation actually requires." },
      { h: 'Why the number alone means nothing' },
      { p: "A TSH of 3.8 means something completely different in a 28-year-old trying to conceive than it does in a 61-year-old on thyroid medication, and different again if she's on biotin, three weeks postpartum, or acutely unwell. Interpretation isn't reading a number against a range — it's reading a number against a person. That's the entire job, and it's why it takes a license." },
      { callout: '"It\'s within range" is interpretation. So is "that looks a little high." So is sending her the reference range and letting her draw the conclusion. All three are the same act.' },
      { h: 'What to send instead' },
      { quote: '"I can see it — and I\'m honestly not the right person to read it, because what a number means depends on your whole picture. Let me get you on Ryan\'s schedule this week so you\'re not sitting with it. Are mornings or afternoons better?"' },
      { p: "Three things happen in that message. You acknowledge her instead of stonewalling. You give her a real reason rather than hiding behind policy. And you end with a question, so the conversation moves toward an appointment instead of stalling." },
      { h: 'What not to do' },
      { list: [
        { text: "Don't say \"I'm not allowed to tell you.\" It sounds like we're hiding something." },
        { text: "Don't guess and then hedge. A hedged interpretation is still an interpretation." },
        { text: "Don't leave her waiting overnight. Anxiety plus silence sends people to Google, and Google will interpret it for her." },
        { text: "Don't forward the screenshot into a group chat or anywhere outside the chart. It's PHI." },
      ] },
      { p: "Handled well, this is one of the highest-trust moments we get. She learns that we take her seriously and that we don't wing it. That's the whole brand in one text message." },
    ],
  },
  {
    id: 'a4',
    cat: 'Hormones',
    title: 'Perimenopause: the first five minutes decide everything',
    dek: "Most of these clients have already been told they're fine. What you say before Ryan walks in determines whether they come back.",
    author: 'Danielle',
    date: 'Jul 2026',
    read: '5 min',
    body: [
      { p: "Here is the pattern, and once you see it you'll see it every week. A woman in her mid-forties books a consult. She's exhausted, not sleeping, her cycle has gone strange, her body composition changed without her habits changing, and she feels like a different person. She has already been to at least one provider who ran a panel, told her it was normal, and suggested she manage her stress." },
      { p: "She is not arriving hopeful. She's arriving to see whether we'll do it too." },
      { h: 'What she needs in the first five minutes' },
      { p: "Not answers — you don't have those and shouldn't offer them. What she needs is evidence that somebody is going to take the whole picture seriously. That's entirely within your scope and it's most of the work." },
      { list: [
        { text: 'Ask what changed, and when. Then be quiet and let her finish.' },
        { text: 'Write it down where she can see you writing it down.' },
        { text: 'Use the real words. "Perimenopause can start years before cycles stop, and symptoms often show up before labs do." That single sentence has visibly relaxed clients.' },
        { text: "Tell her what Ryan will actually look at, and that he reads the numbers alongside what she's describing." },
      ] },
      { quote: '"You\'re not imagining this, and you\'re not the first person to be told you\'re fine while feeling like that."' },
      { p: "That's the most useful sentence you can say, and it diagnoses nothing. Read it again — it validates her experience and makes no clinical claim whatsoever. That's the line we walk, and it's walkable." },
      { h: 'Where the line is' },
      { p: "You can name what perimenopause is and describe the general arc. You cannot tell her that's what she has. You can say the panel includes estradiol, progesterone, FSH and thyroid markers. You cannot tell her what any of her results mean. You can explain that progesterone and progestin are different things — genuinely one of the most valuable clarifications in this whole category, because she's probably carrying a bad experience with an old pill." },
      { callout: "Anything about her history that touches breast or uterine cancer, a clotting disorder, or unexplained bleeding stops the conversation and goes to Ryan. Not later in the visit. Then." },
      { h: 'The handoff' },
      { p: "When Ryan comes in, say what you heard in front of her: \"Sarah's noticed changes over the last eighteen months, mostly sleep and cycle, and she's tracked it.\" She hears that she was listened to and that nothing got lost. He starts three minutes ahead. Nobody repeats themselves." },
      { p: "That's the entire difference between a client who books a program and one who never comes back." },
    ],
  },
  {
    id: 'a5',
    cat: 'IV therapy',
    title: 'Why the NAD+ appointment needs a phone call first',
    dek: 'Our longest, most uncomfortable and most complained-about appointment — and how ten minutes of prep turns it into our best story.',
    author: 'Michelle',
    date: 'Jul 2026',
    read: '3 min',
    body: [
      { p: "NAD+ is the appointment most likely to generate a complaint, and almost none of those complaints are about the product. They're about expectations nobody set." },
      { h: "What clients don't know until they're in the chair" },
      { list: [
        { text: 'It takes a long time. Significantly longer than any other drip on the menu.' },
        { text: "Chest tightness, cramping, flushing and nausea during the infusion are common, and they're overwhelmingly related to how fast it's running." },
        { text: "Slowing the drip usually settles it — but that adjustment is a clinical decision, so Ryan makes it, not the client and not us." },
        { text: 'They should eat beforehand and bring something to do. Nobody enjoys this appointment on an empty stomach with a dead phone.' },
      ] },
      { callout: 'Say all of that on the phone before they come in. A client who was warned describes the same sensations as "intense but manageable." A client who wasn\'t describes them as "nobody told me it would feel like that." Identical infusion, opposite review.' },
      { h: 'The call takes four minutes' },
      { quote: '"Two things before Thursday: block out the afternoon rather than an hour, and eat a real meal beforehand. Some people feel tightness or cramping while it runs — that\'s normal and it\'s about the speed, so tell us the second you feel it and Ryan will adjust. Bring headphones."' },
      { p: "That's it. And note the framing on symptoms: you're telling her to report it, not reassuring her it's nothing. You've prepared her without making a clinical promise." },
      { h: 'And one thing to get right' },
      { p: "If a client tells you she had chest tightness at a previous appointment, that goes to Ryan before she's booked again — every time, without a reassuring preface. Reporting a symptom is never something we smooth over. The prep call exists to make the appointment comfortable, not to explain away anything that happened in it." },
    ],
  },
  {
    id: 'a6',
    cat: 'Compliance',
    pinned: true,
    title: 'The words that cross the line',
    dek: 'A quick reference for what we can and cannot say — and the difference between "studied for" and "treats."',
    author: 'Ryan Kent, NP',
    date: 'Aug 2026',
    read: '3 min',
    body: [
      { p: "Everything we say in marketing, on the phone, in DMs, and at the front desk needs to work if a regulator reads it. This is the quick reference for the language that keeps us compliant." },
      { h: 'What you CAN say' },
      { list: [
        { text: '"BPC-157 is studied for tissue repair." — Educational, accurate, doesn\'t promise an outcome.' },
        { text: '"Ryan screens everyone before prescribing." — True, positions the consult correctly.' },
        { text: '"Many clients report feeling more energy." — Anecdotal framing, not a claim.' },
        { text: '"This is what the research shows." — Educational context.' },
      ] },
      { h: 'What you CANNOT say' },
      { list: [
        { text: '"BPC-157 will heal your tendon." — Outcome promise. Never.' },
        { text: '"You\'d be a good candidate for this." — That\'s a clinical judgment. Not yours.' },
        { text: '"It\'s safe." — Safety is individual. Route to Ryan.' },
        { text: '"This treats anxiety/depression/any condition." — Medical claims require approval we don\'t have.' },
      ] },
      { callout: 'The rule: describe, educate, and route. Never diagnose, promise, or prescribe.' },
      { h: 'The evidence-tier language' },
      { p: "FDA-approved: \"approved for\" the labeled indication. Compounded: \"prescribed by Ryan, prepared by a licensed pharmacy.\" Research-use-only (RUO): \"studied for\" — never \"proven,\" \"treats,\" or \"cures.\"" },
      { p: "This precision isn't being picky — it's being professional. It's also what keeps us compliant with regulators who do read our content." },
    ],
  },
  {
    id: 'a7',
    cat: 'Weight loss',
    title: 'The muscle preservation conversation no one else has',
    dek: 'Weight loss includes muscle loss unless you do something about it. Here\'s how to explain why that matters.',
    author: 'Danielle',
    date: 'Aug 2026',
    read: '4 min',
    body: [
      { p: "Clients come in wanting to lose weight. They've heard about semaglutide or tirzepatide, they've seen the results on social media, and they want in. What they haven't heard is this: losing 30 pounds of which 10 is muscle is not a win." },
      { h: 'Why this matters' },
      { p: "Muscle is metabolically active tissue. It burns calories at rest. It's what keeps you functional as you age. Lose too much of it during a weight loss phase and you end up with a lower metabolic rate, less strength, and harder rebounds." },
      { p: "The providers who skip this conversation do their clients a disservice. We don't." },
      { h: 'What we do differently' },
      { list: [
        { text: 'Protein guidance: most clients undereat protein during weight loss. We address that.' },
        { text: 'Resistance training: it\'s not optional. Lifting or resistance work preserves lean mass.' },
        { text: 'Body composition monitoring: Ryan tracks more than scale weight.' },
        { text: 'Titration pacing: rapid loss isn\'t always the goal — sustainable loss is.' },
      ] },
      { h: 'How to explain it to clients' },
      { quote: '"Our program pairs the medication with protein guidance and training recommendations. That\'s because we care about what you lose, not just how much. Ryan monitors your body composition, not just the scale."' },
      { p: "That framing turns a price conversation into a value conversation. They're not just getting a vial — they're getting a program." },
      { callout: 'This is one of our biggest differentiators. Know it cold.' },
    ],
  },
  {
    id: 'a8',
    cat: 'Front desk',
    title: 'When they mention gray-market peptides',
    dek: 'Clients who\'ve bought peptides online are not bad people — they\'re curious people. Here\'s how to have that conversation.',
    author: 'Michelle',
    date: 'Jul 2026',
    read: '4 min',
    body: [
      { p: "Peptides are available online from dozens of unregulated vendors. Some clients buy them because they're cheaper, more accessible, or because they don't know the difference. They came to us, which means they're open to doing this properly." },
      { callout: 'Never make the client feel stupid for buying online. They were trying to solve a problem. Now they\'re here, which means they want to do it right. Meet them where they are.' },
      { h: 'Quality concerns are real' },
      { list: [
        { text: 'No third-party purity testing on gray-market products' },
        { text: 'Sterility not guaranteed — bacterial contamination is possible' },
        { text: 'Dose inconsistency: actual content may differ from label' },
        { text: 'Mislabeling: some vials contain different compounds entirely' },
      ] },
      { p: "These aren't scare tactics; they're documented problems. Clients deserve to know why our sourcing from licensed 503B compounding pharmacies is different." },
      { h: 'The script that works' },
      { quote: '"I can\'t speak to what\'s in products from other sources — there\'s a lot of variability in quality out there. What we use comes from licensed compounding pharmacies with testing and sterility standards. Ryan can look at what you\'ve been taking and help you transition to something with proper oversight if that makes sense."' },
      { p: "Notice what that does: doesn't disparage, highlights the quality difference, routes to Ryan for evaluation." },
      { h: 'When to escalate immediately' },
      { list: [
        { text: 'Client reports unusual symptoms from gray-market peptides' },
        { text: 'Client is stacking multiple compounds from unknown sources' },
        { text: 'Client asks for dosing advice on products they purchased elsewhere' },
      ] },
      { p: "Any safety concern goes to Ryan immediately. Not later in the visit. Now." },
    ],
  },
  {
    id: 'a9',
    cat: 'Weight loss',
    title: 'Semaglutide vs tirzepatide: how to explain the difference',
    dek: 'The question clients ask most, answered in a way that educates without making a clinical call.',
    author: 'Ryan Kent, NP',
    date: 'Aug 2026',
    read: '3 min',
    body: [
      { p: "\"Which one should I take?\" is the most common GLP-1 question. Here's how to answer it without crossing into clinical territory." },
      { h: 'The actual difference' },
      { p: "Semaglutide is a GLP-1 receptor agonist. Tirzepatide is a dual agonist — it acts on both GLP-1 and GIP receptors. That's the headline difference." },
      { p: "GLP-1 signals satiety. GIP (glucose-dependent insulinotropic polypeptide) affects insulin secretion and may have additional metabolic effects. Tirzepatide targets both." },
      { h: 'Is one better?' },
      { p: "That depends on the person. Some respond better to one than the other. Some have different side-effect profiles. Some have insurance or cost considerations. This is exactly why we screen — and why Ryan, not Google, makes the recommendation." },
      { h: 'The script' },
      { quote: '"They work differently — semaglutide targets GLP-1, tirzepatide targets both GLP-1 and GIP. Which is right for you depends on your history, your goals, and how you respond. That\'s what the consult is for."' },
      { p: "That's factual distinction without making the clinical call. It positions the consult as valuable." },
      { callout: 'Never recommend one over the other. That\'s Ryan\'s job after the full evaluation.' },
    ],
  },
  {
    id: 'a10',
    cat: 'Peptides',
    title: 'What peptides are NOT',
    dek: 'NAD+ is not a peptide. MK-677 is not a peptide. Knowing the difference makes you the expert in the room.',
    author: 'Danielle',
    date: 'Jul 2026',
    read: '3 min',
    body: [
      { p: "Clients lump a lot of things together under \"peptides\" that aren't peptides at all. Knowing what's actually what makes you credible." },
      { h: 'NAD+: a coenzyme' },
      { p: "NAD+ (nicotinamide adenine dinucleotide) shows up constantly in longevity conversations. It's central to cellular energy production. But it's not a peptide — it's a coenzyme, a completely different class of molecule." },
      { p: "When a client says \"I want the NAD+ peptide,\" you can gently correct: \"NAD+ is actually a coenzyme, not a peptide — but we do offer it in our IV services. Let me tell you about that.\"" },
      { h: 'MK-677: a non-peptide secretagogue' },
      { p: "MK-677 is an oral, non-peptide growth hormone secretagogue. It mimics ghrelin and stimulates GH release — the same end goal as some peptides — but it's a small molecule, not a peptide chain. That's why it can be taken orally." },
      { h: 'Creatine: an amino acid derivative' },
      { p: "Creatine is an amino acid derivative — made from arginine, glycine, and methionine — but it's not a peptide. It's not a chain of amino acids; it's a single small molecule." },
      { h: 'Quick reference' },
      { list: [
        { text: 'Peptide: a chain of amino acids (2-50+). Examples: BPC-157, semaglutide, insulin.' },
        { text: 'Coenzyme: a non-protein molecule that helps enzymes work. Example: NAD+.' },
        { text: 'Small molecule secretagogue: triggers hormone release but isn\'t a peptide. Example: MK-677.' },
        { text: 'Amino acid derivative: made from amino acids but not a chain. Example: creatine.' },
      ] },
      { callout: 'Precision makes you credible. Know what\'s actually what.' },
    ],
  },
  {
    id: 'a11',
    cat: 'Sexual health',
    title: 'The PT-141 conversation: lead with privacy',
    dek: 'This is our most sensitive consult. Many clients have never had anyone take this seriously.',
    author: 'Ryan Kent, NP',
    date: 'Aug 2026',
    read: '3 min',
    body: [
      { p: "Sexual health, desire, and intimacy are topics clients often struggle to discuss. Making someone feel comfortable is half the job." },
      { h: 'What PT-141 actually is' },
      { p: "PT-141 (bremelanotide) is a melanocortin receptor agonist. Unlike medications that work on blood flow, it acts centrally in the brain. It's FDA-approved as Vyleesi for hypoactive sexual desire disorder in premenopausal women." },
      { p: "Clients often don't understand this distinction. You can explain the mechanism — central action versus peripheral — without making a suitability judgment." },
      { h: 'The script that works' },
      { quote: '"You\'re in the right place to ask about that. PT-141 works differently than you might expect — it acts in the brain, not on blood flow. Ryan does all the screening for this program and keeps everything private. Would you like me to book you a consult?"' },
      { p: "Notice what that does: normalizes the question, gives one interesting fact, emphasizes privacy, routes to Ryan." },
      { h: 'The hormone connection' },
      { p: "Sexual health conversations often reveal hormone questions underneath. Testosterone, estrogen, progesterone — all affect desire. PT-141 is one option, and sometimes the root is hormonal. Ryan evaluates the whole picture." },
      { callout: 'Lead with compassion and privacy. Many clients have never had anyone take this seriously.' },
    ],
  },
  {
    id: 'a12',
    cat: 'IV therapy',
    title: 'The pre-infusion screening you do every single time',
    dek: 'What we check before any IV starts — and why skipping it is never an option.',
    author: 'Ryan Kent, NP',
    date: 'Aug 2026',
    read: '3 min',
    body: [
      { p: "Every IV visit starts with the same screening. This isn't bureaucracy — it's how we catch the things that change between visits." },
      { h: 'The checklist' },
      { list: [
        { text: 'Blood pressure and vitals check' },
        { text: 'Full health history review (or update from last visit)' },
        { text: 'Current medications — anything new or changed?' },
        { text: 'Allergies and prior reactions review' },
        { text: 'Pregnancy or breastfeeding status' },
        { text: 'Kidney, heart, and liver considerations' },
        { text: 'Hydration status and recent labs when relevant' },
      ] },
      { h: 'Why it matters every time' },
      { p: "A client who was fine three weeks ago may have started a new medication. May have had a health event. May be pregnant now. The screen catches what's changed — and it's why we run it every single visit, not just the first one." },
      { h: 'The cautions' },
      { list: [
        { text: 'Kidney or heart conditions: fluid loads may not be appropriate' },
        { text: 'Pregnant or breastfeeding: some ingredients avoided' },
        { text: 'G6PD deficiency: high-dose Vitamin C contraindicated' },
        { text: 'Allergies to any ingredient: screened before drip selection' },
        { text: 'Blood-thinners or medication interactions: reviewed' },
      ] },
      { callout: 'We screen like a medical practice because we are one. This is the difference between us and a pop-up IV bar.' },
    ],
  },
];
