import type { Article } from './types';

export const ARTICLES: Article[] = [
  {
    id: 'a1',
    cat: 'Front desk',
    pinned: true,
    title: 'How to answer the BPC-157 question in thirty seconds',
    dek: 'The most common peptide question we get, and a repeatable three-move answer that never crosses the line.',
    author: 'Danielle',
    date: 'Aug 2026',
    read: '4 min',
    body: [
      { p: "Someone is going to ask you about BPC-157 this week. Probably at the front desk, probably while three other things are happening. You don't need a lecture ready — you need three moves." },
      { h: 'Move one: name it plainly' },
      { p: '"It\'s a peptide — a short chain of amino acids — that\'s been studied for tissue repair and gut lining." That\'s it. You\'ve told them something true and specific in one breath, and you\'ve already outperformed most of what they read online.' },
      { h: 'Move two: say where the research stands' },
      { p: '"Most of what exists is research-use-only, so it\'s studied for those things rather than approved to treat them." This sentence is doing enormous work. It\'s honest, it protects the practice, and it quietly signals that we know the difference — which is the whole reason they should trust us over a website.' },
      { h: 'Move three: hand it off warmly' },
      { quote: '"Whether it makes sense for you specifically is exactly what Ryan looks at. Want me to find you twenty minutes this week?"' },
      { p: "Notice what that last line does. It doesn't say no. It doesn't say \"I can't answer that.\" It says the honest thing — that suitability is a medical question — and it converts. Every time you run this sequence you should end up with a booked consult, not a dead end." },
      { callout: 'The trap to avoid: any version of "it\'s safe" or "it should be fine for you." Those five words turn a great interaction into a compliance problem. There is no situation where they\'re ours to say.' },
      { h: 'If they push' },
      { list: [
        { text: '"My friend takes it and it\'s fine." — "That\'s great for her. Everyone\'s screening looks different, which is why Ryan does his own."' },
        { text: '"Can\'t you just tell me the dose?" — "That part genuinely isn\'t mine, and you\'d want it to come from him anyway."' },
        { text: '"Do you sell it?" — Answer the menu question plainly, then route back to the consult.' },
      ] },
      { p: "Run it three times and it stops feeling like a script. It just becomes how you talk." },
    ],
  },
  {
    id: 'a2',
    cat: 'Safety',
    title: 'The biotin question we should ask before every lab draw',
    dek: "A hair-skin-nails gummy can throw a thyroid panel far enough to send someone to a cardiologist. Here's why, and the one question that prevents it.",
    author: 'Ryan Kent, NP',
    date: 'Aug 2026',
    read: '3 min',
    body: [
      { p: "This one is worth knowing cold, because it's the rare case where a supplement most people consider harmless can produce a genuinely alarming lab result." },
      { h: 'What actually happens' },
      { p: "A lot of lab immunoassays use a biotin-streptavidin binding step in their chemistry. When there's a large amount of biotin circulating in the sample, it competes with that step. Depending on how the particular assay is built, the result comes back falsely high or falsely low." },
      { p: 'The tests most affected are the ones we order most: TSH, free T4, free T3, and — importantly — troponin, the cardiac marker used in emergency departments to evaluate chest pain.' },
      { callout: "There are documented cases of high-dose biotin producing thyroid results that looked like Graves' disease, and troponin results that looked normal in someone actually having a cardiac event. This isn't a theoretical interference." },
      { h: 'Why our clients are high risk for it' },
      { p: "Biotin is the headline ingredient in nearly every hair, skin and nail supplement sold — which is to say, the exact category our clients buy. Doses in those products routinely run far above what anyone needs from food. And because it's marketed as a beauty supplement rather than a medication, clients almost never think to mention it." },
      { h: 'The one question' },
      { quote: '"Before I get you scheduled — are you taking any hair, skin and nail vitamins, or a biotin supplement?"' },
      { p: "Ask it at booking, not at the draw. If the answer is yes, flag it to me. You can absolutely tell a client that biotin is known to interfere with lab results — that's education. What you should not do is tell them to stop taking it, or for how long. Stopping a supplement before a draw is an instruction with a clinical timeline attached, and that's mine." },
      { p: "One question at booking. It's the cheapest safety intervention in the building." },
    ],
  },
  {
    id: 'a3',
    cat: 'Compliance',
    title: 'When a client texts you her lab screenshot',
    dek: "It will happen. The instinct to be helpful is exactly what makes this dangerous — and there's a warm way to hold the line.",
    author: 'Ryan Kent, NP',
    date: 'Jul 2026',
    read: '4 min',
    body: [
      { p: 'A client screenshots her panel and sends it over with "is this bad??" She trusts you. She\'s anxious. You can see the number and the reference range right there on the screen. Everything about the moment is pulling you toward answering.' },
      { p: "Don't. Not because of a rule for its own sake, but because of what interpretation actually requires." },
      { h: 'Why the number alone means nothing' },
      { p: "A TSH of 3.8 means something completely different in a 28-year-old trying to conceive than it does in a 61-year-old on thyroid medication, and different again if she's on biotin, three weeks postpartum, or acutely unwell. Interpretation isn't reading a number against a range — it's reading a number against a person. That's the entire job, and it's why it takes a license." },
      { callout: '"It\'s within range" is interpretation. So is "that looks a little high." So is sending her the reference range and letting her draw the conclusion. All three are the same act.' },
      { h: 'What to send instead' },
      { quote: '"I can see it — and I\'m honestly not the right person to read it, because what a number means depends on your whole picture. Let me get you on Ryan\'s schedule this week so you\'re not sitting with it. Are mornings or afternoons better?"' },
      { p: "Three things happen in that message. You acknowledge her instead of stonewalling. You give her a real reason rather than hiding behind policy. And you end with a question, so the conversation moves toward an appointment instead of stalling." },
      { h: 'What not to do' },
      { list: [
        { text: "Don't say \"I'm not allowed to tell you.\" It sounds like we're hiding something." },
        { text: "Don't guess and then hedge. A hedged interpretation is still an interpretation." },
        { text: "Don't leave her waiting overnight. Anxiety plus silence sends people to Google, and Google will interpret it for her." },
        { text: "Don't forward the screenshot into a group chat or anywhere outside the chart. It's PHI." },
      ] },
      { p: "Handled well, this is one of the highest-trust moments we get. She learns that we take her seriously and that we don't wing it. That's the whole brand in one text message." },
    ],
  },
  {
    id: 'a4',
    cat: 'Hormones',
    title: 'Perimenopause: the first five minutes decide everything',
    dek: "Most of these clients have already been told they're fine. What you say before Ryan walks in determines whether they come back.",
    author: 'Danielle',
    date: 'Jul 2026',
    read: '5 min',
    body: [
      { p: "Here is the pattern, and once you see it you'll see it every week. A woman in her mid-forties books a consult. She's exhausted, not sleeping, her cycle has gone strange, her body composition changed without her habits changing, and she feels like a different person. She has already been to at least one provider who ran a panel, told her it was normal, and suggested she manage her stress." },
      { p: "She is not arriving hopeful. She's arriving to see whether we'll do it too." },
      { h: 'What she needs in the first five minutes' },
      { p: "Not answers — you don't have those and shouldn't offer them. What she needs is evidence that somebody is going to take the whole picture seriously. That's entirely within your scope and it's most of the work." },
      { list: [
        { text: 'Ask what changed, and when. Then be quiet and let her finish.' },
        { text: 'Write it down where she can see you writing it down.' },
        { text: 'Use the real words. "Perimenopause can start years before cycles stop, and symptoms often show up before labs do." That single sentence has visibly relaxed clients.' },
        { text: "Tell her what Ryan will actually look at, and that he reads the numbers alongside what she's describing." },
      ] },
      { quote: '"You\'re not imagining this, and you\'re not the first person to be told you\'re fine while feeling like that."' },
      { p: "That's the most useful sentence you can say, and it diagnoses nothing. Read it again — it validates her experience and makes no clinical claim whatsoever. That's the line we walk, and it's walkable." },
      { h: 'Where the line is' },
      { p: "You can name what perimenopause is and describe the general arc. You cannot tell her that's what she has. You can say the panel includes estradiol, progesterone, FSH and thyroid markers. You cannot tell her what any of her results mean. You can explain that progesterone and progestin are different things — genuinely one of the most valuable clarifications in this whole category, because she's probably carrying a bad experience with an old pill." },
      { callout: "Anything about her history that touches breast or uterine cancer, a clotting disorder, or unexplained bleeding stops the conversation and goes to Ryan. Not later in the visit. Then." },
      { h: 'The handoff' },
      { p: "When Ryan comes in, say what you heard in front of her: \"Sarah's noticed changes over the last eighteen months, mostly sleep and cycle, and she's tracked it.\" She hears that she was listened to and that nothing got lost. He starts three minutes ahead. Nobody repeats themselves." },
      { p: "That's the entire difference between a client who books a program and one who never comes back." },
    ],
  },
  {
    id: 'a5',
    cat: 'IV therapy',
    title: 'Why the NAD+ appointment needs a phone call first',
    dek: 'Our longest, most uncomfortable and most complained-about appointment — and how ten minutes of prep turns it into our best story.',
    author: 'Michelle',
    date: 'Jul 2026',
    read: '3 min',
    body: [
      { p: "NAD+ is the appointment most likely to generate a complaint, and almost none of those complaints are about the product. They're about expectations nobody set." },
      { h: "What clients don't know until they're in the chair" },
      { list: [
        { text: 'It takes a long time. Significantly longer than any other drip on the menu.' },
        { text: "Chest tightness, cramping, flushing and nausea during the infusion are common, and they're overwhelmingly related to how fast it's running." },
        { text: "Slowing the drip usually settles it — but that adjustment is a clinical decision, so Ryan makes it, not the client and not us." },
        { text: 'They should eat beforehand and bring something to do. Nobody enjoys this appointment on an empty stomach with a dead phone.' },
      ] },
      { callout: 'Say all of that on the phone before they come in. A client who was warned describes the same sensations as "intense but manageable." A client who wasn\'t describes them as "nobody told me it would feel like that." Identical infusion, opposite review.' },
      { h: 'The call takes four minutes' },
      { quote: '"Two things before Thursday: block out the afternoon rather than an hour, and eat a real meal beforehand. Some people feel tightness or cramping while it runs — that\'s normal and it\'s about the speed, so tell us the second you feel it and Ryan will adjust. Bring headphones."' },
      { p: "That's it. And note the framing on symptoms: you're telling her to report it, not reassuring her it's nothing. You've prepared her without making a clinical promise." },
      { h: 'And one thing to get right' },
      { p: "If a client tells you she had chest tightness at a previous appointment, that goes to Ryan before she's booked again — every time, without a reassuring preface. Reporting a symptom is never something we smooth over. The prep call exists to make the appointment comfortable, not to explain away anything that happened in it." },
    ],
  },
];
