// Clinical monographs keyed by drug family. Educational summaries only —
// conservative language, no dosing. Every entry is reviewed by a provider
// before it is shown to a client, and the portal shows a standing disclaimer.
export const MONOGRAPHS = {
  semaglutide: {
    name: 'Semaglutide', tagline: 'GLP-1 for appetite & weight',
    what: 'Semaglutide is a GLP-1 receptor agonist. It mimics a natural gut hormone that signals fullness to the brain and slows how quickly the stomach empties, so you feel satisfied on less food.',
    benefits: ['Reduces appetite and food cravings', 'Supports steady, meaningful weight loss', 'Helps regulate blood sugar', 'Once-weekly options available'],
    howUsed: 'Available as a weekly subcutaneous injection or as a daily sublingual/oral disintegrating form. Your provider titrates the dose slowly.',
    contra: ['Personal or family history of medullary thyroid cancer or MEN 2', 'History of pancreatitis', 'Pregnancy, trying to conceive, or breastfeeding', 'Known hypersensitivity to GLP-1 medications'],
    side: ['Nausea, especially when starting or increasing dose', 'Constipation or diarrhea', 'Reduced appetite, early fullness', 'Injection-site reactions'],
    note: 'Nausea usually eases as your body adjusts; slow dose increases help.'
  },
  tirzepatide: {
    name: 'Tirzepatide', tagline: 'Dual GIP/GLP-1 for weight',
    what: 'Tirzepatide activates two gut-hormone receptors (GIP and GLP-1) at once. This dual action can produce strong appetite control and metabolic benefit.',
    benefits: ['Powerful appetite and craving control', 'Often greater weight loss than single-hormone options', 'Improves blood-sugar regulation', 'Once-weekly dosing'],
    howUsed: 'Weekly subcutaneous injection, or a daily sublingual/oral disintegrating form. Doses are increased gradually to limit side effects.',
    contra: ['Personal or family history of medullary thyroid cancer or MEN 2', 'History of pancreatitis', 'Pregnancy, trying to conceive, or breastfeeding', 'Severe GI disease (e.g., gastroparesis)'],
    side: ['Nausea, fullness, or reflux early on', 'Constipation or diarrhea', 'Fatigue', 'Injection-site reactions'],
    note: 'Combinations with glycine, B12 or L-carnitine aim to support energy and comfort — the active driver is tirzepatide.'
  },
  metformin: {
    name: 'Metformin', tagline: 'Insulin sensitivity & metabolic support',
    what: 'Metformin improves how your body responds to insulin and lowers the amount of sugar your liver releases. It is widely used for blood-sugar control and metabolic health.',
    benefits: ['Improves insulin sensitivity', 'Supports modest weight management', 'Helps steady blood sugar', 'Long track record of safe use'],
    howUsed: 'Taken by mouth, usually with food to reduce stomach upset.',
    contra: ['Significant kidney impairment', 'Conditions raising acid levels (metabolic acidosis)', 'Around iodinated-contrast imaging (temporary hold)', 'Heavy alcohol use'],
    side: ['Stomach upset, nausea, or diarrhea', 'Metallic taste', 'Can lower vitamin B12 over time', 'Reduced appetite'],
  },
  phentermine: {
    name: 'Phentermine', tagline: 'Short-term appetite suppressant',
    what: 'Phentermine is a stimulant-type appetite suppressant that reduces hunger signals. It is used short-term alongside diet and lifestyle changes.',
    benefits: ['Curbs appetite', 'Can increase daytime energy', 'Helpful jump-start for weight loss'],
    howUsed: 'Taken by mouth, usually in the morning to avoid sleep disruption. Often paired with topiramate.',
    contra: ['Heart disease, uncontrolled high blood pressure, or arrhythmia', 'Overactive thyroid or glaucoma', 'History of substance misuse', 'Pregnancy or breastfeeding', 'Use of MAOI medications'],
    side: ['Faster heart rate, raised blood pressure', 'Insomnia or restlessness', 'Dry mouth', 'Jitteriness'],
  },
  topiramate: {
    name: 'Topiramate', tagline: 'Appetite & craving support',
    what: 'Topiramate is used to reduce appetite and cravings (and for migraine). It is frequently combined with phentermine for weight management.',
    benefits: ['Reduces cravings and appetite', 'Can help with migraine frequency', 'Complements phentermine'],
    howUsed: 'Taken by mouth; dose is titrated up slowly.',
    contra: ['Pregnancy (risk of birth defects) — reliable contraception advised', 'Glaucoma', 'Metabolic acidosis', 'History of kidney stones'],
    side: ['Tingling in hands/feet', 'Word-finding or memory fog', 'Altered taste (especially carbonated drinks)', 'Reduced appetite'],
  },
  naltrexone: {
    name: 'Low-Dose Naltrexone (LDN)', tagline: 'Wellness & inflammation support',
    what: 'At low doses, naltrexone is used off-label to modulate the immune system and may help with inflammation, mood, and general wellness.',
    benefits: ['May help calm chronic inflammation', 'Some report better mood and sleep', 'Well tolerated at low doses'],
    howUsed: 'Taken by mouth, often at night.',
    contra: ['Current opioid use (prescription or otherwise)', 'Acute liver disease', 'Pregnancy or breastfeeding without provider guidance'],
    side: ['Vivid dreams or short-term sleep changes', 'Headache', 'Mild nausea'],
  },
  lipotropic: {
    name: 'Lipotropic / MIC + B12', tagline: 'Fat-metabolism & energy shot',
    what: 'A blend of methionine, inositol, choline (MIC) with B vitamins that supports the body\u2019s natural fat metabolism and energy production.',
    benefits: ['Supports fat metabolism', 'Boosts energy', 'Complements a weight-loss program'],
    howUsed: 'Given as an intramuscular injection, often weekly.',
    contra: ['Known allergy to any component', 'Significant liver or kidney disease', 'Pregnancy or breastfeeding without guidance'],
    side: ['Injection-site soreness', 'Mild flushing', 'Rare stomach upset'],
  },
  bpc157: {
    name: 'BPC-157', tagline: 'Recovery & tissue-repair peptide',
    what: 'BPC-157 is a research peptide studied for its role in tissue healing and gut health. It is used to support recovery from injury and inflammation.',
    benefits: ['May support tendon, muscle & joint recovery', 'Studied for gut and GI comfort', 'May help calm localized inflammation'],
    howUsed: 'Subcutaneous injection, or oral capsule for gut-focused goals.',
    contra: ['Pregnancy or breastfeeding', 'Active cancer (discuss with your provider)', 'Known peptide hypersensitivity'],
    side: ['Injection-site reactions', 'Occasional lightheadedness', 'Limited long-term human data'],
    note: 'A research peptide — used under provider supervision; not FDA-approved for treatment.'
  },
  pentadeca: {
    name: 'Pentadeca Arginate (PDA)', tagline: 'Next-gen healing peptide',
    what: 'A stabilized peptide related to BPC-157, studied for tissue repair, inflammation, and recovery, with a formulation designed for stability.',
    benefits: ['May support soft-tissue recovery', 'Studied for inflammation and healing', 'Designed for improved stability'],
    howUsed: 'Subcutaneous injection.',
    contra: ['Pregnancy or breastfeeding', 'Active cancer (discuss with your provider)', 'Peptide hypersensitivity'],
    side: ['Injection-site reactions', 'Limited long-term human data'],
    note: 'A research peptide — used under provider supervision.'
  },
  tb500: {
    name: 'TB-500 (Thymosin \u03b2-4)', tagline: 'Recovery & flexibility peptide',
    what: 'TB-500 is a research peptide fragment studied for tissue repair, flexibility, and recovery, often paired with BPC-157.',
    benefits: ['May support muscle & connective-tissue recovery', 'Studied for flexibility and range of motion', 'Often stacked with BPC-157'],
    howUsed: 'Subcutaneous injection.',
    contra: ['Pregnancy or breastfeeding', 'Active cancer (discuss with your provider)', 'Peptide hypersensitivity'],
    side: ['Injection-site reactions', 'Temporary fatigue', 'Limited long-term human data'],
    note: 'A research peptide — used under provider supervision.'
  },
  'cjc-ipamorelin': {
    name: 'CJC-1295 / Ipamorelin', tagline: 'Growth-hormone support stack',
    what: 'A pairing of growth-hormone-releasing peptides that gently prompt your body to produce more of its own growth hormone, supporting recovery, body composition, and sleep.',
    benefits: ['Supports lean body composition', 'May improve sleep quality', 'Aids recovery and vitality', 'Works with your natural GH rhythm'],
    howUsed: 'Subcutaneous injection, commonly at night.',
    contra: ['Active cancer or history of certain tumors', 'Pregnancy or breastfeeding', 'Uncontrolled diabetes without guidance'],
    side: ['Head-rush or flushing after dosing', 'Water retention or tingling', 'Injection-site reactions', 'Vivid dreams'],
    note: 'A research peptide — used under provider supervision.'
  },
  sermorelin: {
    name: 'Sermorelin', tagline: 'GH-releasing hormone',
    what: 'Sermorelin prompts the pituitary to release growth hormone naturally, supporting recovery, energy, sleep, and body composition.',
    benefits: ['Supports natural GH production', 'May improve sleep and recovery', 'Supports lean body composition'],
    howUsed: 'Subcutaneous injection, often at night.',
    contra: ['Active cancer', 'Pregnancy or breastfeeding', 'Untreated thyroid or pituitary conditions'],
    side: ['Injection-site reactions', 'Flushing or headache', 'Water retention'],
    note: 'Used under provider supervision.'
  },
  tesamorelin: {
    name: 'Tesamorelin', tagline: 'Targets visceral fat',
    what: 'Tesamorelin is a growth-hormone-releasing hormone analog studied specifically for reducing visceral (deep abdominal) fat.',
    benefits: ['Studied for visceral-fat reduction', 'Supports body composition', 'Supports natural GH release'],
    howUsed: 'Subcutaneous injection.',
    contra: ['Active cancer or pituitary tumor', 'Pregnancy or breastfeeding', 'Proliferative diabetic retinopathy'],
    side: ['Injection-site reactions', 'Joint pain or swelling', 'Fluid retention'],
    note: 'Used under provider supervision.'
  },
  motsc: {
    name: 'MOTS-c', tagline: 'Mitochondrial & metabolic peptide',
    what: 'MOTS-c is a mitochondrial-derived peptide studied for metabolism, insulin sensitivity, and physical performance.',
    benefits: ['May support metabolic health', 'Studied for exercise capacity', 'May support insulin sensitivity'],
    howUsed: 'Subcutaneous injection.',
    contra: ['Pregnancy or breastfeeding', 'Active cancer (discuss with your provider)'],
    side: ['Injection-site reactions', 'Limited long-term human data'],
    note: 'A research peptide — used under provider supervision.'
  },
  ss31: {
    name: 'SS-31 (Elamipretide)', tagline: 'Mitochondrial support',
    what: 'SS-31 is a research peptide that targets mitochondria — the cell\u2019s energy factories — and is studied for cellular energy and recovery.',
    benefits: ['Studied for cellular energy', 'May support recovery and endurance', 'Antioxidant-type mitochondrial support'],
    howUsed: 'Subcutaneous injection.',
    contra: ['Pregnancy or breastfeeding', 'Active cancer (discuss with your provider)'],
    side: ['Injection-site reactions', 'Limited long-term human data'],
    note: 'A research peptide — used under provider supervision.'
  },
  thymosin: {
    name: 'Thymosin Alpha-1', tagline: 'Immune support peptide',
    what: 'Thymosin alpha-1 is a peptide studied for modulating and strengthening immune function.',
    benefits: ['May support immune resilience', 'Studied for immune balance', 'Used in wellness and recovery protocols'],
    howUsed: 'Subcutaneous injection.',
    contra: ['Pregnancy or breastfeeding', 'Immunosuppressive therapy (discuss with your provider)', 'Organ transplant recipients'],
    side: ['Injection-site reactions', 'Mild flu-like feeling initially'],
    note: 'A research peptide — used under provider supervision.'
  },
  igflr3: {
    name: 'IGF-1 LR3', tagline: 'Growth & recovery peptide',
    what: 'A long-acting form of insulin-like growth factor studied for muscle growth and recovery.',
    benefits: ['Studied for muscle growth', 'May support recovery'],
    howUsed: 'Subcutaneous injection.',
    contra: ['Active or prior cancer', 'Pregnancy or breastfeeding', 'Low blood sugar tendencies'],
    side: ['Risk of low blood sugar', 'Injection-site reactions', 'Limited long-term human data'],
    note: 'A research peptide — requires careful provider supervision.'
  },
  epithalon: {
    name: 'Epithalon', tagline: 'Longevity & sleep peptide',
    what: 'Epithalon is a research peptide studied for its effects on the pineal gland, sleep-wake rhythm, and cellular aging.',
    benefits: ['Studied for longevity pathways', 'May support sleep and circadian rhythm', 'Antioxidant-type support'],
    howUsed: 'Subcutaneous injection, typically in short cycles.',
    contra: ['Pregnancy or breastfeeding', 'Active cancer (discuss with your provider)'],
    side: ['Injection-site reactions', 'Limited long-term human data'],
    note: 'A research peptide — used under provider supervision.'
  },
  kisspeptin: {
    name: 'Kisspeptin', tagline: 'Reproductive-hormone signaling',
    what: 'Kisspeptin is a peptide that signals the brain to support natural reproductive-hormone production, studied for libido and hormonal health.',
    benefits: ['May support natural hormone signaling', 'Studied for libido', 'Supports reproductive-axis health'],
    howUsed: 'Subcutaneous injection.',
    contra: ['Pregnancy or breastfeeding', 'Hormone-sensitive conditions (discuss with your provider)'],
    side: ['Injection-site reactions', 'Limited long-term human data'],
    note: 'A research peptide — used under provider supervision.'
  },
  ll37: {
    name: 'LL-37', tagline: 'Antimicrobial & immune peptide',
    what: 'LL-37 is a naturally occurring antimicrobial peptide studied for immune defense and tissue health.',
    benefits: ['Studied for antimicrobial defense', 'May support immune and gut health'],
    howUsed: 'Subcutaneous injection.',
    contra: ['Pregnancy or breastfeeding', 'Autoimmune conditions (discuss with your provider)'],
    side: ['Injection-site reactions', 'Limited long-term human data'],
    note: 'A research peptide — used under provider supervision.'
  },
  melanotan: {
    name: 'Melanotan II', tagline: 'Tanning & libido peptide',
    what: 'Melanotan II is a melanocortin peptide studied for skin pigmentation (tanning) and libido.',
    benefits: ['May deepen skin pigmentation with less sun', 'Some report increased libido'],
    howUsed: 'Subcutaneous injection.',
    contra: ['History of melanoma or atypical moles', 'Pregnancy or breastfeeding', 'Uncontrolled high blood pressure'],
    side: ['Nausea and flushing', 'Darkening of moles and freckles', 'Spontaneous erections', 'Appetite changes'],
    note: 'Have skin/moles evaluated before use. A research peptide — used under provider supervision.'
  },
  'semax-selank': {
    name: 'Semax / Selank', tagline: 'Focus & calm peptides',
    what: 'Semax and Selank are nootropic peptides studied for cognition, focus, mood, and stress resilience.',
    benefits: ['May support focus and mental clarity', 'Studied for calm and stress resilience', 'Non-sedating'],
    howUsed: 'Subcutaneous injection or intranasal formulations.',
    contra: ['Pregnancy or breastfeeding', 'Significant psychiatric conditions without guidance'],
    side: ['Injection-site or nasal irritation', 'Limited long-term human data'],
    note: 'A research peptide — used under provider supervision.'
  },
  'nootropic-peptide': {
    name: 'Sleep & Cognition Peptides', tagline: 'DSIP / Pinealon / PE22-28',
    what: 'A group of peptides studied for restorative sleep, relaxation, and brain health, including DSIP (delta sleep-inducing peptide).',
    benefits: ['May support deep, restorative sleep', 'Studied for relaxation and cognition'],
    howUsed: 'Subcutaneous injection, usually before bed.',
    contra: ['Pregnancy or breastfeeding', 'Combining with sedatives without guidance'],
    side: ['Injection-site reactions', 'Morning grogginess in some', 'Limited long-term human data'],
    note: 'A research peptide — used under provider supervision.'
  },
  pt141: {
    name: 'PT-141 (Bremelanotide)', tagline: 'Desire & arousal',
    what: 'PT-141 works through the brain\u2019s melanocortin pathway to support sexual desire and arousal in both women and men — a different mechanism than blood-flow medications.',
    benefits: ['Supports libido and arousal', 'Works centrally (brain-based)', 'For women and men'],
    howUsed: 'Subcutaneous injection or troche, taken before intimacy.',
    contra: ['Uncontrolled high blood pressure', 'Known cardiovascular disease', 'Pregnancy or breastfeeding'],
    side: ['Nausea', 'Flushing and headache', 'Temporary rise in blood pressure', 'Skin darkening with frequent use'],
  },
  trimix: {
    name: 'Tri-Mix', tagline: 'Prescription ED injection',
    what: 'Tri-Mix is a compounded injectable that relaxes blood vessels in the penis to produce a reliable erection, used when oral ED medications aren\u2019t enough.',
    benefits: ['Highly effective for erectile dysfunction', 'Works when pills don\u2019t', 'Fast onset'],
    howUsed: 'Self-administered penile injection, dosed precisely and demonstrated by your provider.',
    contra: ['Sickle cell disease or clotting disorders', 'Penile implants or anatomical deformity', 'History of priapism'],
    side: ['Prolonged erection (priapism) — seek care if over 4 hours', 'Injection-site pain or bruising', 'Scar tissue with long-term use'],
    note: 'First dose must be titrated in-clinic. Requires careful provider training.'
  },
  phenylephrine: {
    name: 'Phenylephrine', tagline: 'Vasoconstrictor (protocol support)',
    what: 'Phenylephrine is a vasoconstrictor used within certain urology protocols, including management of prolonged erections.',
    benefits: ['Used within specialist ED protocols'],
    howUsed: 'Administered as directed by your provider.',
    contra: ['Severe hypertension', 'Certain heart conditions', 'Pregnancy without guidance'],
    side: ['Raised blood pressure', 'Headache', 'Palpitations'],
    note: 'Used only under specific provider instruction.'
  },
  pde5: {
    name: 'Sildenafil / Tadalafil / Vardenafil', tagline: 'Erectile & blood-flow support',
    what: 'These are PDE5 inhibitors that increase blood flow to support erections. Combination troches blend more than one for onset and duration.',
    benefits: ['Reliable support for erectile function', 'Options for fast onset or longer duration', 'Convenient troche and tablet forms'],
    howUsed: 'Taken by mouth or dissolved under the tongue before intimacy.',
    contra: ['Any nitrate medication (dangerous drop in blood pressure)', 'Recent heart attack or stroke', 'Severe low blood pressure or heart failure', 'Certain eye conditions (e.g., NAION)'],
    side: ['Headache and flushing', 'Nasal congestion', 'Indigestion', 'Vision changes; rarely, prolonged erection'],
  },
  oxytocin: {
    name: 'Oxytocin', tagline: 'Connection & intimacy hormone',
    what: 'Oxytocin is the "bonding" hormone. In sublingual form it is used to support feelings of connection, mood, and intimacy.',
    benefits: ['May enhance feelings of connection', 'Supports mood and intimacy', 'Fast-dissolving forms'],
    howUsed: 'Sublingual troche or rapid-dissolve tablet.',
    contra: ['Pregnancy (unless directed)', 'Known hypersensitivity'],
    side: ['Generally well tolerated', 'Occasional nausea or headache'],
  },
  'female-desire': {
    name: 'Female Desire Troche', tagline: 'Libido blend for women',
    what: 'A compounded troche blending agents such as bremelanotide, oxytocin, and others to support desire and arousal in women.',
    benefits: ['Supports female libido and arousal', 'Convenient dissolvable troche', 'Blended, centrally-acting approach'],
    howUsed: 'Dissolved in the mouth before intimacy.',
    contra: ['Uncontrolled high blood pressure', 'Cardiovascular disease', 'Pregnancy or breastfeeding'],
    side: ['Nausea', 'Flushing', 'Headache'],
  },
  'arousal-cream': {
    name: 'Arousal Creams', tagline: 'Topical intimacy support',
    what: 'Compounded topical creams that increase local blood flow and sensitivity to support arousal.',
    benefits: ['Applied where needed, as needed', 'Supports sensitivity and arousal', 'Non-systemic option'],
    howUsed: 'Applied topically before intimacy as directed.',
    contra: ['Skin sensitivity to ingredients', 'Partner sensitivity — discuss with your provider', 'Pregnancy without guidance'],
    side: ['Local warmth, tingling, or irritation', 'Redness'],
  },
  testosterone: {
    name: 'Testosterone', tagline: 'Hormone optimization',
    what: 'Testosterone replacement restores the primary male hormone to a healthy range, supporting energy, libido, mood, muscle, and focus. Available in injection, cream, and troche forms.',
    benefits: ['Restores energy and drive', 'Supports libido and mood', 'Supports lean muscle and strength', 'Multiple delivery options'],
    howUsed: 'Intramuscular/subcutaneous injection, topical cream, or troche, based on your labs and preference.',
    contra: ['Prostate or breast cancer', 'Untreated severe sleep apnea', 'Uncontrolled heart failure', 'Trying to conceive (can reduce fertility)'],
    side: ['Acne or oily skin', 'Increased red blood cell count', 'Testicular shrinkage or reduced fertility', 'Estrogen-related effects if unmanaged'],
    note: 'Requires baseline and ongoing lab monitoring.'
  },
  'oral-testosterone': {
    name: 'Oral Testosterone (Kyzatrex)', tagline: 'Needle-free TRT',
    what: 'An oral testosterone capsule that restores testosterone without injections, for men who prefer a pill.',
    benefits: ['No injections', 'Supports energy, libido, and mood', 'Convenient daily dosing'],
    howUsed: 'Capsules taken with food, usually twice daily.',
    contra: ['Prostate or breast cancer', 'Uncontrolled heart failure', 'Trying to conceive'],
    side: ['Blood-pressure increase', 'Increased red blood cell count', 'Headache'],
    note: 'Requires blood-pressure and lab monitoring.'
  },
  nandrolone: {
    name: 'Nandrolone', tagline: 'Anabolic recovery hormone',
    what: 'Nandrolone is an anabolic hormone used in specific protocols to support joint comfort, recovery, and lean mass.',
    benefits: ['May support joint comfort and recovery', 'Supports lean mass in specific protocols'],
    howUsed: 'Injection or cream as directed.',
    contra: ['Prostate or breast cancer', 'Pregnancy', 'Cardiovascular or liver disease'],
    side: ['Hormonal suppression', 'Lipid and mood changes', 'Water retention'],
    note: 'Specialist protocol with lab monitoring.'
  },
  oxandrolone: {
    name: 'Oxandrolone', tagline: 'Oral anabolic',
    what: 'Oxandrolone is a mild oral anabolic used in select protocols for lean mass and recovery.',
    benefits: ['Supports lean mass and recovery in specific protocols'],
    howUsed: 'Oral capsule or troche as directed.',
    contra: ['Prostate or breast cancer', 'Pregnancy', 'Liver disease'],
    side: ['Liver strain', 'Cholesterol changes', 'Hormonal suppression'],
    note: 'Requires liver and lipid monitoring.'
  },
  stanozolol: {
    name: 'Stanozolol', tagline: 'Oral anabolic',
    what: 'Stanozolol is an anabolic used in select protocols; it carries notable liver and lipid considerations.',
    benefits: ['Used in specific performance/recovery protocols'],
    howUsed: 'Oral capsule or troche as directed.',
    contra: ['Prostate or breast cancer', 'Pregnancy', 'Liver disease'],
    side: ['Liver strain', 'Cholesterol changes', 'Joint dryness'],
    note: 'Requires liver and lipid monitoring.'
  },
  biest: {
    name: 'BiEst (Estriol/Estradiol)', tagline: 'Bioidentical estrogen blend',
    what: 'BiEst is a bioidentical blend of two estrogens (estriol and estradiol) used to relieve menopausal symptoms like hot flashes, sleep issues, and vaginal dryness.',
    benefits: ['Relieves hot flashes and night sweats', 'Supports mood and sleep', 'Helps vaginal and skin health', 'Bioidentical, customizable ratios'],
    howUsed: 'Topical cream (Topi-Click), sublingual, or troche.',
    contra: ['Estrogen-sensitive cancers', 'History of blood clots, stroke, or DVT', 'Unexplained vaginal bleeding', 'Pregnancy'],
    side: ['Breast tenderness', 'Spotting', 'Bloating or headache'],
    note: 'Usually paired with progesterone if you have a uterus.'
  },
  estradiol: {
    name: 'Estradiol', tagline: 'Primary estrogen',
    what: 'Estradiol is the main estrogen, used to relieve menopausal symptoms and support bone, mood, and vaginal health.',
    benefits: ['Relieves hot flashes and night sweats', 'Supports bone density', 'Supports mood, skin, and vaginal health'],
    howUsed: 'Tablet, topical cream, vaginal cream/insert, or injection.',
    contra: ['Estrogen-sensitive cancers', 'History of clots or stroke', 'Unexplained vaginal bleeding', 'Pregnancy'],
    side: ['Breast tenderness', 'Spotting', 'Bloating or nausea'],
    note: 'Pair with progesterone if you have a uterus.'
  },
  estriol: {
    name: 'Estriol', tagline: 'Gentle estrogen (vaginal/skin)',
    what: 'Estriol is a milder estrogen used especially for vaginal and skin health with a favorable safety profile.',
    benefits: ['Relieves vaginal dryness and irritation', 'Supports skin hydration', 'Gentle estrogen option'],
    howUsed: 'Topical or vaginal cream.',
    contra: ['Estrogen-sensitive cancers', 'History of clots', 'Unexplained vaginal bleeding', 'Pregnancy'],
    side: ['Local irritation', 'Breast tenderness'],
  },
  progesterone: {
    name: 'Progesterone', tagline: 'Balance, sleep & uterine protection',
    what: 'Bioidentical progesterone balances estrogen, protects the uterine lining, and often improves sleep and calm.',
    benefits: ['Balances estrogen therapy', 'Often improves sleep', 'Protects the uterine lining', 'Supports mood'],
    howUsed: 'Oral capsule (often at bedtime) or topical cream.',
    contra: ['Known breast cancer', 'Active blood clots', 'Pregnancy unless directed', 'Liver disease'],
    side: ['Drowsiness (why it\u2019s taken at night)', 'Spotting', 'Breast tenderness'],
  },
  pregnenolone: {
    name: 'Pregnenolone', tagline: 'Hormone precursor',
    what: 'Pregnenolone is a precursor the body uses to make other hormones; used to support mood, memory, and hormonal balance.',
    benefits: ['May support mood and memory', 'Upstream hormone support'],
    howUsed: 'Oral capsule.',
    contra: ['Hormone-sensitive conditions (discuss with your provider)', 'Pregnancy or breastfeeding'],
    side: ['Headache', 'Sleep changes', 'Irritability at higher doses'],
  },
  dhea: {
    name: 'DHEA / 7-Keto DHEA', tagline: 'Adrenal hormone precursor',
    what: 'DHEA is an adrenal hormone precursor that supports energy, mood, libido, and healthy aging. 7-Keto is a metabolite used more for metabolism.',
    benefits: ['Supports energy and mood', 'May support libido and body composition', 'Upstream hormone support'],
    howUsed: 'Oral capsule.',
    contra: ['Hormone-sensitive cancers (breast, prostate)', 'Pregnancy or breastfeeding', 'PCOS without guidance'],
    side: ['Acne or oily skin', 'Facial hair (women)', 'Mood changes'],
  },
  anastrozole: {
    name: 'Anastrozole', tagline: 'Estrogen control (aromatase inhibitor)',
    what: 'Anastrozole lowers estrogen by blocking the aromatase enzyme; used in hormone protocols where estrogen runs high.',
    benefits: ['Controls excess estrogen', 'Supports hormone balance in TRT protocols'],
    howUsed: 'Oral tablet or capsule, dosed conservatively.',
    contra: ['Pregnancy', 'Premenopausal use without guidance', 'Osteoporosis (use with caution)'],
    side: ['Joint aches', 'Lowered mood or libido if estrogen too low', 'Bone-density effects long-term'],
    note: 'Over-suppressing estrogen causes symptoms — dosing is careful and lab-guided.'
  },
  exemestane: {
    name: 'Exemestane', tagline: 'Estrogen control (aromatase inhibitor)',
    what: 'Exemestane is a steroidal aromatase inhibitor used to control estrogen in specific protocols.',
    benefits: ['Controls excess estrogen', 'Supports hormone balance'],
    howUsed: 'Oral tablet.',
    contra: ['Pregnancy', 'Premenopausal use without guidance'],
    side: ['Joint aches', 'Fatigue', 'Bone-density effects long-term'],
    note: 'Lab-guided dosing.'
  },
  tamoxifen: {
    name: 'Tamoxifen', tagline: 'Estrogen-receptor modulator',
    what: 'Tamoxifen blocks estrogen at certain receptors and is used in specific hormone and post-cycle protocols.',
    benefits: ['Used in specific hormone protocols', 'Supports natural hormone recovery'],
    howUsed: 'Oral tablet.',
    contra: ['History of blood clots', 'Pregnancy', 'Certain eye conditions'],
    side: ['Hot flashes', 'Clot risk', 'Mood changes'],
    note: 'Requires provider oversight.'
  },
  enclomiphene: {
    name: 'Enclomiphene', tagline: 'Boosts natural testosterone',
    what: 'Enclomiphene prompts the body to raise its own testosterone by signaling the pituitary — helpful for men who want to preserve fertility.',
    benefits: ['Raises natural testosterone', 'Preserves fertility (unlike TRT)', 'Oral, no injections'],
    howUsed: 'Oral capsule.',
    contra: ['Pre-existing clotting disorders', 'Certain eye conditions', 'Pregnancy (not for use)'],
    side: ['Mood changes', 'Visual changes (rare)', 'Headache'],
    note: 'Lab-monitored.'
  },
  clomiphene: {
    name: 'Clomiphene', tagline: 'Fertility & hormone support',
    what: 'Clomiphene stimulates the hormones that drive ovulation (women) or testosterone production (men).',
    benefits: ['Supports fertility', 'Raises natural testosterone in men'],
    howUsed: 'Oral capsule.',
    contra: ['Pregnancy', 'Liver disease', 'Certain eye conditions'],
    side: ['Hot flashes', 'Mood changes', 'Visual changes (rare)'],
    note: 'Provider-monitored.'
  },
  cabergoline: {
    name: 'Cabergoline', tagline: 'Lowers prolactin',
    what: 'Cabergoline lowers prolactin (a hormone that, when high, can affect libido, mood, and fertility).',
    benefits: ['Lowers elevated prolactin', 'May support libido and mood', 'Twice-weekly dosing'],
    howUsed: 'Oral tablet, usually twice weekly.',
    contra: ['Uncontrolled high blood pressure', 'Heart-valve disease', 'History of certain lung/heart fibrosis'],
    side: ['Nausea', 'Dizziness', 'Headache'],
    note: 'Higher long-term doses require heart-valve monitoring.'
  },
  hcg: {
    name: 'HCG', tagline: 'Testicular & fertility support',
    what: 'HCG mimics LH to stimulate the testes, helping preserve testicular size and fertility during hormone therapy.',
    benefits: ['Preserves testicular size on TRT', 'Supports fertility', 'Supports natural testosterone production'],
    howUsed: 'Subcutaneous or intramuscular injection.',
    contra: ['Hormone-sensitive cancers', 'Pregnancy', 'Known hypersensitivity'],
    side: ['Injection-site reactions', 'Mood changes', 'Breast tenderness'],
  },
  gonadorelin: {
    name: 'Gonadorelin', tagline: 'Stimulates natural hormones',
    what: 'Gonadorelin is a GnRH that signals the pituitary to release LH and FSH, supporting natural testosterone and fertility — often used as an HCG alternative.',
    benefits: ['Supports natural hormone production', 'Fertility and testicular support', 'HCG alternative'],
    howUsed: 'Subcutaneous injection.',
    contra: ['Hormone-sensitive conditions', 'Pregnancy', 'Known hypersensitivity'],
    side: ['Injection-site reactions', 'Flushing', 'Headache'],
  },
  hgh: {
    name: 'Growth Hormone (Somatropin)', tagline: 'Recombinant GH',
    what: 'Prescription recombinant human growth hormone, used for diagnosed deficiency and select protocols under close supervision.',
    benefits: ['Supports body composition', 'Supports recovery and vitality (when indicated)'],
    howUsed: 'Daily subcutaneous injection.',
    contra: ['Active cancer', 'Proliferative diabetic retinopathy', 'Critical illness', 'Pregnancy'],
    side: ['Fluid retention and swelling', 'Joint or muscle aches', 'Carpal tunnel symptoms', 'Insulin resistance'],
    note: 'Prescription hormone with strict monitoring.'
  },
  thyroid: {
    name: 'Thyroid (T3 / T4 / Armour)', tagline: 'Thyroid hormone support',
    what: 'Thyroid medications replace or supplement thyroid hormone to restore energy, metabolism, mood, and temperature regulation. Options include T4, T3, combinations, and desiccated thyroid.',
    benefits: ['Restores energy and metabolism', 'Supports mood and mental clarity', 'Customizable T3/T4 ratios'],
    howUsed: 'Oral capsule or tablet, taken consistently (often on an empty stomach).',
    contra: ['Untreated adrenal insufficiency', 'Recent heart attack', 'Overactive thyroid (thyrotoxicosis)'],
    side: ['Palpitations or racing heart if dose is high', 'Insomnia or anxiety', 'Weight or appetite changes'],
    note: 'Dosing is guided by thyroid labs and symptoms.'
  },
  finasteride: {
    name: 'Finasteride', tagline: 'DHT-blocker for hair',
    what: 'Finasteride reduces DHT, the hormone behind male-pattern hair loss, helping preserve and sometimes regrow hair.',
    benefits: ['Slows hair loss', 'Can regrow hair over months', 'Available in capsule, foam, or solution'],
    howUsed: 'Oral capsule, or topical foam/solution to limit systemic exposure.',
    contra: ['Women who are or may become pregnant should not handle it', 'Known hypersensitivity'],
    side: ['Possible sexual side effects', 'Mood changes in some', 'Breast tenderness (rare)'],
  },
  dutasteride: {
    name: 'Dutasteride', tagline: 'Dual DHT-blocker for hair',
    what: 'Dutasteride blocks DHT more completely than finasteride and is used for hair loss in topical or oral forms.',
    benefits: ['Strong DHT reduction', 'May help when finasteride isn\u2019t enough', 'Topical options available'],
    howUsed: 'Oral capsule or topical solution.',
    contra: ['Women who are or may become pregnant should not handle it', 'Known hypersensitivity'],
    side: ['Possible sexual side effects', 'Mood changes in some'],
  },
  minoxidil: {
    name: 'Minoxidil', tagline: 'Regrowth stimulator',
    what: 'Minoxidil increases blood flow to hair follicles and extends the growth phase, thickening and regrowing hair. Compounded with actives like finasteride or biotin.',
    benefits: ['Stimulates regrowth', 'Thickens existing hair', 'Topical and low-dose oral options'],
    howUsed: 'Topical foam/solution, or low-dose oral tablet.',
    contra: ['Heart conditions (oral form) without guidance', 'Pregnancy or breastfeeding', 'Scalp irritation/dermatitis'],
    side: ['Initial temporary shedding', 'Scalp dryness or irritation', 'Unwanted facial hair (topical spread)', 'Oral: fluid retention, faster heart rate'],
  },
  tretinoin: {
    name: 'Tretinoin', tagline: 'Gold-standard retinoid',
    what: 'Tretinoin is a prescription vitamin-A derivative that speeds cell turnover to smooth texture, fade dark spots, clear acne, and reduce fine lines.',
    benefits: ['Improves texture and fine lines', 'Fades dark spots and acne marks', 'Clears and prevents acne'],
    howUsed: 'Applied at night to clean, dry skin; introduce slowly and use daily SPF.',
    contra: ['Pregnancy or breastfeeding', 'Very sensitive or broken skin', 'Sunburn'],
    side: ['Peeling, dryness, and redness (a purge phase)', 'Increased sun sensitivity', 'Temporary irritation'],
  },
  hydroquinone: {
    name: 'Hydroquinone', tagline: 'Skin-brightening standard',
    what: 'Hydroquinone lightens dark spots, melasma, and hyperpigmentation by reducing melanin production — often compounded with tretinoin and other actives.',
    benefits: ['Fades dark spots and melasma', 'Evens skin tone', 'Effective in combination formulas'],
    howUsed: 'Applied as directed, typically in cycles; daily SPF is essential.',
    contra: ['Pregnancy or breastfeeding', 'Very sensitive skin'],
    side: ['Irritation or dryness', 'Sun sensitivity', 'Rare darkening with prolonged overuse (ochronosis)'],
    note: 'Best used in guided cycles rather than continuously.'
  },
  'skin-brightening': {
    name: 'Kojic Acid Brightening', tagline: 'Tone-evening actives',
    what: 'Kojic acid and companion actives reduce melanin to brighten and even skin tone, often in multi-active compounded creams.',
    benefits: ['Brightens and evens tone', 'Fades discoloration', 'Gentler brightening option'],
    howUsed: 'Applied as directed; use daily SPF.',
    contra: ['Sensitivity to ingredients', 'Broken or irritated skin'],
    side: ['Mild irritation or redness', 'Sun sensitivity'],
  },
  azelaic: {
    name: 'Azelaic Acid', tagline: 'Acne, rosacea & tone',
    what: 'Azelaic acid calms redness, clears acne, and brightens tone — well tolerated, including in rosacea and melasma.',
    benefits: ['Reduces acne and clogged pores', 'Calms redness and rosacea', 'Evens skin tone'],
    howUsed: 'Applied to clean skin as directed.',
    contra: ['Sensitivity to ingredients'],
    side: ['Mild tingling or dryness initially', 'Temporary redness'],
  },
  niacinamide: {
    name: 'Niacinamide & Antioxidant Blends', tagline: 'Barrier, tone & glow',
    what: 'Multi-active cosmetic creams built around niacinamide, vitamin C, hyaluronic acid, and antioxidants to hydrate, brighten, and support the skin barrier.',
    benefits: ['Hydrates and strengthens the barrier', 'Brightens and evens tone', 'Antioxidant protection', 'Well tolerated'],
    howUsed: 'Applied daily as directed.',
    contra: ['Sensitivity to a specific ingredient'],
    side: ['Generally gentle', 'Occasional mild irritation'],
  },
  'topical-antibiotic': {
    name: 'Topical Acne Compounds', tagline: 'Clindamycin / anti-microbial blends',
    what: 'Compounded topicals combining anti-microbial and anti-inflammatory actives (e.g., clindamycin, erythromycin, ketoconazole) to clear acne.',
    benefits: ['Targets acne-causing bacteria', 'Reduces inflammation and breakouts', 'Customized combinations'],
    howUsed: 'Applied to affected areas as directed.',
    contra: ['Sensitivity to ingredients', 'Pregnancy without guidance'],
    side: ['Dryness or irritation', 'Redness or peeling'],
  },
  glutathione: {
    name: 'Glutathione', tagline: 'Master antioxidant & glow',
    what: 'Glutathione is the body\u2019s master antioxidant, used to support detoxification, skin brightness, and cellular health.',
    benefits: ['Antioxidant and detox support', 'Supports skin brightness and glow', 'Supports immune and cellular health'],
    howUsed: 'Intramuscular or IV injection, or capsule.',
    contra: ['Known hypersensitivity', 'Active asthma flare (IV, discuss with provider)'],
    side: ['Generally very well tolerated', 'Rare injection-site reaction'],
  },
  nad: {
    name: 'NAD+', tagline: 'Cellular energy & longevity',
    what: 'NAD+ is a coenzyme central to cellular energy production and repair that declines with age. It is used to support energy, focus, recovery, and healthy aging.',
    benefits: ['Supports cellular energy', 'May improve focus and clarity', 'Supports recovery and longevity pathways'],
    howUsed: 'IV infusion, subcutaneous injection, or sublingual — infusions are given slowly.',
    contra: ['Pregnancy or breastfeeding', 'Known hypersensitivity'],
    side: ['Flushing, chest tightness, or nausea if infused too fast', 'Injection-site reactions'],
    note: 'Infusions are given slowly to stay comfortable.'
  },
  b12: {
    name: 'Vitamin B12', tagline: 'Energy & nerve support',
    what: 'B12 (methylcobalamin or cyanocobalamin) supports energy, red blood cell production, and nerve health — especially helpful if you\u2019re low.',
    benefits: ['Supports energy and reduces fatigue', 'Supports nerve and blood-cell health', 'Great add-on to weight-loss programs'],
    howUsed: 'Intramuscular injection, often weekly to monthly.',
    contra: ['Known hypersensitivity (rare)'],
    side: ['Very well tolerated', 'Occasional injection-site soreness'],
  },
  'methylene-blue': {
    name: 'Methylene Blue', tagline: 'Mitochondrial & cognitive support',
    what: 'At low doses, methylene blue supports mitochondrial energy and is studied for cognition and antioxidant effects.',
    benefits: ['Supports cellular energy', 'Studied for focus and cognition', 'Antioxidant support'],
    howUsed: 'Oral capsule, low-dose.',
    contra: ['Use with SSRIs/SNRIs/MAOIs (serotonin-syndrome risk)', 'G6PD deficiency', 'Pregnancy or breastfeeding', 'Kidney impairment'],
    side: ['Blue-green urine (harmless)', 'Mild GI upset', 'Headache'],
    note: 'Important: not to be combined with many antidepressants.'
  },
  coq10: {
    name: 'CoQ10', tagline: 'Heart & mitochondrial antioxidant',
    what: 'Coenzyme Q10 supports mitochondrial energy production and acts as an antioxidant, with a focus on heart and muscle health.',
    benefits: ['Supports heart and muscle energy', 'Antioxidant protection', 'May ease statin-related muscle aches'],
    howUsed: 'Oral capsule, best with food.',
    contra: ['Known hypersensitivity'],
    side: ['Very well tolerated', 'Rare mild GI upset'],
  },
  vitamind: {
    name: 'Vitamin D3', tagline: 'Immune & bone support',
    what: 'Vitamin D3 (often paired with K2) supports immune function, bone health, mood, and hormone balance — commonly low in adults.',
    benefits: ['Supports immune health', 'Supports bone strength', 'Supports mood and hormones'],
    howUsed: 'Oral capsule, with food.',
    contra: ['High blood calcium', 'Certain kidney conditions'],
    side: ['Very well tolerated at appropriate doses', 'Excess can raise calcium'],
    note: 'Dose is best guided by a vitamin-D blood level.'
  },
  ketamine: {
    name: 'Ketamine (Oral)', tagline: 'Mood & mental-health support',
    what: 'Low-dose oral ketamine is used within supervised programs for treatment-resistant depression, anxiety, and mood support.',
    benefits: ['May rapidly improve mood in appropriate patients', 'Used for treatment-resistant depression', 'Supervised, structured protocols'],
    howUsed: 'Oral disintegrating troche within a monitored program.',
    contra: ['Uncontrolled high blood pressure', 'History of psychosis', 'Pregnancy or breastfeeding', 'Substance-use concerns'],
    side: ['Dissociation or dizziness', 'Nausea', 'Temporary blood-pressure changes'],
    note: 'Controlled medication — used only within a supervised program.'
  },
  spironolactone: {
    name: 'Spironolactone', tagline: 'Anti-androgen for skin & hair',
    what: 'Spironolactone blocks androgens, helping hormonal acne, unwanted hair, and female-pattern hair thinning.',
    benefits: ['Clears hormonal acne', 'Reduces unwanted facial hair', 'Supports female hair retention'],
    howUsed: 'Oral capsule.',
    contra: ['High potassium levels', 'Significant kidney impairment', 'Pregnancy'],
    side: ['Increased urination', 'Menstrual changes', 'Breast tenderness', 'Potassium elevation (monitored)'],
  },
  doxycycline: {
    name: 'Doxycycline', tagline: 'Antibiotic for acne & rosacea',
    what: 'Doxycycline is an antibiotic with anti-inflammatory effects used for acne and rosacea, often at low doses.',
    benefits: ['Reduces inflammatory acne', 'Calms rosacea', 'Low-dose options'],
    howUsed: 'Oral capsule, with a full glass of water (stay upright afterward).',
    contra: ['Pregnancy or breastfeeding', 'Children under 8', 'Known tetracycline allergy'],
    side: ['Sun sensitivity', 'Stomach upset', 'Yeast overgrowth'],
  },
  ezetimibe: {
    name: 'Ezetimibe', tagline: 'Cholesterol support',
    what: 'Ezetimibe lowers cholesterol by reducing how much your gut absorbs — used alone or with other cholesterol therapies.',
    benefits: ['Lowers LDL cholesterol', 'Non-statin option', 'Well tolerated'],
    howUsed: 'Oral tablet, once daily.',
    contra: ['Active liver disease (with a statin)', 'Pregnancy or breastfeeding without guidance'],
    side: ['Generally well tolerated', 'Occasional GI upset or muscle aches'],
  },
  supplies: {
    name: 'Supplies & Devices', tagline: 'Syringes, needles & dosing tools',
    what: 'The syringes, needles, dosing devices, and reconstitution supplies that go with your protocol — sized and packaged for at-home use.',
    benefits: ['Correct gauge and volume for your protocol', 'Clean, sealed, single-use', 'Includes alcohol pads and spikes in kits'],
    howUsed: 'Used as demonstrated by your provider for your specific medication.',
    contra: ['Not applicable'],
    side: ['Not applicable'],
    note: 'Dispose of sharps in an approved sharps container.'
  },
  // universal fallback
  generic: {
    name: 'Compounded Prescription', tagline: 'Provider-directed therapy',
    what: 'This is a compounded prescription product prepared by a licensed pharmacy and prescribed for your individual protocol.',
    benefits: ['Customized to your prescription', 'Prepared by a licensed compounding pharmacy'],
    howUsed: 'Use exactly as directed by your provider.',
    contra: ['Discuss your full history and medications with your provider'],
    side: ['Ask your provider about expected effects for this specific product'],
    note: 'Your provider will review benefits, risks, and instructions with you.'
  },
};
