/** Gallery case registry — single source for /gallery and InMode service land-embed results. */

export type BeforeAfterCase = {
  type: "before-after";
  id: string;
  treatment: string;
  category: string;
  tagline: string;
  before: string;
  after: string;
  duringVideo?: string;
  note: string;
  serviceHref: string;
};

export type VideoCase = {
  type: "video";
  id: string;
  treatment: string;
  category: string;
  tagline: string;
  video: string;
  note: string;
  serviceHref: string;
};

export type YoutubeCase = {
  type: "youtube";
  id: string;
  treatment: string;
  category: string;
  tagline: string;
  youtubeId: string;
  note: string;
  serviceHref: string;
};

export type SingleImageCase = {
  type: "single-image";
  id: string;
  treatment: string;
  category: string;
  tagline: string;
  image: string;
  imageAlt: string;
  note: string;
  serviceHref: string;
};

export type GalleryCase = BeforeAfterCase | VideoCase | YoutubeCase | SingleImageCase;

/* ─────────────────────────────────────────────────────────────
   CASES — add more here
───────────────────────────────────────────────────────────── */

export const GALLERY_CASES: GalleryCase[] = [
  {
    type: "single-image",
    id: "brow-pmu-portfolio-danielle-alcala",
    treatment: "Brow PMU — Microblading, Powder, Combo & Nano",
    category: "Brow PMU",
    tagline:
      "Four-technique permanent makeup brow portfolio — hair stroke, powder, hybrid combo & nano strokes.",
    image: "/images/brow/danielle-alcala-brow-pmu-portfolio-before-after.png",
    imageAlt:
      "Microblading, powder brows, combo brows and nano brows before and after by Danielle Alcala at Hello Gorgeous Med Spa Oswego IL",
    note: "Brow PMU portfolio at Hello Gorgeous Med Spa, Oswego, IL — Danielle Alcala. Microblading, powder, combo & nano brows. Client consent on file.",
    serviceHref: "/microblading-brow-pmu-oswego-il",
  },
  {
    type: "single-image",
    id: "combo-brows-blonde-before-after",
    treatment: "Combo Brows — Hybrid Hair Stroke + Powder",
    category: "Brow PMU",
    tagline: "Hair strokes at the front, soft powder density through arch and tail — ideal for very light natural brows.",
    image: "/images/brow/combo-brows-blonde-before-after-danielle-alcala.png",
    imageAlt:
      "Combo hybrid brows before and after by Danielle Alcala at Hello Gorgeous Med Spa Oswego IL",
    note: "Combo / hybrid brow PMU. Hello Gorgeous Med Spa, Oswego, IL. Danielle Alcala. Client consent on file.",
    serviceHref: "/blog/brow-mapping-shapes-techniques-nano-powder-combo-ombre-oswego-il",
  },
  {
    type: "single-image",
    id: "combo-ombre-brows-before-after",
    treatment: "Combo & Ombré Brows",
    category: "Brow PMU",
    tagline: "Mapped arch and tail with ombré shading plus stroke detail at the brow head.",
    image: "/images/brow/combo-ombre-brows-before-after-danielle-alcala.png",
    imageAlt:
      "Combo ombré brows before and after permanent makeup by Danielle Alcala Hello Gorgeous Med Spa Oswego IL",
    note: "Combo ombré brow permanent makeup. Oswego, IL. Client consent on file.",
    serviceHref: "/blog/brow-mapping-shapes-techniques-nano-powder-combo-ombre-oswego-il",
  },
  {
    type: "single-image",
    id: "natural-light-stroke-brows-before-after",
    treatment: "Natural Light Stroke Brows — Microblading",
    category: "Brow PMU",
    tagline: "Fine hair-stroke microblading for soft, feathery fullness and a natural arch.",
    image: "/images/brow/natural-light-stroke-brows-before-after-danielle-alcala.png",
    imageAlt:
      "Natural light stroke brows before and after microblading by Danielle Alcala at Hello Gorgeous Med Spa Oswego IL",
    note: "Natural light stroke / hair-stroke microblading at Hello Gorgeous Med Spa, Oswego, IL — Danielle Alcala. Client consent on file.",
    serviceHref: "/microblading-brow-pmu-oswego-il",
  },
  {
    type: "single-image",
    id: "natural-light-stroke-brows-vertical",
    treatment: "Natural Light Stroke Brows — Hand Stroke PMU",
    category: "Brow PMU",
    tagline: "Hand-stroke microblading before and after — soft hair strokes, natural arch.",
    image: "/images/brow/natural-light-stroke-brows-vertical-before-after-danielle-alcala.png",
    imageAlt:
      "Natural light stroke brows vertical before and after microblading by Danielle Alcala Hello Gorgeous Med Spa Oswego IL",
    note: "Natural light stroke hand-stroke brows. Danielle Alcala, Hello Gorgeous Med Spa Oswego. Client consent on file.",
    serviceHref: "/microblading-brow-pmu-oswego-il",
  },
  {
    type: "single-image",
    id: "powder-nano-brows-before-after",
    treatment: "Powder & Nano Brows — Ombré PMU",
    category: "Brow PMU",
    tagline: "Soft ombré powder/nano shading for light or sparse natural brows.",
    image: "/images/brow/powder-nano-brows-before-after-danielle-alcala.png",
    imageAlt:
      "Powder and nano brow PMU before and after by Danielle Alcala at Hello Gorgeous Med Spa Oswego IL",
    note: "Powder and nano brow permanent makeup. Hello Gorgeous Med Spa, Oswego, IL. Client consent on file.",
    serviceHref: "/microblading-brow-pmu-oswego-il",
  },
  {
    type: "single-image",
    id: "powder-brows-before-after",
    treatment: "Powder Brows — Ombré PMU",
    category: "Brow PMU",
    tagline: "Soft ombré powder shading — fuller brows, defined arch, natural finish.",
    image: "/images/brow/powder-brows-before-after.png",
    imageAlt:
      "Powder brows before and after permanent makeup comparison — Hello Gorgeous Med Spa Oswego IL",
    note: "Ombré powder brow PMU at Hello Gorgeous Med Spa, Oswego, IL. Client consent on file. Individual results vary.",
    serviceHref: "/microblading-brow-pmu-oswego-il",
  },
  // ── InMode Gift Night — Quantum RF, Solaria CO₂ & Morpheus8 winners (May 2026) ──
  {
    type: "video",
    id: "gift-night-highlights",
    treatment: "InMode Gift Night — Event Highlights",
    category: "Gift Night Winners",
    tagline: "Quantum RF, Solaria CO₂ & Morpheus8 — winners, demos & celebration in one night.",
    video: "/videos/gallery/event-winners/inmode-gift-night-highlights.mp4",
    note: "InMode gift night at Hello Gorgeous Med Spa featuring Quantum RF, Solaria CO₂ laser, and Morpheus8 Burst giveaways. Oswego, IL.",
    serviceHref: "/specials",
  },
  {
    type: "single-image",
    id: "gift-night-solaria-winner",
    treatment: "Solaria CO₂ — Gift Certificate Winner",
    category: "Gift Night Winners",
    tagline: "Congratulations to our Solaria fractional CO₂ laser gift night winner.",
    image: "/gallery/event-winners/solaria-co2-winner.png",
    imageAlt: "Solaria CO₂ laser gift certificate winner at Hello Gorgeous Med Spa Oswego IL",
    note: "Solaria CO₂ fractional laser resurfacing giveaway winner. Hello Gorgeous Med Spa, Oswego, IL. Published with client consent.",
    serviceHref: "/solaria-co2-oswego",
  },
  {
    type: "single-image",
    id: "gift-night-morpheus8-winner",
    treatment: "Morpheus8 — Gift Certificate Winner",
    category: "Gift Night Winners",
    tagline: "Morpheus8 Burst RF microneedling — gift night winner celebration.",
    image: "/gallery/event-winners/morpheus8-winner.png",
    imageAlt: "Morpheus8 gift certificate winner at Hello Gorgeous Med Spa Oswego IL",
    note: "Morpheus8 Burst RF microneedling giveaway winner. Hello Gorgeous Med Spa, Oswego, IL. Published with client consent.",
    serviceHref: "/morpheus8-burst-oswego",
  },
  {
    type: "single-image",
    id: "gift-night-quantum-rf-winner",
    treatment: "Quantum RF — Gift Certificate Winner",
    category: "Gift Night Winners",
    tagline: "Quantum RF subdermal contouring — gift night winner with Hello Gorgeous team.",
    image: "/gallery/event-winners/quantum-rf-winner.png",
    imageAlt: "Quantum RF gift certificate winner at Hello Gorgeous Med Spa Oswego IL",
    note: "Quantum RF subdermal contouring giveaway winner. Hello Gorgeous Med Spa, Oswego, IL. Published with client consent.",
    serviceHref: "/quantum-rf-oswego",
  },
  {
    type: "single-image",
    id: "gift-night-ryan-demo-1",
    treatment: "Live Treatment Demo — Ryan Kent, FNP-BC",
    category: "Gift Night Winners",
    tagline: "On-site medical director performing a live aesthetic treatment at gift night.",
    image: "/gallery/event-winners/ryan-live-demo-1.png",
    imageAlt: "Ryan Kent FNP performing live treatment demo Hello Gorgeous Med Spa",
    note: "Live demo with Ryan Kent, FNP-BC, Medical Director. Hello Gorgeous Med Spa community event, Oswego, IL.",
    serviceHref: "/about",
  },
  {
    type: "single-image",
    id: "gift-night-ryan-demo-2",
    treatment: "Live Treatment Demo — Clinical Technique",
    category: "Gift Night Winners",
    tagline: "Precision injectable technique — real event, real provider, real community.",
    image: "/gallery/event-winners/ryan-live-demo-2.png",
    imageAlt: "Live injectable treatment demonstration Hello Gorgeous Med Spa Oswego",
    note: "Gift night live demonstration. Medical oversight by Ryan Kent, FNP-BC. Individual results vary.",
    serviceHref: "/about",
  },
  {
    type: "single-image",
    id: "gift-night-ryan-demo-3",
    treatment: "Live Treatment Demo — Client Experience",
    category: "Gift Night Winners",
    tagline: "Comfortable, personal care at our InMode technology launch event.",
    image: "/gallery/event-winners/ryan-live-demo-3.png",
    imageAlt: "Client receiving live treatment at Hello Gorgeous Med Spa gift night",
    note: "Community event footage. Hello Gorgeous Med Spa, Oswego, IL. Published with client consent.",
    serviceHref: "/about",
  },
  {
    type: "single-image",
    id: "gift-night-skin-result",
    treatment: "Skin Tightening — Real Result",
    category: "Gift Night Winners",
    tagline: "Visible jawline definition and skin quality improvement — real client comparison.",
    image: "/gallery/event-winners/skin-tightening-before-after.png",
    imageAlt: "Skin tightening before and after Hello Gorgeous Med Spa Oswego IL",
    note: "Client result shared at community event. Individual results vary. Consult required for candidacy.",
    serviceHref: "/morpheus8-burst-oswego",
  },
  {
    type: "single-image",
    id: "gift-night-community",
    treatment: "Hello Gorgeous Community Night",
    category: "Gift Night Winners",
    tagline: "Celebrating our Fox Valley clients — team, winners & InMode technology under one roof.",
    image: "/gallery/event-winners/community-celebration.png",
    imageAlt: "Hello Gorgeous Med Spa community celebration with clients Oswego IL",
    note: "Community gift night at Hello Gorgeous Med Spa, Oswego, IL.",
    serviceHref: "/about",
  },
  {
    type: "single-image",
    id: "gift-night-outdoor-team",
    treatment: "Gift Night — Team & Clients",
    category: "Gift Night Winners",
    tagline: "Dani, Ryan & our community — celebrating InMode technology together outdoors.",
    image: "/gallery/event-winners/outdoor-event-team.png",
    imageAlt: "Hello Gorgeous Med Spa team and clients at outdoor gift night event Oswego IL",
    note: "Outdoor community event with Danielle Alcala-Glazier and Ryan Kent, FNP-BC. Hello Gorgeous Med Spa, Oswego, IL.",
    serviceHref: "/about",
  },
  // ── Quantum RF client results (Hello Gorgeous, Oswego) ──
  {
    type: "single-image",
    id: "quantum-rf-jen-knees-ba",
    treatment: "Quantum RF — Thighs & Knees",
    category: "RF Treatments",
    tagline: "Before & after — smoother thighs, tighter skin above the knees.",
    image: "/gallery/quantum-rf-client-results/jen-knees-before-after.png",
    imageAlt: "Quantum RF before and after thighs and knees skin tightening Hello Gorgeous Med Spa Oswego IL",
    note: "Quantum RF subdermal contouring at Hello Gorgeous Med Spa, Oswego, IL. Published with client consent. Individual results vary.",
    serviceHref: "/quantum-rf-oswego",
  },
  {
    type: "single-image",
    id: "quantum10-upper-arms-ba",
    treatment: "Quantum 10 — Upper Arm Skin Tightening",
    category: "RF Treatments",
    tagline: "Left and right upper arms — visible reduction in laxity and smoother contour.",
    image: "/gallery/quantum10-morpheus8-burst-upper-arms/before-after.png",
    imageAlt:
      "Quantum 10 before and after upper arm skin tightening left arm and right arm — Hello Gorgeous Med Spa Oswego IL",
    note: "Real client before and after upper arm skin laxity. Quantum 10 subdermal RF contouring at Hello Gorgeous Med Spa, Oswego, IL. Published with client consent. Individual results vary.",
    serviceHref: "/quantum-rf-oswego",
  },
  {
    type: "single-image",
    id: "morpheus8-burst-upper-arms-ba",
    treatment: "Morpheus8 Burst — Upper Arm Skin Tightening",
    category: "RF Microneedling",
    tagline: "Bilateral upper arm laxity tightened — before and after on left and right arms.",
    image: "/gallery/quantum10-morpheus8-burst-upper-arms/before-after.png",
    imageAlt:
      "Morpheus8 Burst before and after upper arm skin tightening left arm and right arm — Hello Gorgeous Med Spa Oswego IL",
    note: "Real client before and after upper arm skin laxity. Morpheus8 Burst RF microneedling — body. Hello Gorgeous Med Spa, Oswego, IL. Published with client consent. Individual results vary.",
    serviceHref: "/morpheus8-burst-oswego",
  },
  // ── Quantum RF clinical results ──────────────────────
  {
    type: "single-image",
    id: "qrf-pdf-1",
    treatment: "Quantum RF — Face & Neck Contouring",
    category: "RF Treatments",
    tagline: "Face and neck tightening without surgery — Quantum RF clinical result.",
    image: "/gallery/qrf-pdf-1/before-after.jpg",
    imageAlt: "Quantum RF face and neck before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Quantum RF subdermal contouring. Clinical result. Available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/quantum-rf-oswego",
  },
  {
    type: "single-image",
    id: "qrf-pdf-2",
    treatment: "Quantum RF — Jawline Definition",
    category: "RF Treatments",
    tagline: "Defined jawline and reduced jowls — Quantum RF without surgery.",
    image: "/gallery/qrf-pdf-2/before-after.jpg",
    imageAlt: "Quantum RF jawline definition before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Quantum RF subdermal contouring. Clinical result. Available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/quantum-rf-oswego",
  },
  {
    type: "single-image",
    id: "qrf-pdf-3",
    treatment: "Quantum RF — Skin Tightening",
    category: "RF Treatments",
    tagline: "Loose skin and laxity tightened — Quantum RF subdermal technology.",
    image: "/gallery/qrf-pdf-3/before-after.jpg",
    imageAlt: "Quantum RF skin tightening before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Quantum RF subdermal contouring. Clinical result. Available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/quantum-rf-oswego",
  },
  {
    type: "single-image",
    id: "qrf-pdf-4",
    treatment: "Quantum RF — Submental Contouring",
    category: "RF Treatments",
    tagline: "Double chin and neck laxity corrected — Quantum RF real result.",
    image: "/gallery/qrf-pdf-4/before-after.jpg",
    imageAlt: "Quantum RF submental contouring before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Quantum RF subdermal contouring. Clinical result. Available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/quantum-rf-oswego",
  },
  // ── Solaria PB clinical results ──────────────────────
  {
    type: "single-image",
    id: "solaria-pb-1",
    treatment: "Solaria CO₂ Laser — Skin Renewal",
    category: "Laser Resurfacing",
    tagline: "Full skin renewal — texture, tone and clarity transformed with Solaria CO₂.",
    image: "/gallery/solaria-pb-1/before-after.jpg",
    imageAlt: "Solaria CO₂ laser skin renewal before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Solaria fractional CO₂ laser. Clinical result. Available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/solaria-co2-oswego",
  },
  {
    type: "single-image",
    id: "solaria-pb-2",
    treatment: "Solaria CO₂ — Pores & Texture",
    category: "Laser Resurfacing",
    tagline: "Enlarged pores and rough texture refined — Solaria CO₂ fractional laser.",
    image: "/gallery/solaria-pb-2/before-after.jpg",
    imageAlt: "Solaria CO₂ pores and texture before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Solaria fractional CO₂ laser. Clinical result. Available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/solaria-co2-oswego",
  },
  {
    type: "single-image",
    id: "solaria-pb-3",
    treatment: "Solaria CO₂ — Melasma & Dark Spots",
    category: "Laser Resurfacing",
    tagline: "Melasma and dark spots visibly faded — Solaria fractional CO₂ resurfacing.",
    image: "/gallery/solaria-pb-3/before-after.jpg",
    imageAlt: "Solaria CO₂ melasma and dark spots before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Solaria fractional CO₂ laser. Clinical result. Available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/solaria-co2-oswego",
  },
  {
    type: "single-image",
    id: "solaria-pb-4",
    treatment: "Solaria CO₂ — Wrinkles & Collagen",
    category: "Laser Resurfacing",
    tagline: "Wrinkles reduced and collagen rebuilt — Solaria CO₂ laser resurfacing.",
    image: "/gallery/solaria-pb-4/before-after.jpg",
    imageAlt: "Solaria CO₂ wrinkles and collagen before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Solaria fractional CO₂ laser. Clinical result. Available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/solaria-co2-oswego",
  },
  {
    type: "single-image",
    id: "solaria-pb-5",
    treatment: "Solaria CO₂ — Acne Scars",
    category: "Laser Resurfacing",
    tagline: "Acne scars smoothed with Solaria fractional CO₂ laser resurfacing.",
    image: "/gallery/solaria-pb-5/before-after.jpg",
    imageAlt: "Solaria CO₂ acne scars before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Solaria fractional CO₂ laser. Clinical result. Available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/solaria-co2-oswego",
  },
  {
    type: "single-image",
    id: "luxora-pdf-1",
    treatment: "Luxora by InMode — Skin Tightening",
    category: "Advanced Technology",
    tagline: "Non-invasive skin tightening and body contouring — Luxora real results.",
    image: "/gallery/luxora-pdf-1/before-after.jpg",
    imageAlt: "Luxora InMode skin tightening before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Luxora by InMode. Clinical result. Available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/specials",
  },
  {
    type: "single-image",
    id: "luxora-pdf-2",
    treatment: "Luxora — Body Contouring",
    category: "Advanced Technology",
    tagline: "Visible body contouring and fat reduction — Luxora by InMode.",
    image: "/gallery/luxora-pdf-2/before-after.jpg",
    imageAlt: "Luxora InMode body contouring before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Luxora by InMode. Clinical result. Available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/specials",
  },
  {
    type: "single-image",
    id: "luxora-pdf-3",
    treatment: "Luxora — Skin Laxity",
    category: "Advanced Technology",
    tagline: "Loose skin tightened without surgery — Luxora InMode technology.",
    image: "/gallery/luxora-pdf-3/before-after.jpg",
    imageAlt: "Luxora InMode skin laxity before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Luxora by InMode. Clinical result. Available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/specials",
  },
  {
    type: "single-image",
    id: "luxora-pdf-4",
    treatment: "Luxora — Circumference Reduction",
    category: "Advanced Technology",
    tagline: "Circumference reduction and contouring — Luxora by InMode.",
    image: "/gallery/luxora-pdf-4/before-after.jpg",
    imageAlt: "Luxora InMode circumference reduction before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Luxora by InMode. Clinical result. Available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/specials",
  },
  {
    type: "single-image",
    id: "luxora-pdf-5",
    treatment: "Luxora — Fat Reduction",
    category: "Advanced Technology",
    tagline: "Non-surgical fat reduction and skin improvement — Luxora InMode.",
    image: "/gallery/luxora-pdf-5/before-after.jpg",
    imageAlt: "Luxora InMode fat reduction before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Luxora by InMode. Clinical result. Available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/specials",
  },
  {
    type: "single-image",
    id: "luxora-pdf-6",
    treatment: "Luxora — Cellulite & Texture",
    category: "Advanced Technology",
    tagline: "Cellulite and skin texture improved — Luxora by InMode.",
    image: "/gallery/luxora-pdf-6/before-after.jpg",
    imageAlt: "Luxora InMode cellulite and texture before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Luxora by InMode. Clinical result. Available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/specials",
  },
  {
    type: "single-image",
    id: "luxora-pdf-7",
    treatment: "Luxora — Tone & Tightening",
    category: "Advanced Technology",
    tagline: "Skin tone and tightness visibly improved — Luxora InMode technology.",
    image: "/gallery/luxora-pdf-7/before-after.jpg",
    imageAlt: "Luxora InMode tone and tightening before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Luxora by InMode. Clinical result. Available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/specials",
  },
  {
    type: "single-image",
    id: "luxora-pdf-8",
    treatment: "Luxora — Full Body Result",
    category: "Advanced Technology",
    tagline: "Full body contouring and tightening — real Luxora by InMode result.",
    image: "/gallery/luxora-pdf-8/before-after.jpg",
    imageAlt: "Luxora InMode full body result before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Luxora by InMode. Clinical result. Available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/specials",
  },
  {
    type: "single-image",
    id: "solaria-pdf-1",
    treatment: "Solaria CO₂ Laser — Skin Resurfacing",
    category: "Laser Resurfacing",
    tagline: "Fractional CO₂ resurfacing — texture, tone and fine lines visibly improved.",
    image: "/gallery/solaria-pdf-1/before-after.jpg",
    imageAlt: "Solaria CO₂ laser before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Solaria fractional CO₂ laser resurfacing. Clinical result. Available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/solaria-co2-oswego",
  },
  {
    type: "single-image",
    id: "solaria-pdf-2",
    treatment: "Solaria CO₂ Laser — Fine Lines & Texture",
    category: "Laser Resurfacing",
    tagline: "Fine lines, texture and skin quality dramatically improved with Solaria CO₂.",
    image: "/gallery/solaria-pdf-2/before-after.jpg",
    imageAlt: "Solaria CO₂ laser fine lines and texture before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Solaria fractional CO₂ laser resurfacing. Clinical result. Available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/solaria-co2-oswego",
  },
  {
    type: "single-image",
    id: "solaria-pdf-3",
    treatment: "Solaria CO₂ Laser — Tone & Radiance",
    category: "Laser Resurfacing",
    tagline: "Dull, uneven skin transformed — brighter tone and smoother texture.",
    image: "/gallery/solaria-pdf-3/before-after.jpg",
    imageAlt: "Solaria CO₂ laser skin tone and radiance before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Solaria fractional CO₂ laser resurfacing. Clinical result. Available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/solaria-co2-oswego",
  },
  {
    type: "single-image",
    id: "solaria-pdf-4",
    treatment: "Solaria CO₂ Laser — Wrinkles & Laxity",
    category: "Laser Resurfacing",
    tagline: "Loose skin and deep wrinkles tightened — Solaria fractional CO₂ resurfacing.",
    image: "/gallery/solaria-pdf-4/before-after.jpg",
    imageAlt: "Solaria CO₂ laser wrinkles and skin laxity before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Solaria fractional CO₂ laser resurfacing. Clinical result. Available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/solaria-co2-oswego",
  },
  {
    type: "single-image",
    id: "solaria-pdf-5",
    treatment: "Solaria CO₂ Laser — Sun Damage & Aging",
    category: "Laser Resurfacing",
    tagline: "Sun damage, age spots and skin aging reversed with one Solaria CO₂ treatment.",
    image: "/gallery/solaria-pdf-5/before-after.jpg",
    imageAlt: "Solaria CO₂ laser sun damage and aging before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Solaria fractional CO₂ laser resurfacing. Clinical result. Available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/solaria-co2-oswego",
  },
  {
    type: "single-image",
    id: "morpheus8-thigh-1",
    treatment: "Morpheus8 Burst — Thigh & Cellulite",
    category: "RF Microneedling",
    tagline: "Cellulite and skin laxity on the thighs — visibly smoother after Morpheus8 Burst.",
    image: "/gallery/morpheus8-thigh-1/before-after.jpg",
    imageAlt: "Morpheus8 Burst thigh cellulite before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Morpheus8 Burst RF microneedling — body. Clinical result. Now available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/morpheus8-burst-oswego",
  },
  {
    type: "single-image",
    id: "morpheus8-thigh-2",
    treatment: "Morpheus8 Burst — Body Contouring",
    category: "RF Microneedling",
    tagline: "Tighter, smoother skin on the outer thigh — Morpheus8 Burst body results.",
    image: "/gallery/morpheus8-thigh-2/before-after.jpg",
    imageAlt: "Morpheus8 Burst body contouring thigh before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Morpheus8 Burst RF microneedling — body. Clinical result. Now available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/morpheus8-burst-oswego",
  },
  {
    type: "single-image",
    id: "morpheus8-face-hyperpig",
    treatment: "Morpheus8 — Hyperpigmentation & Tone",
    category: "RF Microneedling",
    tagline: "Sun spots, uneven tone and texture corrected — Morpheus8 RF microneedling.",
    image: "/gallery/morpheus8-face-hyperpig/before-after.jpg",
    imageAlt: "Morpheus8 face hyperpigmentation before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Morpheus8 RF microneedling — face. Clinical result. Now available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/morpheus8-burst-oswego",
  },
  {
    type: "single-image",
    id: "morpheus8-face-wrinkles",
    treatment: "Morpheus8 — Fine Lines & Wrinkles",
    category: "RF Microneedling",
    tagline: "Deep wrinkles and skin laxity visibly reduced — Morpheus8 RF microneedling.",
    image: "/gallery/morpheus8-face-wrinkles/before-after.jpg",
    imageAlt: "Morpheus8 face wrinkles fine lines before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Morpheus8 RF microneedling — face. Clinical result. Now available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/morpheus8-burst-oswego",
  },
  {
    type: "single-image",
    id: "morpheus8-acne-scars-1",
    treatment: "Morpheus8 — Acne Scars",
    category: "RF Microneedling",
    tagline: "Active acne and post-acne scarring treated with Morpheus8 RF microneedling.",
    image: "/gallery/morpheus8-acne-scars-1/before-after.jpg",
    imageAlt: "Morpheus8 acne scars before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Morpheus8 RF microneedling — acne scars. Clinical result. Now available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/morpheus8-burst-oswego",
  },
  {
    type: "single-image",
    id: "morpheus8-acne-scars-2",
    treatment: "Morpheus8 — Acne Scars & Redness",
    category: "RF Microneedling",
    tagline: "Redness, scarring and texture dramatically improved — Morpheus8 at Hello Gorgeous.",
    image: "/gallery/morpheus8-acne-scars-2/before-after.jpg",
    imageAlt: "Morpheus8 acne scars and redness before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Morpheus8 RF microneedling — acne scars. Clinical result. Now available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/morpheus8-burst-oswego",
  },
  {
    type: "single-image",
    id: "morpheus8-burst-face",
    treatment: "Morpheus8 Burst — Fine Lines & Laxity",
    category: "RF Microneedling",
    tagline: "Morpheus8 Burst + Lumecca — deep wrinkles and skin laxity visibly lifted.",
    image: "/gallery/morpheus8-burst-face/before-after.jpg",
    imageAlt: "Morpheus8 Burst fine lines and skin laxity before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Morpheus8 Burst RF microneedling — face. Clinical result. Now available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/morpheus8-burst-oswego",
  },
  {
    type: "single-image",
    id: "morpheus8-acne-scars-3",
    treatment: "Morpheus8 — Surgical Scar & Acne Scars",
    category: "RF Microneedling",
    tagline: "Surgical scarring and acne scars faded — Morpheus8 RF microneedling.",
    image: "/gallery/morpheus8-acne-scars-3/before-after.jpg",
    imageAlt: "Morpheus8 surgical scar and acne scars before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Morpheus8 RF microneedling — scars. Clinical result. Now available at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/morpheus8-burst-oswego",
  },
  {
    type: "single-image",
    id: "solaria-client-7",
    treatment: "Solaria CO₂ Laser — Before, During & After",
    category: "Laser Resurfacing",
    tagline: "Acne scars, texture & dullness — completely transformed in one session.",
    image: "/gallery/solaria-client-7/before-during-after.jpg",
    imageAlt: "Solaria CO₂ laser before, during healing, and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Solaria fractional CO₂ laser. Left: before. Center: immediately post. Right: healed result. Hello Gorgeous Med Spa, Oswego, IL.",
    serviceHref: "/solaria-co2-oswego",
  },
  {
    type: "single-image",
    id: "lip-filler-jen-2",
    treatment: "Lip Filler — Before, During & After",
    category: "Injectables",
    tagline: "Fuller lips, defined shape — natural enhancement from one syringe.",
    image: "/gallery/lip-filler-jen-2/before-during-after.jpg",
    imageAlt: "Lip filler before, during injection, and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Dermal filler for natural lip enhancement. Left: before. Center: live injection. Right: after. Hello Gorgeous Med Spa, Oswego, IL.",
    serviceHref: "/services/lip-filler",
  },
  {
    type: "single-image",
    id: "solaria-client-5",
    treatment: "Solaria CO₂ Laser — Before, During & After",
    category: "Laser Resurfacing",
    tagline: "Real skin transformation — redness, texture & tone corrected in one session.",
    image: "/gallery/solaria-client-5/before-during-after.jpg",
    imageAlt: "Solaria CO₂ laser before, during, and healed after — Hello Gorgeous Med Spa Oswego IL",
    note: "Solaria fractional CO₂ laser. Left: before. Center: immediately post. Right: healed result. Hello Gorgeous Med Spa, Oswego, IL.",
    serviceHref: "/solaria-co2-oswego",
  },
  {
    type: "single-image",
    id: "solaria-client-6",
    treatment: "Solaria CO₂ Laser — Before, During & After",
    category: "Laser Resurfacing",
    tagline: "Dramatic renewal — fine lines, laxity & sun damage treated in a single CO₂ session.",
    image: "/gallery/solaria-client-6/before-during-after.jpg",
    imageAlt: "Solaria CO₂ laser before, 4 days post, and healed after — Hello Gorgeous Med Spa Oswego IL",
    note: "Solaria fractional CO₂ laser. Left: before. Center: 4 days post. Right: healed result. Hello Gorgeous Med Spa, Oswego, IL.",
    serviceHref: "/solaria-co2-oswego",
  },
  {
    type: "single-image",
    id: "lip-filler-jen",
    treatment: "Lip Filler — Before, During & After",
    category: "Injectables",
    tagline: "Natural volume — defined cupid's bow, soft overall shape. Real client result.",
    image: "/gallery/lip-filler-jen/before-during-after.jpg",
    imageAlt: "Lip filler before, during procedure, and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Dermal filler placed for natural lip enhancement. Left: before. Center: live injection. Right: after. Performed at Hello Gorgeous Med Spa, Oswego, IL.",
    serviceHref: "/services/lip-filler",
  },
  {
    type: "before-after",
    id: "solaria-client-4",
    treatment: "Solaria CO₂ Laser",
    category: "Laser Resurfacing",
    tagline: "Hyperpigmentation, texture, and redness — corrected. Real client, real result.",
    before: "/gallery/solaria-client-4/before.jpg",
    after: "/gallery/solaria-client-4/after.jpg",
    note: "Solaria fractional CO₂ laser resurfacing. Performed at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/solaria-co2-oswego",
  },
  {
    type: "before-after",
    id: "solaria-client-2",
    treatment: "Solaria CO₂ Laser",
    category: "Laser Resurfacing",
    tagline: "Smoother texture, lifted tone, and a natural glow — real client result.",
    before: "/gallery/client-2/before.jpg",
    after: "/gallery/client-2/after.jpg",
    note: "Solaria fractional CO₂ laser resurfacing. Performed at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/solaria-co2-oswego",
  },
  {
    type: "single-image",
    id: "solaria-client-3",
    treatment: "Solaria CO₂ Laser — Full Face Result",
    category: "Laser Resurfacing",
    tagline: "Dramatic skin renewal — one treatment, full face transformation.",
    image: "/gallery/solaria-client-2/result.jpg",
    imageAlt: "Solaria CO₂ laser full face before and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Solaria fractional CO₂ laser resurfacing. One treatment result. Hello Gorgeous Med Spa, Oswego, IL.",
    serviceHref: "/solaria-co2-oswego",
  },
  {
    type: "single-image",
    id: "solaria-client-1",
    treatment: "Solaria CO₂ Laser — Before, During & After",
    category: "Laser Resurfacing",
    tagline: "Real client transformation — skin texture, tone, and fine lines treated in one session.",
    image: "/gallery/solaria-client-1/before-during-after.jpg",
    imageAlt: "Solaria CO₂ laser before, during, and after — Hello Gorgeous Med Spa Oswego IL",
    note: "Solaria fractional CO₂ laser resurfacing. Left: before. Center: immediately after. Right: healed result. Hello Gorgeous Med Spa, Oswego, IL.",
    serviceHref: "/solaria-co2-oswego",
  },
  {
    type: "before-after",
    id: "quantum-rf-chin-1",
    treatment: "Quantum RF — Chin & Neck Contouring",
    category: "RF Treatments",
    tagline: "Defined jawline in just 1 week — no surgery, no downtime. Real client result.",
    before: "/gallery/quantum-rf-chin-1/before.jpg",
    after: "/gallery/quantum-rf-chin-1/after.jpg",
    note: "Quantum RF subdermal contouring — chin & neck. Result shown at 1 week post-treatment. Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/quantum-rf-oswego",
  },
  {
    type: "before-after",
    id: "quantum-rf-body-1",
    treatment: "Quantum RF — Body Contouring",
    category: "RF Treatments",
    tagline: "Loose skin tightened without surgery — real client before & after.",
    before: "/gallery/quantum-rf-body-1/before.jpg",
    after: "/gallery/quantum-rf-body-1/after.jpg",
    note: "Quantum RF subdermal body contouring. Performed at Hello Gorgeous Med Spa, Oswego, IL. Individual results vary.",
    serviceHref: "/quantum-rf-oswego",
  },
  {
    type: "video",
    id: "quantum-rf-stomach",
    treatment: "Quantum RF — Body Contouring",
    category: "RF Treatments",
    tagline: "Quantum RF subdermal contouring on the abdomen.",
    video: "/videos/gallery/quantum-rf-stomach.mp4",
    note: "Live Quantum RF body treatment. Performed at Hello Gorgeous Med Spa, Oswego, IL.",
    serviceHref: "/quantum-rf-oswego",
  },
  {
    type: "video",
    id: "morpheus8-burst-procedure",
    treatment: "Morpheus8 Burst",
    category: "RF Microneedling",
    tagline: "Deepest RF microneedling — live Morpheus8 Burst procedure.",
    video: "/videos/gallery/morpheus8-burst-procedure.mp4",
    note: "Morpheus8 Burst RF microneedling procedure footage. Hello Gorgeous Med Spa, Oswego, IL.",
    serviceHref: "/morpheus8-burst-oswego",
  },
  {
    type: "video",
    id: "luxora-inmode-event",
    treatment: "Luxora by InMode — Event Launch",
    category: "Advanced Technology",
    tagline: "Introducing Luxora — InMode's latest body contouring platform at Hello Gorgeous.",
    video: "/videos/gallery/luxora-inmode-event.mp4",
    note: "Luxora InMode event launch footage. Hello Gorgeous Med Spa, Oswego, IL.",
    serviceHref: "/specials",
  },
  {
    type: "video",
    id: "solaria-procedure-2",
    treatment: "Solaria CO₂ Laser — Procedure Clip",
    category: "Laser Resurfacing",
    tagline: "Live Solaria CO₂ fractional laser treatment in clinic.",
    video: "/videos/gallery/solaria-procedure-2.mp4",
    note: "Solaria CO₂ laser procedure footage. Performed at Hello Gorgeous Med Spa, Oswego, IL.",
    serviceHref: "/solaria-co2-oswego",
  },
  {
    type: "video",
    id: "solaria-procedure",
    treatment: "Solaria CO₂ Laser",
    category: "Laser Resurfacing",
    tagline: "Gold-standard fractional CO₂ resurfacing — live in clinic.",
    video: "/videos/gallery/solaria-procedure.mp4",
    note: "Solaria fractional CO₂ laser procedure at Hello Gorgeous Med Spa. Treats wrinkles, texture, tone & acne scars.",
    serviceHref: "/solaria-co2-oswego",
  },
  {
    type: "video",
    id: "quantum-rf-clip-2",
    treatment: "Quantum RF — Live Technique",
    category: "RF Treatments",
    tagline: "Subdermal RF contouring by Ryan Kent, FNP-BC.",
    video: "/videos/quantum-rf/ryan-quantum-rf-action-2.mp4",
    note: "Real Quantum RF treatment footage showing controlled subdermal pass. Hello Gorgeous Med Spa, Oswego, IL.",
    serviceHref: "/quantum-rf-oswego",
  },
  {
    type: "video",
    id: "quantum-rf-clip-3",
    treatment: "Quantum RF — Procedure Continuation",
    category: "RF Treatments",
    tagline: "Real-time provider handling during Quantum RF session.",
    video: "/videos/quantum-rf/ryan-quantum-rf-action-3.mp4",
    note: "Procedure continuation clip with Ryan Kent, FNP-BC. Individual candidacy and results vary.",
    serviceHref: "/quantum-rf-oswego",
  },
  {
    type: "youtube",
    id: "morpheus8-burst-youtube",
    treatment: "Morpheus8 Burst — Full Procedure",
    category: "RF Microneedling",
    tagline: "Watch a full Morpheus8 Burst RF microneedling session from start to finish.",
    youtubeId: "SPJPb-sBWKk",
    note: "Morpheus8 Burst RF microneedling — deepest treatment at 8mm. Hello Gorgeous Med Spa, Oswego, IL.",
    serviceHref: "/morpheus8-burst-oswego",
  },
];
