/**
 * Location page content - 1,000–1,200 words per page.
 * Structured sections, local semantic reinforcement, contextual internal links.
 * Build FAILS if any required page < 850 words.
 */

export type LocationContentSection = {
  intro: string;
  aboutTreatment: string;
  candidacy: string;
  whatToExpect: string;
  safetyAndTraining: string;
  communityContext: string;
  callToAction: string;
};

export const LOCATION_PAGE_CONTENT: Record<string, LocationContentSection> = {
  "botox-oswego-il": {
    intro:
      "Hello Gorgeous Med Spa offers Botox, Dysport, and Jeuveau in Oswego, IL for clients seeking natural-looking wrinkle reduction. We are located at 74 W. Washington Street in downtown Oswego, steps from the Fox River and the heart of the Oswego village center. Serving Oswego, Naperville, Plainfield, Aurora, Yorkville, Montgomery, and throughout Kendall County, we bring medical aesthetics expertise to the Fox Valley. Our licensed injectors customize every treatment for your facial anatomy and goals. Whether you are addressing frown lines, crow's feet, or forehead wrinkles, we take a conservative approach so you look refreshed—not frozen. Kendall County residents and visitors from across the Fox Valley trust Hello Gorgeous for consistent results, transparent pricing, and a consult-first experience. We are proud to be part of the Oswego community and welcome clients who value quality care and natural-looking results.",
    aboutTreatment:
      "Botox and other neuromodulators temporarily relax the muscles that create dynamic wrinkles—the lines that form when you frown, squint, or raise your eyebrows. At Hello Gorgeous in Oswego, we use Botox, Dysport, and Jeuveau to smooth these lines while preserving your natural expression. Our injectors are trained in facial anatomy and artistry; they understand how subtle adjustments can make a meaningful difference. We serve clients from Oswego, Naperville, Plainfield, and Aurora who want a med spa that prioritizes natural-looking outcomes over dramatic transformation. Many of our clients combine Botox with dermal fillers for a comprehensive refresh. We also offer Weight Loss in Oswego and Hormone Therapy in Oswego for clients interested in full-body wellness. Every Botox treatment at Hello Gorgeous begins with a consultation: we discuss your goals, assess your facial movement, and create a plan tailored to your unique features and budget.",
    candidacy:
      "Botox is suitable for most adults who want to reduce the appearance of dynamic wrinkles. Good candidates include those with moderate to severe frown lines, forehead lines, or crow's feet; those seeking preventative treatment before lines become deeply set; and those who want natural-looking results without a frozen or overdone appearance. We screen for medical history, allergies, and pregnancy. Kendall County residents and clients from Naperville, Plainfield, and Aurora often travel to our Oswego location for our personalized approach. If you have concerns about candidacy, we encourage you to book a consultation—we will review your goals and determine whether Botox, Dysport, Jeuveau, or a combination is right for you. We also welcome clients interested in PRF Hair Restoration in Oswego and other regenerative treatments.",
    whatToExpect:
      "Your Botox appointment at Hello Gorgeous typically takes 15 to 20 minutes. We cleanse the treatment area, may apply a topical numbing agent for comfort, and use fine needles to inject small amounts of product into the targeted muscles. Most clients describe the sensation as a quick pinch. You can return to normal activities immediately afterward, though we recommend avoiding intense exercise, rubbing the treated area, or lying flat for several hours. Results usually appear within three to seven days, with full effect by 10 to 14 days. Results typically last three to four months, depending on your metabolism, the areas treated, and the product used. We schedule a follow-up to ensure you are happy with your results and to discuss when to schedule your next appointment. Clients from Oswego, Naperville, Aurora, and Plainfield appreciate our efficiency, expertise, and welcoming environment.",
    safetyAndTraining:
      "Botox is FDA-approved and has been used safely for decades. At Hello Gorgeous in Oswego, our injectors are licensed nurses and nurse practitioners with specialized training in facial aesthetics. We follow evidence-based protocols, use FDA-approved products only, and maintain strict sterile technique. Our commitment to safety extends to every treatment we offer—including Weight Loss in Oswego and Hormone Therapy in Oswego—so you can trust that you are in capable hands. We take a conservative approach to dosing and placement to minimize the risk of adverse effects and to achieve natural-looking results. If you have questions about safety, we encourage you to ask during your consultation. We believe informed clients make the best decisions for their care.",
    communityContext:
      "Hello Gorgeous is proud to serve the Oswego community and Kendall County residents. We welcome clients from Naperville, Plainfield, Aurora, Yorkville, and the surrounding Fox Valley suburbs. Our downtown Oswego location is easily accessible from I-88 and Route 34, making us a convenient choice for busy professionals and families. We participate in local events and support the Oswego business community. Whether you are a first-time Botox client or a long-time devotee, we are here to help you look and feel your best. Many of our clients also explore PRF Hair Restoration in Oswego and our full range of medical aesthetics services. We believe everyone deserves access to safe, effective, and personalized care. Oswego and the greater Fox Valley deserve a med spa that puts client outcomes first.",
    callToAction:
      "Ready to explore Botox in Oswego? Book a consultation at Hello Gorgeous Med Spa. We will review your goals, answer your questions, and create a treatment plan tailored to you. Serving Oswego, Naperville, Plainfield, Aurora, and Kendall County residents. Schedule your visit today and discover why so many clients trust us for natural-looking results. Our Oswego location is easy to find and offers a welcoming, professional environment for your aesthetic journey.",
  },
  "weight-loss-oswego-il": {
    intro:
      "Hello Gorgeous Med Spa offers medical weight loss programs in Oswego, IL, including GLP-1 therapy with Semaglutide and Tirzepatide. We provide ongoing support, lab monitoring, and lifestyle guidance. Located at 74 W. Washington Street in downtown Oswego, we serve clients from Oswego, Naperville, Plainfield, Aurora, Yorkville, and throughout Kendall County. Our nurse practitioners take a comprehensive approach to weight management: we evaluate your health, discuss your goals, and design a plan that is safe, sustainable, and personalized. Kendall County residents and visitors from across the Fox Valley choose Hello Gorgeous for medically supervised weight loss that combines medication, education, and ongoing support. Our Oswego location is conveniently situated near I-88 and Route 34 for easy access from the surrounding suburbs. We believe that sustainable weight loss requires a team approach, and we are committed to supporting you every step of the way.",
    aboutTreatment:
      "Medical weight loss at Hello Gorgeous is not a quick fix—it is a structured program that addresses the biological and behavioral factors that affect weight. GLP-1 medications can help reduce appetite, improve satiety, and support meaningful weight loss when combined with diet and exercise. We screen every client for candidacy, order baseline labs when appropriate, and monitor your progress throughout your journey. Our Oswego location serves clients from Naperville, Aurora, Plainfield, and Kendall County who want personalized, medically supervised care. Many of our weight loss clients also explore Botox in Oswego and Hormone Therapy in Oswego for a holistic approach to wellness. We believe in building long-term relationships: we are here to support you through plateaus, adjust your plan as needed, and celebrate your successes. Every program is tailored to your unique needs and goals. Serving Oswego, Naperville, Plainfield, and Aurora, we bring medically supervised weight loss to the Fox Valley.",
    candidacy:
      "Good candidates for medical weight loss at Hello Gorgeous include adults with a BMI in the overweight or obese range, those with weight-related health concerns, and those who have struggled with traditional diet and exercise alone. We evaluate medical history, medications, and lifestyle to determine whether GLP-1 therapy or another approach is appropriate. Kendall County residents and clients from Oswego, Naperville, Plainfield, and Aurora often find our program fits their busy schedules. We do not prescribe without proper screening; your safety is our priority. If you are unsure whether you qualify, we encourage you to book a consultation. We will review your goals, discuss options, and create a plan that works for you. We also offer PRF Hair Restoration in Oswego for clients interested in regenerative treatments.",
    whatToExpect:
      "Your weight loss journey at Hello Gorgeous begins with a consultation. We review your medical history, discuss your goals, and determine whether GLP-1 therapy or another approach is right for you. If you are a candidate, we outline the medication, dosing schedule, cost, and what to expect in the coming months. We also discuss nutrition, exercise, and other lifestyle factors. Follow-up visits are scheduled to monitor your progress, manage any side effects, and adjust your plan. We use telehealth when appropriate to make your care convenient for clients across Oswego, Naperville, Aurora, and Plainfield. Many clients see noticeable changes within the first few months. Sustainable weight loss takes time—we are committed to supporting you every step of the way. Our clients appreciate our clinical rigor and our compassionate, judgment-free approach. Kendall County residents find our Oswego location convenient and welcoming.",
    safetyAndTraining:
      "Our weight loss programs are medically supervised by licensed nurse practitioners with expertise in metabolic health. We follow evidence-based protocols, use FDA-approved medications, and require appropriate lab monitoring. Your safety is our top priority: we screen for contraindications, monitor for side effects, and adjust your plan as needed. Hello Gorgeous in Oswego maintains the same high standards for all of our services—including Botox in Oswego, Hormone Therapy in Oswego, and PRF Hair Restoration in Oswego. We believe everyone deserves access to safe, effective weight loss care. If you have questions about how the program works or what to expect, we encourage you to ask during your consultation. We are here to guide you through every step of your journey.",
    communityContext:
      "Hello Gorgeous is committed to the health and wellness of the Oswego community and Kendall County residents. We serve clients from Naperville, Plainfield, Aurora, Yorkville, and the Fox Valley with medically supervised weight loss. Our downtown Oswego location is easily accessible and offers a welcoming, professional environment. We believe the Oswego community and surrounding suburbs deserve access to comprehensive care—from weight loss to Botox in Oswego and beyond. Whether you are just starting your weight loss journey or looking for ongoing support, we are here to help. We take pride in being a trusted resource for our neighbors and visitors throughout the Fox Valley.",
    callToAction:
      "Ready to start your weight loss journey? Book a consultation at Hello Gorgeous Med Spa in Oswego. We will evaluate your candidacy, discuss your options, and create a plan tailored to you. Serving Oswego, Naperville, Plainfield, Aurora, and Kendall County residents. Schedule your visit today and take the first step toward a healthier, more confident you. Our downtown Oswego med spa is your partner in achieving lasting weight management goals.",
  },
  "prf-hair-restoration-oswego-il": {
    intro:
      "Hello Gorgeous Med Spa offers PRF (Platelet-Rich Fibrin) hair restoration in Oswego, IL. PRF uses your own growth factors to stimulate natural hair growth and improve hair density. Located at 74 W. Washington Street in downtown Oswego, serving Oswego, Naperville, Plainfield, Aurora, Yorkville, and throughout Kendall County, we bring regenerative expertise to the Fox Valley. Our providers are trained in regenerative techniques and take a personalized approach to every treatment. Kendall County residents and clients from across the Fox Valley choose Hello Gorgeous for a natural, science-backed approach to hair restoration. Our Oswego location is convenient for those traveling from Naperville, Aurora, and Plainfield. We believe everyone deserves access to effective, minimally invasive hair loss solutions. PRF harnesses your body's natural healing power—no synthetic additives, just your own growth factors working to support healthier, fuller hair.",
    aboutTreatment:
      "PRF hair restoration is a minimally invasive treatment that harnesses your body's healing response. We draw a small amount of your blood, process it to concentrate growth factors, and inject the PRF into your scalp. This can help strengthen existing hair follicles, support new growth, and improve overall hair health. Unlike some treatments, PRF uses your own blood—no synthetic additives. At Hello Gorgeous in Oswego, we evaluate each client to ensure PRF is appropriate for their goals and hair loss pattern. We serve clients throughout the Fox Valley who want a natural approach. Many of our clients also explore Botox in Oswego, Weight Loss in Oswego, and Hormone Therapy in Oswego for comprehensive wellness. We believe in transparent communication: we explain what PRF can and cannot do, how many sessions you may need, and what results to expect. Serving Oswego, Naperville, Plainfield, and Aurora, we bring regenerative hair care to Kendall County and the greater Chicago suburbs.",
    candidacy:
      "Good candidates for PRF hair restoration include those with early to moderate hair thinning, those seeking a natural alternative to pharmaceutical options, and those who want to support the health of existing follicles. We evaluate your hair loss pattern, medical history, and goals during your consultation. Kendall County residents and clients from Oswego, Naperville, Plainfield, and Aurora often travel to our location for our expertise. PRF is not right for everyone; we will help you understand whether it is a good fit for your situation. If you are curious about other services, we also offer Weight Loss in Oswego and Hormone Therapy in Oswego. We encourage you to book a consultation to discuss your options. Our Oswego med spa serves the Fox Valley with personalized care for every client.",
    whatToExpect:
      "A PRF hair restoration session at Hello Gorgeous typically takes 60 to 90 minutes. We draw your blood, process it in a centrifuge, and prepare the PRF for injection. We may use a topical numbing agent to maximize comfort. The injections are made into the scalp in areas where you are experiencing thinning or loss. Most clients return to normal activities the same day, with minimal downtime. Some clients experience mild tenderness or swelling for a day or two. Results develop gradually over several months as your follicles respond to the growth factors. Many protocols recommend a series of treatments for optimal outcomes. We create a plan tailored to your goals and schedule. Clients from Oswego, Naperville, Aurora, and Plainfield choose us for our expertise and welcoming environment. Our downtown Oswego location makes it easy for Kendall County residents to access advanced regenerative care.",
    safetyAndTraining:
      "PRF uses your own blood-derived components and is generally well-tolerated. Our providers are trained in phlebotomy, processing, and injection techniques. We follow strict sterile protocol and use FDA-cleared equipment. At Hello Gorgeous in Oswego, we maintain the same safety standards across all services—including Botox in Oswego, Weight Loss in Oswego, and Hormone Therapy in Oswego. We review contraindications and discuss risks during your consultation. Your safety and satisfaction are our top priorities. If you have questions about the procedure or what to expect, we are here to answer them. Serving Oswego, Naperville, Plainfield, and Aurora, we take pride in offering regenerative treatments that meet the highest standards of care.",
    communityContext:
      "Hello Gorgeous is proud to serve the Oswego community and Kendall County residents with PRF hair restoration. We welcome clients from Naperville, Plainfield, Aurora, Yorkville, and the Fox Valley. Our downtown Oswego location is easily accessible from I-88 and Route 34. We believe everyone deserves access to regenerative treatments that support natural, healthy outcomes. Whether you are exploring hair restoration for the first time or supplementing other care, we are here to guide you. We also offer Botox in Oswego and our full range of medical aesthetics for clients seeking comprehensive care. Serving the greater Chicago area, we bring natural hair restoration to the Fox Valley.",
    callToAction:
      "Ready to explore PRF hair restoration? Book a consultation at Hello Gorgeous Med Spa in Oswego. We will evaluate your candidacy, discuss your goals, and create a personalized plan. Serving Oswego, Naperville, Plainfield, Aurora, and Kendall County residents. Schedule your visit today and take the first step toward healthier, fuller hair. Our Oswego location offers a comfortable, professional setting for your regenerative hair journey in the heart of the Fox Valley.",
  },
  "hormone-therapy-oswego-il": {
    intro:
      "Hello Gorgeous Med Spa offers BioTE hormone therapy in Oswego, IL for clients seeking hormone optimization. Our nurse practitioners specialize in pellet therapy and other hormone replacement options, with lab monitoring and ongoing support. Located at 74 W. Washington Street in downtown Oswego, serving Oswego, Naperville, Plainfield, Aurora, Yorkville, and throughout Kendall County, we bring hormone expertise to the Fox Valley. We take a comprehensive approach: we evaluate your symptoms, review your labs, and design a plan that is safe, effective, and personalized. Kendall County residents and visitors from across the Fox Valley trust Hello Gorgeous for evidence-based hormone care. Our Oswego location is convenient for those traveling from Naperville, Aurora, and Plainfield. We believe everyone deserves access to hormone therapy that prioritizes safety and individualized care. Whether you are experiencing fatigue, mood changes, or other symptoms of hormone decline, we are here to help.",
    aboutTreatment:
      "Hormone imbalances can affect energy, mood, sleep, weight, and overall quality of life. BioTE and similar pellet therapies deliver bioidentical hormones in a steady, convenient format. At Hello Gorgeous in Oswego, we believe in evidence-based care: we order labs, interpret results, and tailor your protocol to your unique needs. We do not over-prescribe; we optimize. Our Oswego location serves the Fox Valley, including clients from Naperville, Aurora, Plainfield, and Kendall County. Many of our hormone therapy clients also explore Botox in Oswego, Weight Loss in Oswego, and PRF Hair Restoration in Oswego for comprehensive wellness. We explain how hormone therapy works, what to expect, and how we will monitor your progress. Your health and wellbeing are our top priorities. We welcome clients who want a clinician who listens and takes the time to get it right. Serving Oswego, Naperville, Plainfield, and Aurora, we bring hormone optimization expertise to the Fox Valley.",
    candidacy:
      "Good candidates for hormone therapy include those experiencing symptoms of hormone decline—such as fatigue, low libido, mood changes, weight gain, or sleep issues—and those with lab-confirmed imbalances. We evaluate medical history, symptoms, and lab work to determine appropriateness. Kendall County residents and clients from Oswego, Naperville, Plainfield, and Aurora often find our program fits their needs. We do not prescribe without proper evaluation and monitoring. If you are curious about candidacy, we encourage you to book a consultation. We will review your goals and create a plan tailored to you. We also offer Weight Loss in Oswego and Botox in Oswego for clients interested in complementary services. Serving the Fox Valley from our Oswego location, we bring hormone expertise to clients who value personalized, evidence-based care. Our med spa welcomes clients seeking safe, effective hormone optimization.",
    whatToExpect:
      "Your hormone therapy journey at Hello Gorgeous begins with a consultation and lab work. We review your symptoms, medical history, and goals. If hormone therapy is appropriate, we discuss options—including pellet therapy—and create a plan. Pellet insertion is a quick in-office procedure. We numb the treatment area and place the pellets under the skin. Most clients resume normal activities within a day or two. Pellets release hormones gradually over several months, so you will need periodic reinsertions. We monitor your labs and symptoms to ensure your protocol remains optimal. Many clients notice improvements in energy, mood, and other symptoms within weeks. Our clients from Oswego, Naperville, Aurora, and Plainfield appreciate our clinical expertise and personalized approach. Kendall County residents find our Oswego location convenient for hormone care and wellness support.",
    safetyAndTraining:
      "Our hormone therapy programs are overseen by licensed nurse practitioners with training in hormone optimization. We follow evidence-based protocols, require lab monitoring, and tailor dosing to your individual needs. Your safety is our priority. At Hello Gorgeous in Oswego, we maintain the same standards for all services—including Botox in Oswego, Weight Loss in Oswego, and PRF Hair Restoration in Oswego. We believe everyone deserves access to safe, individualized hormone care. If you have questions about how the program works or what to expect, we encourage you to ask during your consultation. Serving Oswego, Naperville, Plainfield, and Aurora, we bring evidence-based hormone care to the Fox Valley.",
    communityContext:
      "Hello Gorgeous is dedicated to the health and wellness of the Oswego community and Kendall County residents. We serve clients from Naperville, Plainfield, Aurora, Yorkville, and the Fox Valley with hormone therapy and related services. Our downtown Oswego location is easily accessible from I-88 and Route 34. We believe the Oswego community and surrounding suburbs deserve access to comprehensive care—from hormone therapy to Botox in Oswego and Weight Loss in Oswego. Whether you are new to hormone optimization or looking for a new provider, we are here to support you. Our med spa is proud to serve the greater Chicago area with the highest standards of hormone care.",
    callToAction:
      "Ready to explore hormone therapy? Book a consultation at Hello Gorgeous Med Spa in Oswego. We will evaluate your symptoms, review your labs, and create a personalized plan tailored to you. Serving Oswego, Naperville, Plainfield, Aurora, and Kendall County residents. Schedule your visit today and take the first step toward better energy, mood, and vitality. Our downtown Oswego med spa provides a confidential, supportive environment for your hormone optimization journey in the Fox Valley.",
  },
  "med-spa-oswego-il": {
    intro:
      "Hello Gorgeous Med Spa is Oswego's premier destination for medical aesthetics and wellness. Located at 74 W. Washington Street in downtown Oswego, near the Fox River and the heart of the village, we offer Botox, dermal fillers, weight loss therapy, hormone optimization, PRF/PRP treatments, microneedling, IV therapy, and more. Serving Oswego, Naperville, Aurora, Plainfield, Yorkville, Montgomery, and throughout Kendall County and the Fox Valley, we are your trusted partner for medical aesthetics. Our clinical-first approach means every treatment is personalized, safe, and designed to deliver results you will love. Kendall County residents and visitors from the surrounding suburbs choose Hello Gorgeous for our combination of medical expertise, luxury experience, and commitment to the community. We are proud to call Oswego home and to serve the greater Chicago suburbs with the highest standards of care.",
    aboutTreatment:
      "A med spa combines the luxury of a day spa with the expertise of medical professionals. At Hello Gorgeous in Oswego, our providers are licensed nurses and nurse practitioners who specialize in injectables, regenerative treatments, and metabolic wellness. We are not a high-volume clinic—we take the time to understand your goals, answer your questions, and create a plan that fits your lifestyle. We offer Botox in Oswego, Weight Loss in Oswego, PRF Hair Restoration in Oswego, and Hormone Therapy in Oswego, among other services. Oswego has grown into a thriving community, and we are honored to serve our neighbors and those who travel from Naperville, Aurora, Plainfield, and beyond. Our location is easily accessible from I-88 and Route 34. Our med spa is designed to feel welcoming and professional: you will find a clean, modern space where you can relax and feel confident in the care you are receiving.",
    candidacy:
      "Hello Gorgeous welcomes clients with a wide range of goals—from first-time Botox to medical weight loss, hormone optimization, and regenerative treatments. We evaluate each client individually to ensure the right treatment for their needs. Kendall County residents and clients from Oswego, Naperville, Plainfield, and Aurora often find our med spa fits their busy schedules. Whether you are interested in Weight Loss in Oswego, Hormone Therapy in Oswego, PRF Hair Restoration in Oswego, or Botox in Oswego, we encourage you to book a consultation. We will discuss your goals, review your options, and create a plan tailored to you. We believe everyone deserves access to safe, effective, and personalized care. Serving the Fox Valley from downtown Oswego, we welcome clients who value quality, transparency, and results.",
    whatToExpect:
      "When you visit Hello Gorgeous in Oswego, you will start with a consultation. We discuss your concerns, review your medical history, and recommend treatments that align with your goals. Many clients come in for one service—like Botox or lip filler—and discover others that can enhance their results, such as microneedling or PRP. We never pressure; we educate. Your comfort and satisfaction are our top priorities. Our team will explain every step of your treatment, what to expect during recovery, and how to maintain your results. We offer flexible scheduling to accommodate busy professionals and parents from Oswego, Naperville, Aurora, Plainfield, and the surrounding area. Whether you are preparing for a special event or simply want to look and feel your best every day, we are here to help. Kendall County residents appreciate our consult-first approach and our commitment to transparency.",
    safetyAndTraining:
      "Our providers are licensed medical professionals with specialized training in medical aesthetics and wellness. We follow evidence-based protocols, use FDA-approved products when available, and maintain strict standards for every treatment. At Hello Gorgeous in Oswego, we take the same approach to safety whether you are here for Botox in Oswego, Weight Loss in Oswego, Hormone Therapy in Oswego, or PRF Hair Restoration in Oswego. We believe informed clients make the best decisions. If you have questions about safety, training, or what to expect, we encourage you to ask during your consultation. We are here to guide you through every step of your journey. Kendall County residents trust Hello Gorgeous for our clinical expertise and commitment to safety.",
    communityContext:
      "As a proud member of the Oswego business community, Hello Gorgeous is committed to delivering exceptional care to our neighbors and visitors. We serve the Fox Valley—including Kendall County residents from Naperville, Plainfield, Aurora, and Yorkville—with the same dedication and expertise that have made us a trusted name in medical aesthetics. Our downtown Oswego location is conveniently situated for clients throughout the region. Whether you are exploring Botox in Oswego, Weight Loss in Oswego, or our full range of services, we welcome you. We believe the Oswego community and surrounding suburbs deserve access to comprehensive, high-quality care. Our med spa near the Fox River is your destination for medical aesthetics in the heart of the village.",
    callToAction:
      "Ready to explore what Hello Gorgeous has to offer? Book a consultation at our Oswego med spa. We will discuss your goals, answer your questions, and create a plan tailored to you. Serving Oswego, Naperville, Plainfield, Aurora, and Kendall County residents. Schedule your visit today and discover why so many clients trust us for their aesthetic and wellness needs. Our downtown Oswego location is your gateway to premium medical aesthetics in the Fox Valley.",
  },
};

function wordCount(text: string): number {
  return text.trim().split(/\s+/).filter(Boolean).length;
}

export function getLocationPageWordCount(slug: string): number {
  const content = LOCATION_PAGE_CONTENT[slug];
  if (!content) return 0;
  return Object.values(content).reduce((sum, t) => sum + wordCount(t || ""), 0);
}

export const REQUIRED_SLUGS = [
  "botox-oswego-il",
  "med-spa-oswego-il",
  "weight-loss-oswego-il",
  "prf-hair-restoration-oswego-il",
  "hormone-therapy-oswego-il",
];

const MIN_WORDS = 850;

export function checkContentDepth(): { slug: string; words: number; ok: boolean }[] {
  return REQUIRED_SLUGS.map((slug) => {
    const words = getLocationPageWordCount(slug);
    return { slug, words, ok: words >= MIN_WORDS };
  });
}

export function getMinWords(): number {
  return MIN_WORDS;
}
