import {
  definePage,
  educationBlock,
  expectSteps,
  standardFaqs,
} from "./build";
import type { ServicePageData } from "./types";

const TRIFECTA_EXTRA = [
  "Only med spa in the Oswego area with the full InMode Trifecta platform (Morpheus8 Burst, Solaria CO₂, Quantum RF)",
];

export const SERVICE_PAGES_OSwego: ServicePageData[] = [
  definePage({
    slug: "botox-oswego",
    serviceName: "Botox",
    fullServiceName: "Botox, Dysport & Jeuveau",
    targetKeyword: "botox oswego",
    h1: "Botox in Oswego, IL",
    valueProp:
      "$10/unit Botox with a full-authority nurse practitioner on site — natural results, free consultations, same-day appointments when available.",
    tier: "contested",
    procedureType: "Injection",
    bodyLocation: "Face",
    metaDescriptionExtra:
      "From $10/unit. NP on site 7 days/week. Free consults. Dysport & Jeuveau too. Book online.",
    whyBullets: [
      "Full-authority FNP-BC on site — prescriptions and clinical decisions without waiting on a remote MD",
      "Transparent $10/unit pricing for qualifying clients (see consult for your plan)",
      "Complimentary touch-up window for true asymmetry at day 14 through day 21",
      "Allē rewards and experienced injectors focused on natural movement",
      "Serving Naperville, Aurora, Plainfield, and Kendall County from downtown Oswego",
    ],
    howItWorksParagraphs: educationBlock("Botox", "botox oswego", [
      "Botox is a neuromodulator — it temporarily relaxes targeted facial muscles that create expression lines such as forehead lines, frown lines (11s), and crow's feet. Results typically begin in 3–7 days and peak around two weeks. Most clients enjoy results for about three to four months before a refresh.",
      "At Hello Gorgeous, dosing is customized. Our goal is not a frozen look; it is balanced, refreshed expression. We discuss your anatomy, prior treatments, and lifestyle (exercise, metabolism) because those factors influence how long your result lasts.",
      "We also offer Dysport and Jeuveau for clients who respond better to alternate neuromodulators. Your provider can recommend the best product for your goals during a free consultation.",
      "Pricing is discussed upfront. Our published $10/unit rate applies to qualifying promotional plans; your exact unit count depends on treatment areas. Forehead, glabella, and crow's feet are the most common starting zones, but lip flip, masseter slimming, neck bands, and hyperhidrosis are available after evaluation.",
      "Safety matters: Botox is FDA-approved for cosmetic and therapeutic uses when administered by trained medical professionals. We screen for pregnancy, certain neuromuscular conditions, and medications that may increase bruising. After treatment, avoid rubbing the area, strenuous exercise, and lying flat for several hours per your aftercare sheet.",
      "If you have been searching \"botox oswego\" and comparing med spas, ask who will inject you, who supervises complications, and how touch-ups are handled. Those answers separate a medical spa from a discount injector pop-up.",
    ]),
    whatToExpectSteps: expectSteps("Botox"),
    faqs: standardFaqs("Botox", "botox oswego", [
      {
        q: "How much does Botox cost in Oswego?",
        a: "We publish $10/unit for qualifying plans. Most forehead + glabella + crow's feet treatments use 20–50 total units. Your exact quote is provided at a free consultation.",
      },
      {
        q: "Botox vs Dysport vs Jeuveau — which is best?",
        a: "All three are neuromodulators with similar goals. Some clients metabolize one faster than another. We recommend the best fit after assessing your anatomy and history.",
      },
      {
        q: "When will I see Botox results?",
        a: "Early changes in 3–7 days; full effect typically by day 14. We schedule a complimentary touch-up for true asymmetry through day 21 when clinically appropriate.",
      },
    ]),
    relatedServices: ["dysport-oswego", "lip-filler-oswego", "dermal-fillers-oswego"],
  }),

  definePage({
    slug: "dysport-oswego",
    serviceName: "Dysport",
    fullServiceName: "Dysport",
    targetKeyword: "dysport oswego",
    h1: "Dysport in Oswego, IL",
    valueProp: "Dysport wrinkle relaxers with NP-led care, natural dosing, and free consultations in downtown Oswego.",
    tier: "contested",
    procedureType: "Injection",
    bodyLocation: "Face",
    metaDescriptionExtra: "NP on site. Natural results. Compare Botox & Jeuveau. Book a free consult.",
    howItWorksParagraphs: educationBlock("Dysport", "dysport oswego", [
      "Dysport is an FDA-approved neuromodulator used to soften frown lines, forehead lines, and crow's feet. Some clients feel Dysport spreads slightly differently than Botox, which can matter for larger treatment zones.",
      "Your Hello Gorgeous provider will compare Dysport, Botox, and Jeuveau based on your prior response, metabolism, and goals. We do not push one brand — we push the result you want.",
      "Treatment takes about 15–20 minutes for typical upper-face areas. Downtime is minimal; small bumps or pinkness usually resolve within hours. Bruising is possible and more likely if you take blood thinners or drink alcohol close to treatment.",
    ]),
    whatToExpectSteps: expectSteps("Dysport"),
    faqs: standardFaqs("Dysport", "dysport oswego", [
      { q: "Is Dysport the same as Botox?", a: "Both relax targeted muscles, but they are different formulations. Some clients prefer one over the other for onset or longevity." },
    ]),
    relatedServices: ["botox-oswego", "jeuveau-oswego", "dermal-fillers-oswego"],
  }),

  definePage({
    slug: "jeuveau-oswego",
    serviceName: "Jeuveau",
    fullServiceName: "Jeuveau",
    targetKeyword: "jeuveau oswego",
    h1: "Jeuveau in Oswego, IL",
    valueProp: "Jeuveau (#NEWTOX) injectables with medical oversight and boutique care in Oswego.",
    tier: "contested",
    procedureType: "Injection",
    bodyLocation: "Face",
    metaDescriptionExtra: "Modern neuromodulator option. NP on site. Book your free consultation today.",
    howItWorksParagraphs: educationBlock("Jeuveau", "jeuveau oswego", [
      "Jeuveau is a neuromodulator FDA-approved for glabellar (frown) lines. Clients searching jeuveau oswego often want a Botox alternative with competitive pricing and a medical team they trust.",
      "We use the same consultation process as other injectables: assess movement, discuss symmetry, and plan units before treatment. Results timeline mirrors other neuromodulators — days to two weeks for full effect.",
    ]),
    whatToExpectSteps: expectSteps("Jeuveau"),
    faqs: standardFaqs("Jeuveau", "jeuveau oswego"),
    relatedServices: ["botox-oswego", "dysport-oswego", "lip-filler-oswego"],
  }),

  definePage({
    slug: "dermal-fillers-oswego",
    serviceName: "Dermal Fillers",
    fullServiceName: "Dermal Fillers",
    targetKeyword: "dermal fillers oswego",
    h1: "Dermal Fillers in Oswego, IL",
    valueProp: "Hyaluronic acid fillers for cheeks, jawline, nasolabial folds, and facial balance — priced by syringe with NP oversight.",
    tier: "contested",
    procedureType: "Injection",
    bodyLocation: "Face",
    metaDescriptionExtra: "Juvederm & Restylane experts. Free consult. Natural volume. Book online.",
    howItWorksParagraphs: educationBlock("Dermal fillers", "dermal fillers oswego", [
      "Dermal fillers restore structure and volume using hyaluronic acid gels placed beneath the skin. Common goals include cheek enhancement, jawline definition, nasolabial fold softening, chin projection, and under-eye support when appropriate.",
      "Fillers are priced by syringe, not by area. Additional product means additional cost — we explain this clearly at consultation so there are no surprises.",
      "Results are visible immediately but continue to settle over 2–4 weeks as swelling resolves. True clinical asymmetry may be corrected at a complimentary 2-week follow-up when indicated.",
    ]),
    whatToExpectSteps: expectSteps("dermal fillers"),
    faqs: standardFaqs("dermal fillers", "dermal fillers oswego", [
      { q: "How long do fillers last?", a: "Many facial fillers last roughly 6–18 months depending on product, placement, and metabolism." },
      { q: "Can fillers be dissolved?", a: "Hyaluronic acid fillers can often be dissolved with hyaluronidase if needed. We discuss risks and options beforehand." },
    ]),
    relatedServices: ["lip-filler-oswego", "botox-oswego", "morpheus8-burst-oswego"],
  }),

  definePage({
    slug: "lip-filler-oswego",
    serviceName: "Lip Filler",
    fullServiceName: "Lip Filler",
    targetKeyword: "lip filler oswego",
    h1: "Lip Filler in Oswego, IL",
    valueProp: "Subtle to defined lip enhancement with Juvederm and Restylane — shape, hydration, and proportion tailored to your face.",
    tier: "contested",
    procedureType: "Injection",
    bodyLocation: "Face",
    metaDescriptionExtra: "Natural lip results. NP injectors. Free consultation in Oswego.",
    howItWorksParagraphs: educationBlock("Lip filler", "lip filler oswego", [
      "Lip filler adds volume and definition using hyaluronic acid products designed for delicate lip tissue. We prioritize balance with your chin, nose, and overall facial proportions — not a one-shape-fits-all trend.",
      "Swelling is normal for several days. Final shape is best judged around two weeks. We provide aftercare to reduce bruising risk and schedule follow-up if needed.",
    ]),
    whatToExpectSteps: expectSteps("lip filler"),
    faqs: standardFaqs("lip filler", "lip filler oswego", [
      { q: "How many syringes do lips need?", a: "Many clients start with 0.5–1 syringe. Goals for dramatic volume may require staged sessions." },
    ]),
    relatedServices: ["dermal-fillers-oswego", "botox-oswego", "chemical-peel-oswego"],
  }),

  definePage({
    slug: "morpheus8-burst-oswego",
    serviceName: "Morpheus8 Burst",
    fullServiceName: "Morpheus8 Burst RF Microneedling",
    targetKeyword: "morpheus8 burst oswego",
    h1: "Morpheus8 Burst in Oswego, IL",
    valueProp: "Deepest RF microneedling in the area — face and body skin tightening, texture, and contouring with Burst technology.",
    tier: "contested",
    procedureType: "RF",
    bodyLocation: "Face and Body",
    inModeBadge: "morpheus8",
    metaDescriptionExtra: "InMode Morpheus8 Burst. Face & body. NP on site. Free consult — book now.",
    whyBullets: [
      ...TRIFECTA_EXTRA,
      "Full-authority nurse practitioner (FNP-BC) on site — not a remote medical director",
      "Free consultations and honest candidacy conversations before you invest",
      "Same-day and next-day appointments when our schedule allows",
    ],
    howItWorksParagraphs: educationBlock("Morpheus8 Burst", "morpheus8 burst oswego", [
      "Morpheus8 Burst combines microneedling with radiofrequency energy delivered at customizable depths — including deeper body settings many older devices cannot reach. It treats laxity, texture, acne scarring, and stubborn fat pockets on abdomen, arms, and thighs when clinically appropriate.",
      "Hello Gorgeous invested in Burst because Kendall County clients asked for one platform that could address both face and body without sending them to Chicago.",
      "A series is typically recommended. Downtime varies by depth and area; we provide pre-treatment prep (often including antiviral coverage for deeper face treatments) and written aftercare.",
    ]),
    whatToExpectSteps: expectSteps("Morpheus8 Burst"),
    faqs: standardFaqs("Morpheus8 Burst", "morpheus8 burst oswego", [
      { q: "How many Morpheus8 sessions will I need?", a: "Many plans include 3 treatments spaced several weeks apart. Your provider tailors depth and count to your goals." },
    ]),
    relatedServices: ["solaria-co2-oswego", "quantum-rf-oswego", "microneedling-oswego"],
  }),

  definePage({
    slug: "solaria-co2-oswego",
    serviceName: "Solaria CO₂",
    fullServiceName: "Solaria CO₂ Laser Resurfacing",
    targetKeyword: "solaria co2 oswego",
    h1: "Solaria CO₂ in Oswego, IL",
    valueProp: "Fractional CO₂ resurfacing for wrinkles, sun damage, scars, and texture — exclusive InMode Solaria technology in Oswego.",
    tier: "uncontested",
    procedureType: "Laser",
    bodyLocation: "Face",
    inModeBadge: "solaria",
    metaDescriptionExtra: "Advanced CO₂ laser in Oswego. NP-supervised. Free consultation — schedule today.",
    whyBullets: TRIFECTA_EXTRA,
    howItWorksParagraphs: educationBlock("Solaria CO₂", "solaria co2 oswego", [
      "Solaria is our fractional CO₂ platform designed for significant skin renewal — fine lines, photodamage, acne scars, and uneven texture. CO₂ treatments remove damaged surface layers while stimulating collagen remodeling below.",
      "Because CO₂ is powerful, candidacy and downtime are discussed honestly. Medical clearance, antivirals when indicated, and strict sun protection are part of safe outcomes.",
      "Clients choose Hello Gorgeous when they want hospital-grade technology without hospital-system pricing — with an NP on site for questions every step of the way.",
    ]),
    whatToExpectSteps: expectSteps("Solaria CO₂"),
    faqs: standardFaqs("Solaria CO₂", "solaria co2 oswego", [
      { q: "What is downtime after CO₂?", a: "Depends on depth and treatment zone. We provide a detailed timeline at consultation — plan for redness, peeling, and strict sun avoidance." },
    ]),
    relatedServices: ["morpheus8-burst-oswego", "quantum-rf-oswego", "chemical-peel-oswego"],
  }),

  definePage({
    slug: "quantum-rf-oswego",
    serviceName: "Quantum RF",
    fullServiceName: "Quantum RF Body Contouring",
    targetKeyword: "quantum rf oswego",
    h1: "Quantum RF in Oswego, IL",
    valueProp: "Non-invasive RF contouring for stubborn fat and skin tightening — InMode Quantum RF with clinical oversight.",
    tier: "uncontested",
    procedureType: "RF",
    bodyLocation: "Body",
    inModeBadge: "quantum",
    metaDescriptionExtra: "Body contouring RF in Oswego. No surgery. Free consult. Book online.",
    whyBullets: TRIFECTA_EXTRA,
    howItWorksParagraphs: educationBlock("Quantum RF", "quantum rf oswego", [
      "Quantum RF uses radiofrequency energy to heat adipose tissue and dermis, aiming to reduce circumferential fat and improve laxity in treated zones such as abdomen, flanks, arms, and thighs.",
      "It is not a weight-loss replacement — best results combine realistic expectations, hydration, and healthy habits. Many clients pair Quantum with Morpheus8 Burst for comprehensive body goals.",
      "Treatments are comfortable for most patients with warming sensations; series are typically recommended.",
    ]),
    whatToExpectSteps: expectSteps("Quantum RF"),
    faqs: standardFaqs("Quantum RF", "quantum rf oswego"),
    relatedServices: ["morpheus8-burst-oswego", "glp-1-weight-loss-oswego", "semaglutide-oswego"],
  }),

  definePage({
    slug: "semaglutide-oswego",
    serviceName: "Semaglutide",
    fullServiceName: "Semaglutide Medical Weight Loss",
    targetKeyword: "semaglutide oswego",
    h1: "Semaglutide in Oswego, IL",
    valueProp: "Medically supervised GLP-1 weight loss with labs, coaching, and NP oversight — not a telehealth-only program.",
    tier: "contested",
    procedureType: "Wellness",
    metaDescriptionExtra: "GLP-1 weight loss in Oswego. Ryan Kent FNP-BC. Book a consult.",
    howItWorksParagraphs: educationBlock("Semaglutide", "semaglutide oswego", [
      "Semaglutide is a GLP-1 receptor agonist used under medical supervision to support weight loss alongside nutrition and activity changes. Candidates receive screening labs and ongoing monitoring.",
      "Hello Gorgeous is not a 'sign up online and never see a provider' clinic — you have access to an on-site NP for questions, dose adjustments, and side-effect management.",
    ]),
    whatToExpectSteps: expectSteps("semaglutide"),
    faqs: standardFaqs("semaglutide", "semaglutide oswego", [
      { q: "Do you offer telehealth for weight loss?", a: "Some follow-ups may be virtual after an initial evaluation, but medical oversight remains with our Oswego clinical team." },
    ]),
    relatedServices: ["tirzepatide-oswego", "glp-1-weight-loss-oswego", "peptide-therapy-oswego"],
  }),

  definePage({
    slug: "tirzepatide-oswego",
    serviceName: "Tirzepatide",
    fullServiceName: "Tirzepatide Medical Weight Loss",
    targetKeyword: "tirzepatide oswego",
    h1: "Tirzepatide in Oswego, IL",
    valueProp: "Dual-action GLP-1/GIP weight loss therapy with in-person medical support in Oswego.",
    tier: "contested",
    procedureType: "Wellness",
    metaDescriptionExtra: "Medically supervised tirzepatide. NP on site. Start with a free consult.",
    howItWorksParagraphs: educationBlock("Tirzepatide", "tirzepatide oswego", [
      "Tirzepatide targets both GLP-1 and GIP pathways and may be appropriate for selected patients after medical evaluation. Like other GLP-1 therapies, it works best with lifestyle support and regular follow-up.",
      "We review history, medications, and goals before prescribing. Pricing and compounding options are explained at consultation.",
    ]),
    whatToExpectSteps: expectSteps("tirzepatide"),
    faqs: standardFaqs("tirzepatide", "tirzepatide oswego"),
    relatedServices: ["semaglutide-oswego", "glp-1-weight-loss-oswego", "biote-hormone-therapy-oswego"],
  }),

  definePage({
    slug: "glp-1-weight-loss-oswego",
    serviceName: "GLP-1 Weight Loss",
    fullServiceName: "GLP-1 Medical Weight Loss",
    targetKeyword: "glp-1 weight loss oswego",
    h1: "GLP-1 Weight Loss in Oswego, IL",
    valueProp: "Comprehensive GLP-1 programs — semaglutide, tirzepatide, labs, and coaching with an on-site NP.",
    tier: "contested",
    procedureType: "Wellness",
    metaDescriptionExtra: "Medical weight loss Oswego. Supervised GLP-1. Book your consultation.",
    howItWorksParagraphs: educationBlock("GLP-1 weight loss", "glp-1 weight loss oswego", [
      "GLP-1 medications reduce appetite and slow gastric emptying, helping many patients lose weight when combined with nutrition changes. Success depends on medical candidacy, consistency, and follow-up.",
      "Our program includes intake, labs as indicated, education on injection technique, and scheduled check-ins. We coordinate with your primary care provider when needed.",
    ]),
    whatToExpectSteps: expectSteps("GLP-1 therapy"),
    faqs: standardFaqs("GLP-1 weight loss", "glp-1 weight loss oswego"),
    relatedServices: ["semaglutide-oswego", "tirzepatide-oswego", "peptide-therapy-oswego"],
  }),

  definePage({
    slug: "biote-hormone-therapy-oswego",
    serviceName: "BioTE Hormone Therapy",
    fullServiceName: "BioTE Hormone Optimization",
    targetKeyword: "biote oswego",
    h1: "BioTE Hormone Therapy in Oswego, IL",
    valueProp: "BioTE pellet therapy and hormone optimization with lab monitoring and NP-led care.",
    tier: "contested",
    procedureType: "Wellness",
    metaDescriptionExtra: "Hormone therapy Oswego. BioTE provider. Book a consult today.",
    howItWorksParagraphs: educationBlock("BioTE hormone therapy", "biote oswego", [
      "BioTE uses bioidentical hormone pellets placed during an in-office procedure after labs confirm candidacy. Goals often include improved energy, mood, sleep, and libido when deficiency is documented.",
      "Therapy requires ongoing lab monitoring and dose adjustments. We explain risks, benefits, and alternatives including non-pellet protocols.",
    ]),
    whatToExpectSteps: expectSteps("BioTE"),
    faqs: standardFaqs("BioTE", "biote oswego", [
      { q: "How often are pellets replaced?", a: "Typically every 3–6 months depending on metabolism and lab results — your provider will personalize timing." },
    ]),
    relatedServices: ["testosterone-replacement-oswego", "peptide-therapy-oswego", "iv-therapy-oswego"],
  }),

  definePage({
    slug: "testosterone-replacement-oswego",
    serviceName: "Testosterone Replacement",
    fullServiceName: "TRT / Testosterone Replacement Therapy",
    targetKeyword: "trt oswego",
    h1: "Testosterone Replacement in Oswego, IL",
    valueProp: "Medically supervised TRT for qualifying men — labs, dosing, and follow-up with our clinical team.",
    tier: "contested",
    procedureType: "Wellness",
    metaDescriptionExtra: "TRT in Oswego. NP-supervised. Confidential consults. Call or book online.",
    howItWorksParagraphs: educationBlock("Testosterone replacement", "trt oswego", [
      "TRT may be appropriate when lab work and symptoms align with clinically low testosterone. We do not prescribe based on marketing promises alone — diagnosis and monitoring matter.",
      "Delivery options may include injections, creams, or pellets depending on your plan. We review cardiovascular risk, fertility goals, and contraindications before starting.",
    ]),
    whatToExpectSteps: expectSteps("TRT"),
    faqs: standardFaqs("TRT", "trt oswego"),
    relatedServices: ["biote-hormone-therapy-oswego", "peptide-therapy-oswego", "semaglutide-oswego"],
  }),

  definePage({
    slug: "peptide-therapy-oswego",
    serviceName: "Peptide Therapy",
    fullServiceName: "Peptide Therapy",
    targetKeyword: "peptide therapy oswego",
    h1: "Peptide Therapy in Oswego, IL",
    valueProp: "Regenerative peptide protocols for recovery, metabolism, and wellness — medically supervised in Oswego.",
    tier: "uncontested",
    procedureType: "Wellness",
    metaDescriptionExtra: "Peptide therapy near Oswego. NP oversight. Schedule a consultation.",
    howItWorksParagraphs: educationBlock("Peptide therapy", "peptide therapy oswego", [
      "Peptides are short chains of amino acids used in targeted wellness protocols — from recovery support to metabolic optimization — when medically appropriate.",
      "Hello Gorgeous designs plans after reviewing goals, history, and contraindications. We do not sell peptides as anonymous retail products; care stays inside a supervised medical relationship.",
    ]),
    whatToExpectSteps: expectSteps("peptide therapy"),
    faqs: standardFaqs("peptide therapy", "peptide therapy oswego"),
    relatedServices: ["nad-iv-oswego", "iv-therapy-oswego", "glp-1-weight-loss-oswego"],
  }),

  definePage({
    slug: "iv-therapy-oswego",
    serviceName: "IV Therapy",
    fullServiceName: "IV Therapy & Vitamin Drips",
    targetKeyword: "iv therapy oswego",
    h1: "IV Therapy in Oswego, IL",
    valueProp: "Hydration and vitamin IV drips in a medical setting — energy, immunity, recovery, and glow protocols.",
    tier: "contested",
    procedureType: "IV",
    metaDescriptionExtra: "IV drips in Oswego. B-complex, vitamin C, glutathione & more. Book now.",
    howItWorksParagraphs: educationBlock("IV therapy", "iv therapy oswego", [
      "IV therapy delivers fluids and nutrients directly into the bloodstream for clients who want rapid replenishment before events, after illness, or during demanding training seasons.",
      "All IVs are administered by trained clinical staff with screening for kidney, heart, and medication considerations.",
    ]),
    whatToExpectSteps: expectSteps("IV therapy"),
    faqs: standardFaqs("IV therapy", "iv therapy oswego"),
    relatedServices: ["nad-iv-oswego", "vitamin-injections-oswego", "peptide-therapy-oswego"],
  }),

  definePage({
    slug: "nad-iv-oswego",
    serviceName: "NAD+ IV",
    fullServiceName: "NAD+ IV Therapy",
    targetKeyword: "nad iv oswego",
    h1: "NAD+ IV in Oswego, IL",
    valueProp: "NAD+ infusions for cellular energy and recovery support — medically supervised IV therapy in Oswego.",
    tier: "uncontested",
    procedureType: "IV",
    metaDescriptionExtra: "NAD+ IV drips in Oswego. NP on site. Book your session online.",
    howItWorksParagraphs: educationBlock("NAD+ IV", "nad iv oswego", [
      "NAD+ (nicotinamide adenine dinucleotide) IV protocols aim to support cellular energy pathways. Clients often report improved focus or stamina, though individual response varies.",
      "Infusions are titrated for comfort — some clients experience mild flushing or nausea slowed by rate adjustment. Medical screening is required before your first drip.",
    ]),
    whatToExpectSteps: expectSteps("NAD+ IV"),
    faqs: standardFaqs("NAD+ IV", "nad iv oswego"),
    relatedServices: ["iv-therapy-oswego", "peptide-therapy-oswego", "vitamin-injections-oswego"],
  }),

  definePage({
    slug: "laser-hair-removal-oswego",
    serviceName: "Laser Hair Removal",
    fullServiceName: "Laser Hair Removal",
    targetKeyword: "laser hair removal oswego",
    h1: "Laser Hair Removal in Oswego, IL",
    valueProp: "Permanent hair reduction for face and body with customized laser settings and medical oversight.",
    tier: "contested",
    procedureType: "Laser",
    bodyLocation: "Face and Body",
    metaDescriptionExtra: "Laser hair removal Oswego. Safe for many skin types. Free consult.",
    howItWorksParagraphs: educationBlock("Laser hair removal", "laser hair removal oswego", [
      "Laser hair removal targets melanin in the hair follicle to reduce future growth. A series of treatments spaced weeks apart yields the best results.",
      "We adjust device settings for skin tone and hair color. Sun avoidance and pre-treatment shaving instructions are provided for safety and efficacy.",
    ]),
    whatToExpectSteps: expectSteps("laser hair removal"),
    faqs: standardFaqs("laser hair removal", "laser hair removal oswego", [
      { q: "How many sessions will I need?", a: "Most areas need 6–8 sessions on average, though this varies by hormone status, hair color, and treatment zone." },
    ]),
    relatedServices: ["facials-oswego", "chemical-peel-oswego", "microneedling-oswego"],
  }),

  definePage({
    slug: "microneedling-oswego",
    serviceName: "Microneedling",
    fullServiceName: "Microneedling & RF Microneedling",
    targetKeyword: "microneedling oswego",
    h1: "Microneedling in Oswego, IL",
    valueProp: "Collagen-inducing microneedling and RF options for texture, pores, and scars — from classic pens to Morpheus8 Burst.",
    tier: "contested",
    procedureType: "RF",
    bodyLocation: "Face",
    metaDescriptionExtra: "Microneedling in Oswego. RF options available. Book a free consult.",
    howItWorksParagraphs: educationBlock("Microneedling", "microneedling oswego", [
      "Microneedling creates controlled micro-injuries that stimulate collagen remodeling. It helps acne scars, enlarged pores, and fine lines when performed in an appropriate series.",
      "We also offer RF microneedling (Morpheus8 Burst) when deeper tightening is needed. Your provider recommends the right tier so you do not over- or under-treat.",
    ]),
    whatToExpectSteps: expectSteps("microneedling"),
    faqs: standardFaqs("microneedling", "microneedling oswego"),
    relatedServices: ["morpheus8-burst-oswego", "chemical-peel-oswego", "facials-oswego"],
  }),

  definePage({
    slug: "facials-oswego",
    serviceName: "Facials",
    fullServiceName: "Medical Facials & HydraFacial",
    targetKeyword: "facials oswego",
    h1: "Facials in Oswego, IL",
    valueProp: "HydraFacial, Geneo, and medical-grade facials for glow, congestion, and event-ready skin.",
    tier: "contested",
    procedureType: "Topical",
    bodyLocation: "Face",
    metaDescriptionExtra: "HydraFacial & medical facials in Oswego. Book your glow session today.",
    howItWorksParagraphs: educationBlock("Facials", "facials oswego", [
      "Medical facials combine professional exfoliation, extraction, hydration, and targeted serums. HydraFacial and Geneo protocols are popular before weddings, photos, and seasonal skin resets.",
      "Facials complement injectables and laser work — they do not replace medical treatments for deep laxity or scars, but they keep skin healthy between visits.",
    ]),
    whatToExpectSteps: expectSteps("your facial"),
    faqs: standardFaqs("facials", "facials oswego", [
      { q: "HydraFacial vs regular facial?", a: "HydraFacial uses vortex technology for deep cleanse and infusion. Classic facials may be better for specific peels or manual focus areas." },
    ]),
    relatedServices: ["dermaplaning-oswego", "chemical-peel-oswego", "botox-oswego"],
  }),

  definePage({
    slug: "dermaplaning-oswego",
    serviceName: "Dermaplaning",
    fullServiceName: "Dermaplaning",
    targetKeyword: "dermaplaning oswego",
    h1: "Dermaplaning in Oswego, IL",
    valueProp: "Instantly smooth, bright skin with medical-grade dermaplaning — perfect before events or with a facial.",
    tier: "contested",
    procedureType: "Topical",
    bodyLocation: "Face",
    metaDescriptionExtra: "Dermaplaning in Oswego. Peach fuzz removal & glow. Book online.",
    howItWorksParagraphs: educationBlock("Dermaplaning", "dermaplaning oswego", [
      "Dermaplaning uses a surgical blade at a shallow angle to remove vellus hair and dead skin cells. Makeup applies smoothly afterward and skincare penetrates better.",
      "It is not the same as shaving — technique and sanitation standards matter. We often pair dermaplaning with hydrating facials for amplified glow.",
    ]),
    whatToExpectSteps: expectSteps("dermaplaning"),
    faqs: standardFaqs("dermaplaning", "dermaplaning oswego"),
    relatedServices: ["facials-oswego", "chemical-peel-oswego", "microneedling-oswego"],
  }),

  definePage({
    slug: "chemical-peel-oswego",
    serviceName: "Chemical Peels",
    fullServiceName: "Chemical Peels",
    targetKeyword: "chemical peel oswego",
    h1: "Chemical Peels in Oswego, IL",
    valueProp: "Medical-grade peels for acne, pigment, and texture — customized depth for your skin and downtime tolerance.",
    tier: "contested",
    procedureType: "Topical",
    bodyLocation: "Face",
    metaDescriptionExtra: "Chemical peels Oswego. Acne & pigment protocols. Free consult.",
    howItWorksParagraphs: educationBlock("Chemical peels", "chemical peel oswego", [
      "Chemical peels use acids (such as glycolic, salicylic, TCA, or blended formulas) to accelerate cell turnover. Light peels refresh with minimal downtime; deeper peels target stubborn pigment and scars.",
      "We select peel type after analyzing skin tone, sensitivity, and goals. Post-peel sun protection is mandatory to prevent rebound pigment.",
    ]),
    whatToExpectSteps: expectSteps("your peel"),
    faqs: standardFaqs("chemical peels", "chemical peel oswego"),
    relatedServices: ["facials-oswego", "microneedling-oswego", "solaria-co2-oswego"],
  }),

  definePage({
    slug: "prp-oswego",
    serviceName: "PRP",
    fullServiceName: "PRP & PRF Treatments",
    targetKeyword: "prp oswego",
    h1: "PRP in Oswego, IL",
    valueProp: "Platelet-rich plasma and PRF for hair restoration, skin rejuvenation, and joint support — using your own growth factors.",
    tier: "contested",
    procedureType: "Injection",
    bodyLocation: "Face, Scalp, and Joints",
    metaDescriptionExtra: "PRP & PRF in Oswego. Hair, skin & joint protocols. Book a consult.",
    howItWorksParagraphs: educationBlock("PRP", "prp oswego", [
      "PRP concentrates platelets from your blood to stimulate repair in targeted tissue. Applications include thinning hair, crepey skin, and select joint complaints after evaluation.",
      "A blood draw and centrifuge spin precede treatment. Downtime is usually mild for facial PRP; hair protocols require a series for best results.",
    ]),
    whatToExpectSteps: expectSteps("PRP"),
    faqs: standardFaqs("PRP", "prp oswego", [
      { q: "PRP vs PRF — what is the difference?", a: "PRF is a fibrin matrix that releases growth factors more slowly. Your provider recommends the format for your goal." },
    ]),
    relatedServices: ["microneedling-oswego", "morpheus8-burst-oswego", "vitamin-injections-oswego"],
  }),

  definePage({
    slug: "vitamin-injections-oswego",
    serviceName: "Vitamin Injections",
    fullServiceName: "Vitamin B12, B-Complex & MIC Injections",
    targetKeyword: "vitamin injections oswego",
    h1: "Vitamin Injections in Oswego, IL",
    valueProp: "B12, B-complex, and MIC shots for energy and metabolism support — quick in-office visits.",
    tier: "contested",
    procedureType: "Injection",
    metaDescriptionExtra: "B12 & vitamin shots in Oswego. Walk-in friendly. Book online.",
    howItWorksParagraphs: educationBlock("Vitamin injections", "vitamin injections oswego", [
      "Intramuscular vitamin injections bypass digestion for clients with absorption concerns or acute energy needs. B12 supports red blood cell formation; MIC blends are popular in weight-loss plans.",
      "We review medications and conditions before injecting. Many clients book monthly maintenance after an initial series.",
    ]),
    whatToExpectSteps: expectSteps("vitamin injections"),
    faqs: standardFaqs("vitamin injections", "vitamin injections oswego", [
      { q: "Do B12 shots hurt?", a: "Most clients feel a quick pinch in the deltoid or gluteal muscle. The visit is typically under 15 minutes." },
    ]),
    relatedServices: ["iv-therapy-oswego", "nad-iv-oswego", "glp-1-weight-loss-oswego"],
  }),
];
