import type { KnowledgeEntry } from "../types";

/**
 * Site-wide content: membership, VIP/Trifecta, pre & post care, general FAQs.
 * Seeded so chat agents can answer any question from the website.
 */
export const SITE_CONTENT: readonly KnowledgeEntry[] = [
  // ——— Membership (No Prior Authorization) ———
  {
    id: "site.membership-what",
    topic: "No Prior Authorization membership — what it is and benefits",
    category: "membership",
    explanation:
      "No Prior Authorization is a membership program that gives you direct access to healthcare services without traditional insurance hassles, referrals, or waiting periods. Benefits include 10% off all services, priority appointment booking, exclusive member events, early access to new treatments, birthday bonus service, referral rewards program, monthly wellness newsletter, and free annual skin consultation.",
    whatItHelpsWith: ["Understanding membership value", "Deciding between monthly and annual"],
    whoItsFor: ["Anyone considering joining Hello Gorgeous as a member"],
    whoItsNotFor: [],
    commonQuestions: [
      "What is No Prior Authorization?",
      "What are the membership benefits?",
      "How do I get the free $75 service?",
      "What's the difference between monthly and annual?",
      "Can I switch from monthly to annual?",
      "Can I cancel my membership?",
      "Can I use insurance with this?",
      "Who are the providers?",
    ],
    safetyNotes: [],
    escalationTriggers: [],
    relatedTopics: ["site.booking-how", "site.general-location"],
    updatedAt: "2026-03-05T00:00:00.000Z",
    version: 1,
  },
  {
    id: "site.membership-plans",
    topic: "Membership plans: monthly vs annual, free $75, cancel",
    category: "membership",
    explanation:
      "Both monthly and annual plans give full member benefits: 10% off all services and priority booking. The annual plan saves $189/year compared to monthly AND includes a FREE service up to $75 value as a welcome bonus (total savings $264). You can upgrade to annual anytime and immediately receive the free $75 benefit. Cancel anytime: monthly members cancel before the next billing cycle; annual members can cancel but we don't offer prorated refunds for the remaining term. No Prior Authorization operates independently of insurance — you pay transparent, upfront prices.",
    whatItHelpsWith: ["Choosing a plan", "Understanding cancellation"],
    whoItsFor: ["Prospective or current members"],
    whoItsNotFor: [],
    commonQuestions: ["How do I get the free $75 service?", "Can I switch to annual?", "Can I cancel?"],
    safetyNotes: [],
    escalationTriggers: [],
    relatedTopics: ["site.membership-what"],
    updatedAt: "2026-03-05T00:00:00.000Z",
    version: 1,
  },
  // ——— VIP / Trifecta / Morpheus8 / Solaria / Quantum ———
  {
    id: "site.vip-trifecta",
    topic: "VIP Skin Tightening: Quantum RF, Morpheus8 Burst, Solaria CO₂, Trifecta",
    category: "vip",
    explanation:
      "Hello Gorgeous has the NEWEST Morpheus8 Burst — deepest RF at 8mm for face AND body. Only med spa in Oswego, Naperville, Aurora, Plainfield with Morpheus8 Burst. We offer VIP skin tightening with Quantum RF (subdermal body contouring), Morpheus8 Burst (RF microneedling for face and body), and Solaria CO₂ (fractional laser). The Trifecta combines all three. Morpheus8 Burst: single from $800, package of 3 $2,100. Solaria CO₂: single from $1,500. Quantum RF pricing varies by area. You can join the VIP waitlist for priority access.",
    whatItHelpsWith: ["Understanding VIP options", "Pricing and packages", "When scheduling opens"],
    whoItsFor: ["Anyone interested in skin tightening, body contouring, or laser treatments"],
    whoItsNotFor: [],
    commonQuestions: [
      "What is the Trifecta?",
      "What is Quantum RF?",
      "What is Morpheus8?",
      "What is Solaria CO₂?",
      "When can I book VIP treatments?",
      "How much does Morpheus8 cost?",
      "How much does Solaria cost?",
      "How do I get on the VIP list?",
    ],
    safetyNotes: [],
    escalationTriggers: [],
    relatedTopics: ["site.booking-how"],
    updatedAt: "2026-03-05T00:00:00.000Z",
    version: 1,
  },
  // ——— General site: location, hours, booking, first visit ———
  {
    id: "site.general-location",
    topic: "Location, address, hours, contact",
    category: "site",
    explanation:
      "Hello Gorgeous Med Spa is located at 74 W. Washington Street, Oswego, IL 60543. We serve Oswego, Naperville, Aurora, Plainfield, Yorkville, and surrounding areas (Kendall County, Kane County). Phone (630) 636-6193. Email hellogorgeousskin@yahoo.com. Check the website for current hours.",
    whatItHelpsWith: ["Finding us", "Planning a visit"],
    whoItsFor: ["New and returning clients"],
    whoItsNotFor: [],
    commonQuestions: ["Where are you located?", "Do you serve Naperville?", "What are your hours?", "How do I contact you?"],
    safetyNotes: [],
    escalationTriggers: [],
    relatedTopics: ["site.booking-how", "site.first-visit"],
    updatedAt: "2026-03-05T00:00:00.000Z",
    version: 1,
  },
  {
    id: "site.booking-how",
    topic: "How to book: online, in chat, cancel, reschedule",
    category: "site",
    explanation:
      "You can book a live appointment on the website Book page or in the chat widget (pick service, provider Ryan or Danielle, date, and time from live availability). We send confirmation and reminders. To cancel or reschedule, call us or reply to your confirmation message. Pricing depends on the service; we give exact numbers when you book or call. Most aesthetics are self-pay; some medical services may work with insurance — call to ask.",
    whatItHelpsWith: ["Booking an appointment", "Cancelling or rescheduling"],
    whoItsFor: ["Anyone wanting to schedule or change an appointment"],
    whoItsNotFor: [],
    commonQuestions: [
      "How do I book an appointment?",
      "Can I book in chat?",
      "How do I cancel or reschedule?",
      "Who will I see?",
      "What are the next available times?",
      "How much does it cost?",
      "Do you take insurance?",
    ],
    safetyNotes: [],
    escalationTriggers: [],
    relatedTopics: ["site.first-visit", "site.general-location"],
    updatedAt: "2026-03-05T00:00:00.000Z",
    version: 1,
  },
  {
    id: "site.first-visit",
    topic: "First visit, new client, what to expect, intake",
    category: "site",
    explanation:
      "For your first visit we'll have you fill out a short intake; we may send forms before your appointment. Plan to arrive a few minutes early. We'll go over your goals and the treatment. If you're not sure which service to book, a consultation is available so we can get you scheduled for a conversation first. You'll see either Ryan Kent (FNP-BC) or Danielle Alcala (RN-S, Licensed CNA, CMAA, Phlebotomist, Licensed Esthetician, Business Owner) depending on the service and who you choose when you book.",
    whatItHelpsWith: ["Preparing for first visit", "Knowing what to expect"],
    whoItsFor: ["New clients"],
    whoItsNotFor: [],
    commonQuestions: ["What should I expect for my first visit?", "Do I need to bring anything?", "Who will I see?"],
    safetyNotes: [],
    escalationTriggers: [],
    relatedTopics: ["site.booking-how"],
    updatedAt: "2026-03-05T00:00:00.000Z",
    version: 1,
  },
  // ——— Pre & post care (summaries so agents can answer) ———
  {
    id: "site.prepost-botox",
    topic: "Botox pre and post care — before and after",
    category: "site",
    explanation:
      "Before Botox: avoid alcohol 24 hours prior; avoid aspirin, ibuprofen, naproxen, fish oil, vitamin E 5–7 days unless medically necessary; discontinue retinol 3 days prior; avoid facials, chemical peels, or laser within 1 week; arrive with clean skin (no makeup in treatment area). Notify us if pregnant, breastfeeding, have a neuromuscular disorder, or take muscle relaxants. After: mild redness, small injection marks, slight swelling, tenderness are common; avoid rubbing the area 24 hours; avoid strenuous exercise and lying down 4 hours; results typically begin 3–5 days, full effect 10–14 days.",
    whatItHelpsWith: ["Preparing for Botox", "What to do after Botox"],
    whoItsFor: ["Anyone with an upcoming or recent Botox appointment"],
    whoItsNotFor: ["Anyone with severe post-treatment symptoms — contact provider or seek urgent care"],
    commonQuestions: ["What should I avoid before Botox?", "What do I do after Botox?", "When will I see results?"],
    safetyNotes: ["No medical advice. Severe symptoms require evaluation."],
    escalationTriggers: ["vision", "severe headache", "trouble swallowing", "breathing"],
    relatedTopics: ["aftercare.general-aftercare", "expectations.neuromodulator-timeline"],
    updatedAt: "2026-03-05T00:00:00.000Z",
    version: 1,
  },
  {
    id: "site.prepost-filler",
    topic: "Filler pre and post care — before and after",
    category: "site",
    explanation:
      "Before filler: avoid blood thinners (aspirin, ibuprofen, fish oil, vitamin E) as advised; avoid alcohol 24–48 hours; no dental work or major procedures shortly before; arrive with clean skin. After filler: swelling and bruising can occur; avoid touching or massaging the area unless instructed; avoid strenuous exercise 24–48 hours; avoid extreme heat or cold; swelling often peaks 24–72 hours and settles over 1–2 weeks; final assessment best after settling. Red flags: vision changes, severe pain, skin color changes — seek urgent care.",
    whatItHelpsWith: ["Preparing for filler", "What to expect after filler"],
    whoItsFor: ["Anyone with an upcoming or recent filler appointment"],
    whoItsNotFor: ["Anyone with red-flag symptoms — seek urgent care"],
    commonQuestions: ["What should I avoid before filler?", "How long does swelling last?", "When can I exercise after filler?"],
    safetyNotes: ["Red flags: vision changes, severe pain, blanching or dusky skin — seek urgent care."],
    escalationTriggers: ["vision", "blanch", "dusky", "severe pain"],
    relatedTopics: ["aftercare.filler-swelling-bruising", "expectations.filler-timeline"],
    updatedAt: "2026-03-05T00:00:00.000Z",
    version: 1,
  },
  {
    id: "site.prepost-general",
    topic: "Pre and post care — general guidance",
    category: "site",
    explanation:
      "We have specific pre and post care guides for Botox, filler, microneedling, chemical peel, laser, IV therapy, weight loss, hormone therapy, PRP/PRF, and trigger point. In general: follow your provider's written instructions; avoid blood thinners and alcohol before injectables as advised; protect skin from sun after treatments; contact the clinic if something feels unusual or worsening. For detailed instructions, see our Pre & Post Care section on the website or ask for your specific treatment.",
    whatItHelpsWith: ["Finding the right care instructions", "When to contact the clinic"],
    whoItsFor: ["Anyone with a scheduled or recent treatment"],
    whoItsNotFor: ["Anyone with severe or urgent symptoms — seek urgent care"],
    commonQuestions: ["Where do I find pre/post instructions?", "What if I have a reaction?", "When should I call?"],
    safetyNotes: ["Severe symptoms require urgent evaluation."],
    escalationTriggers: ["severe", "worsening", "vision", "breathing", "infection"],
    relatedTopics: ["aftercare.general-aftercare", "safety.post-treatment-red-flags"],
    updatedAt: "2026-03-05T00:00:00.000Z",
    version: 1,
  },
  // ——— Programs (Precision Hormone, Metabolic Reset) ———
  {
    id: "site.programs-memberships",
    topic: "Precision Hormone Program and Metabolic Reset Program",
    category: "membership",
    explanation:
      "Precision Hormone Program: full-spectrum hormone optimization — prescriptions, IV therapy, vitamin injections, HRT, blood work with next-day results, same-day visits, AI-powered insights. About $199/month. Metabolic Reset Program: medical weight loss with tirzepatide — prescription included (up to 5mg for $450/mo or 7.5mg for $499/mo), same-day visits, next-day labs, quarterly check-ins, secure messaging. Both programs include supplement support via Fullscript. No semaglutide; we only offer tirzepatide for weight loss.",
    whatItHelpsWith: ["Understanding hormone and weight loss programs", "Pricing and what's included"],
    whoItsFor: ["Anyone interested in hormone optimization or medical weight loss"],
    whoItsNotFor: [],
    commonQuestions: [
      "What is the Precision Hormone Program?",
      "What is the Metabolic Reset Program?",
      "How much is tirzepatide?",
      "Do you offer semaglutide?",
    ],
    safetyNotes: ["Program eligibility requires clinician evaluation."],
    escalationTriggers: [],
    relatedTopics: ["site.membership-what", "weight-loss.metabolic-care-basics", "hormones.bhrt-basics"],
    updatedAt: "2026-03-05T00:00:00.000Z",
    version: 1,
  },
];
