// ============================================================
// HELLO GORGEOUS OS - DATABASE TYPES
// Auto-generated type definitions for Supabase
// ============================================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          auth_id: string | null;
          email: string;
          phone: string | null;
          role: 'client' | 'provider' | 'admin' | 'superadmin';
          first_name: string;
          last_name: string;
          avatar_url: string | null;
          email_verified: boolean;
          phone_verified: boolean;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          auth_id?: string | null;
          email: string;
          phone?: string | null;
          role?: 'client' | 'provider' | 'admin' | 'superadmin';
          first_name: string;
          last_name: string;
          avatar_url?: string | null;
          email_verified?: boolean;
          phone_verified?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          auth_id?: string | null;
          email?: string;
          phone?: string | null;
          role?: 'client' | 'provider' | 'admin' | 'superadmin';
          first_name?: string;
          last_name?: string;
          avatar_url?: string | null;
          email_verified?: boolean;
          phone_verified?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      clients: {
        Row: {
          id: string;
          user_id: string;
          fresha_client_id: string | null;
          date_of_birth: string | null;
          gender: string | null;
          preferred_pronouns: string | null;
          accepts_email_marketing: boolean;
          accepts_sms_marketing: boolean;
          preferred_contact_method: 'email' | 'sms' | 'push' | 'in_app';
          address_line1: string | null;
          address_line2: string | null;
          city: string | null;
          state: string | null;
          postal_code: string | null;
          country: string;
          emergency_contact_name: string | null;
          emergency_contact_phone: string | null;
          emergency_contact_relation: string | null;
          allergies_summary: string | null;
          medications_summary: string | null;
          medical_conditions_summary: string | null;
          is_new_client: boolean;
          consult_completed_at: string | null;
          is_vip: boolean;
          is_blocked: boolean;
          block_reason: string | null;
          referral_source: string | null;
          referred_by_client_id: string | null;
          internal_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          fresha_client_id?: string | null;
          date_of_birth?: string | null;
          gender?: string | null;
          preferred_pronouns?: string | null;
          accepts_email_marketing?: boolean;
          accepts_sms_marketing?: boolean;
          preferred_contact_method?: 'email' | 'sms' | 'push' | 'in_app';
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          country?: string;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          emergency_contact_relation?: string | null;
          allergies_summary?: string | null;
          medications_summary?: string | null;
          medical_conditions_summary?: string | null;
          is_new_client?: boolean;
          consult_completed_at?: string | null;
          is_vip?: boolean;
          is_blocked?: boolean;
          block_reason?: string | null;
          referral_source?: string | null;
          referred_by_client_id?: string | null;
          internal_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          fresha_client_id?: string | null;
          date_of_birth?: string | null;
          gender?: string | null;
          preferred_pronouns?: string | null;
          accepts_email_marketing?: boolean;
          accepts_sms_marketing?: boolean;
          preferred_contact_method?: 'email' | 'sms' | 'push' | 'in_app';
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          country?: string;
          emergency_contact_name?: string | null;
          emergency_contact_phone?: string | null;
          emergency_contact_relation?: string | null;
          allergies_summary?: string | null;
          medications_summary?: string | null;
          medical_conditions_summary?: string | null;
          is_new_client?: boolean;
          consult_completed_at?: string | null;
          is_vip?: boolean;
          is_blocked?: boolean;
          block_reason?: string | null;
          referral_source?: string | null;
          referred_by_client_id?: string | null;
          internal_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      providers: {
        Row: {
          id: string;
          user_id: string;
          credentials: string | null;
          license_number: string | null;
          license_state: string | null;
          npi_number: string | null;
          bio: string | null;
          specialties: string[] | null;
          services_offered: string[] | null;
          default_buffer_minutes: number;
          max_daily_appointments: number;
          accepts_new_clients: boolean;
          color_hex: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          credentials?: string | null;
          license_number?: string | null;
          license_state?: string | null;
          npi_number?: string | null;
          bio?: string | null;
          specialties?: string[] | null;
          services_offered?: string[] | null;
          default_buffer_minutes?: number;
          max_daily_appointments?: number;
          accepts_new_clients?: boolean;
          color_hex?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          credentials?: string | null;
          license_number?: string | null;
          license_state?: string | null;
          npi_number?: string | null;
          bio?: string | null;
          specialties?: string[] | null;
          services_offered?: string[] | null;
          default_buffer_minutes?: number;
          max_daily_appointments?: number;
          accepts_new_clients?: boolean;
          color_hex?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      locations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          address_line1: string;
          address_line2: string | null;
          city: string;
          state: string;
          postal_code: string;
          country: string;
          phone: string | null;
          email: string | null;
          business_hours: Json | null;
          timezone: string;
          is_active: boolean;
          accepts_online_booking: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          address_line1: string;
          address_line2?: string | null;
          city: string;
          state: string;
          postal_code: string;
          country?: string;
          phone?: string | null;
          email?: string | null;
          business_hours?: Json | null;
          timezone?: string;
          is_active?: boolean;
          accepts_online_booking?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          address_line1?: string;
          address_line2?: string | null;
          city?: string;
          state?: string;
          postal_code?: string;
          country?: string;
          phone?: string | null;
          email?: string | null;
          business_hours?: Json | null;
          timezone?: string;
          is_active?: boolean;
          accepts_online_booking?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      service_categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          icon: string | null;
          display_order: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          icon?: string | null;
          display_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          icon?: string | null;
          display_order?: number;
          is_active?: boolean;
          created_at?: string;
        };
      };
      services: {
        Row: {
          id: string;
          category_id: string | null;
          name: string;
          slug: string;
          description: string | null;
          short_description: string | null;
          price_cents: number;
          price_display: string | null;
          price_type: string;
          duration_minutes: number;
          buffer_before_minutes: number;
          buffer_after_minutes: number;
          deposit_required: boolean;
          deposit_amount_cents: number | null;
          deposit_type: string;
          requires_consult: boolean;
          requires_intake: boolean;
          requires_consent: boolean;
          requires_labs: boolean;
          requires_telehealth_clearance: boolean;
          minimum_age: number | null;
          contraindications: string[] | null;
          max_advance_booking_days: number;
          min_advance_booking_hours: number;
          allow_online_booking: boolean;
          addon_service_ids: string[] | null;
          related_service_ids: string[] | null;
          image_url: string | null;
          display_order: number;
          is_featured: boolean;
          is_active: boolean;
          primary_persona_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          category_id?: string | null;
          name: string;
          slug: string;
          description?: string | null;
          short_description?: string | null;
          price_cents: number;
          price_display?: string | null;
          price_type?: string;
          duration_minutes: number;
          buffer_before_minutes?: number;
          buffer_after_minutes?: number;
          deposit_required?: boolean;
          deposit_amount_cents?: number | null;
          deposit_type?: string;
          requires_consult?: boolean;
          requires_intake?: boolean;
          requires_consent?: boolean;
          requires_labs?: boolean;
          requires_telehealth_clearance?: boolean;
          minimum_age?: number | null;
          contraindications?: string[] | null;
          max_advance_booking_days?: number;
          min_advance_booking_hours?: number;
          allow_online_booking?: boolean;
          addon_service_ids?: string[] | null;
          related_service_ids?: string[] | null;
          image_url?: string | null;
          display_order?: number;
          is_featured?: boolean;
          is_active?: boolean;
          primary_persona_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          category_id?: string | null;
          name?: string;
          slug?: string;
          description?: string | null;
          short_description?: string | null;
          price_cents?: number;
          price_display?: string | null;
          price_type?: string;
          duration_minutes?: number;
          buffer_before_minutes?: number;
          buffer_after_minutes?: number;
          deposit_required?: boolean;
          deposit_amount_cents?: number | null;
          deposit_type?: string;
          requires_consult?: boolean;
          requires_intake?: boolean;
          requires_consent?: boolean;
          requires_labs?: boolean;
          requires_telehealth_clearance?: boolean;
          minimum_age?: number | null;
          contraindications?: string[] | null;
          max_advance_booking_days?: number;
          min_advance_booking_hours?: number;
          allow_online_booking?: boolean;
          addon_service_ids?: string[] | null;
          related_service_ids?: string[] | null;
          image_url?: string | null;
          display_order?: number;
          is_featured?: boolean;
          is_active?: boolean;
          primary_persona_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      appointments: {
        Row: {
          id: string;
          client_id: string | null;
          provider_id: string | null;
          service_id: string | null;
          location_id: string | null;
          starts_at: string;
          ends_at: string;
          status: 'pending' | 'confirmed' | 'checked_in' | 'in_progress' | 'completed' | 'cancelled' | 'no_show';
          deposit_required: boolean;
          deposit_amount_cents: number | null;
          deposit_paid: boolean;
          deposit_paid_at: string | null;
          deposit_transaction_id: string | null;
          intake_completed: boolean;
          consent_signed: boolean;
          addon_service_ids: string[] | null;
          client_notes: string | null;
          provider_notes: string | null;
          cancelled_at: string | null;
          cancelled_by: string | null;
          cancel_reason: string | null;
          checked_in_at: string | null;
          reminder_sent_24h: boolean;
          reminder_sent_2h: boolean;
          booked_by: string | null;
          booking_source: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id?: string | null;
          provider_id?: string | null;
          service_id?: string | null;
          location_id?: string | null;
          starts_at: string;
          ends_at: string;
          status?: 'pending' | 'confirmed' | 'checked_in' | 'in_progress' | 'completed' | 'cancelled' | 'no_show';
          deposit_required?: boolean;
          deposit_amount_cents?: number | null;
          deposit_paid?: boolean;
          deposit_paid_at?: string | null;
          deposit_transaction_id?: string | null;
          intake_completed?: boolean;
          consent_signed?: boolean;
          addon_service_ids?: string[] | null;
          client_notes?: string | null;
          provider_notes?: string | null;
          cancelled_at?: string | null;
          cancelled_by?: string | null;
          cancel_reason?: string | null;
          checked_in_at?: string | null;
          reminder_sent_24h?: boolean;
          reminder_sent_2h?: boolean;
          booked_by?: string | null;
          booking_source?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string | null;
          provider_id?: string | null;
          service_id?: string | null;
          location_id?: string | null;
          starts_at?: string;
          ends_at?: string;
          status?: 'pending' | 'confirmed' | 'checked_in' | 'in_progress' | 'completed' | 'cancelled' | 'no_show';
          deposit_required?: boolean;
          deposit_amount_cents?: number | null;
          deposit_paid?: boolean;
          deposit_paid_at?: string | null;
          deposit_transaction_id?: string | null;
          intake_completed?: boolean;
          consent_signed?: boolean;
          addon_service_ids?: string[] | null;
          client_notes?: string | null;
          provider_notes?: string | null;
          cancelled_at?: string | null;
          cancelled_by?: string | null;
          cancel_reason?: string | null;
          checked_in_at?: string | null;
          reminder_sent_24h?: boolean;
          reminder_sent_2h?: boolean;
          booked_by?: string | null;
          booking_source?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      memberships: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          price_cents: number;
          interval: string;
          benefits: Json;
          stripe_product_id: string | null;
          stripe_price_id: string | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          price_cents: number;
          interval: string;
          benefits: Json;
          stripe_product_id?: string | null;
          stripe_price_id?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          price_cents?: number;
          interval?: string;
          benefits?: Json;
          stripe_product_id?: string | null;
          stripe_price_id?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
      };
      client_memberships: {
        Row: {
          id: string;
          client_id: string;
          membership_id: string;
          status: 'active' | 'past_due' | 'cancelled' | 'paused';
          started_at: string;
          current_period_start: string | null;
          current_period_end: string | null;
          cancelled_at: string | null;
          stripe_subscription_id: string | null;
          stripe_customer_id: string | null;
          free_service_claimed: boolean;
          free_service_claimed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          membership_id: string;
          status?: 'active' | 'past_due' | 'cancelled' | 'paused';
          started_at?: string;
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancelled_at?: string | null;
          stripe_subscription_id?: string | null;
          stripe_customer_id?: string | null;
          free_service_claimed?: boolean;
          free_service_claimed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          membership_id?: string;
          status?: 'active' | 'past_due' | 'cancelled' | 'paused';
          started_at?: string;
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancelled_at?: string | null;
          stripe_subscription_id?: string | null;
          stripe_customer_id?: string | null;
          free_service_claimed?: boolean;
          free_service_claimed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      transactions: {
        Row: {
          id: string;
          client_id: string | null;
          appointment_id: string | null;
          membership_id: string | null;
          type: 'payment' | 'deposit' | 'refund' | 'credit' | 'membership_charge';
          amount_cents: number;
          description: string | null;
          stripe_payment_intent_id: string | null;
          stripe_charge_id: string | null;
          stripe_refund_id: string | null;
          status: string;
          processed_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          client_id?: string | null;
          appointment_id?: string | null;
          membership_id?: string | null;
          type: 'payment' | 'deposit' | 'refund' | 'credit' | 'membership_charge';
          amount_cents: number;
          description?: string | null;
          stripe_payment_intent_id?: string | null;
          stripe_charge_id?: string | null;
          stripe_refund_id?: string | null;
          status?: string;
          processed_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string | null;
          appointment_id?: string | null;
          membership_id?: string | null;
          type?: 'payment' | 'deposit' | 'refund' | 'credit' | 'membership_charge';
          amount_cents?: number;
          description?: string | null;
          stripe_payment_intent_id?: string | null;
          stripe_charge_id?: string | null;
          stripe_refund_id?: string | null;
          status?: string;
          processed_by?: string | null;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      user_role: 'client' | 'provider' | 'admin' | 'superadmin';
      appointment_status: 'pending' | 'confirmed' | 'checked_in' | 'in_progress' | 'completed' | 'cancelled' | 'no_show';
      membership_status: 'active' | 'past_due' | 'cancelled' | 'paused';
      notification_channel: 'email' | 'sms' | 'push' | 'in_app';
      transaction_type: 'payment' | 'deposit' | 'refund' | 'credit' | 'membership_charge';
    };
  };
};

// ============================================================
// HELPER TYPES
// ============================================================

export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type Insertable<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert'];
export type Updatable<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update'];
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T];
