import type { RxOpsConsolePayload } from "@/lib/rx-ops/types";

/** Fictional demo records — matches approved RX Ops Console prototype. */
export function rxOpsSamplePayload(formularySkuCount: number): RxOpsConsolePayload {
  const requests = [
    {
      id: "demo:q1",
      kind: "intake" as const,
      patientName: "Jamie Rivera",
      initials: "JR",
      meta: "34 · F · IL",
      compound: "Semaglutide",
      product: "Semaglutide / B6",
      reason: "Weight-loss refill · dose stable",
      stage: "Clinical review" as const,
      submittedAt: new Date(Date.now() - 18 * 60000).toISOString(),
      submittedLabel: "18 min ago",
      track: "glp1" as const,
      phone: "(630) 555-0114",
      email: "jamie.r@example.com",
      paymentStatus: "paid",
      paymentAmountUsd: 472.5,
      intakeRef: "DEMO-Q1",
      detailHref: "#",
      actionHref: "#",
    },
    {
      id: "demo:q2",
      kind: "intake" as const,
      patientName: "Alex Chen",
      initials: "AC",
      meta: "41 · M · IL",
      compound: "Testosterone Cypionate",
      product: "Testosterone Cypionate",
      reason: "New TRT protocol · labs attached",
      stage: "Clinical review" as const,
      submittedAt: new Date(Date.now() - 52 * 60000).toISOString(),
      submittedLabel: "52 min ago",
      track: "peptide" as const,
      phone: "(630) 555-0192",
      email: "alex.c@example.com",
      paymentStatus: "paid",
      paymentAmountUsd: 49,
      intakeRef: "DEMO-Q2",
      detailHref: "#",
      actionHref: "#",
    },
    {
      id: "demo:q3",
      kind: "regen" as const,
      patientName: "Morgan Bailey",
      initials: "MB",
      meta: "29 · F · IL",
      compound: "BPC-157",
      product: "BPC-157 / TB-500",
      reason: "Recovery peptide · new",
      stage: "Awaiting payment" as const,
      submittedAt: new Date(Date.now() - 3 * 3600000).toISOString(),
      submittedLabel: "3 hr ago",
      track: "peptide" as const,
      phone: "(630) 555-0177",
      email: "morgan.b@example.com",
      paymentStatus: "pending",
      paymentAmountUsd: 540,
      intakeRef: "DEMO-Q3",
      detailHref: "#",
      actionHref: "#",
    },
  ];

  return {
    generatedAt: new Date().toISOString(),
    requests,
    formulary: [],
    refills: [
      {
        patientName: "Jamie Rivera",
        plan: "Semaglutide / B6",
        pharmacy: "Formulation Rx",
        cadence: "Every 4 weeks",
        nextRefill: "Jul 20",
        nextSoon: true,
        price: "$236.25",
        status: "Active",
        reorderHref: "/rx/care",
      },
    ],
    payments: [
      {
        date: "Jul 6",
        patientName: "Jamie Rivera",
        forLabel: "Semaglutide 90-day",
        method: "Square link · card",
        amountUsd: 472.5,
        status: "paid",
      },
    ],
    threads: [
      {
        id: "demo-m1",
        patientName: "Jamie Rivera",
        initials: "JR",
        preview: "When will my refill ship?",
        time: "9:12a",
        unread: true,
        intakeRef: "DEMO-Q1",
      },
    ],
    overview: {
      requestsToReview: 2,
      revenue30dUsd: 14280,
      activeRefillPlans: 3,
      totalPatients: 4,
      awaitingShipment: 1,
      formularySkuCount: formularySkuCount || 214,
    },
    squareConnected: false,
  };
}
